In [1]:
# ════════════════════════════════════════════════════════════════════════════
# CELL 1 — LOAD ROUND 5 DATA
# ════════════════════════════════════════════════════════════════════════════

from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ROUND = 5
DAYS = [2, 3, 4]

DATA_DIR = Path("Data/round5")

ALGO_PRODUCTS = [
    # Galaxy Sounds Recorders
    "GALAXY_SOUNDS_DARK_MATTER",
    "GALAXY_SOUNDS_BLACK_HOLES",
    "GALAXY_SOUNDS_PLANETARY_RINGS",
    "GALAXY_SOUNDS_SOLAR_WINDS",
    "GALAXY_SOUNDS_SOLAR_FLAMES",

    # Vertical Sleeping Pods
    "SLEEP_POD_SUEDE",
    "SLEEP_POD_LAMB_WOOL",
    "SLEEP_POD_POLYESTER",
    "SLEEP_POD_NYLON",
    "SLEEP_POD_COTTON",

    # Organic Microchips
    "MICROCHIP_CIRCLE",
    "MICROCHIP_OVAL",
    "MICROCHIP_SQUARE",
    "MICROCHIP_RECTANGLE",
    "MICROCHIP_TRIANGLE",

    # Purification Pebbles
    "PEBBLES_XS",
    "PEBBLES_S",
    "PEBBLES_M",
    "PEBBLES_L",
    "PEBBLES_XL",

    # Domestic Robots
    "ROBOT_VACUUMING",
    "ROBOT_MOPPING",
    "ROBOT_DISHES",
    "ROBOT_LAUNDRY",
    "ROBOT_IRONING",

    # UV-Visors
    "UV_VISOR_YELLOW",
    "UV_VISOR_AMBER",
    "UV_VISOR_ORANGE",
    "UV_VISOR_RED",
    "UV_VISOR_MAGENTA",

    # Instant Translators
    "TRANSLATOR_SPACE_GRAY",
    "TRANSLATOR_ASTRO_BLACK",
    "TRANSLATOR_ECLIPSE_CHARCOAL",
    "TRANSLATOR_GRAPHITE_MIST",
    "TRANSLATOR_VOID_BLUE",

    # Construction Panels
    "PANEL_1X2",
    "PANEL_2X2",
    "PANEL_1X4",
    "PANEL_2X4",
    "PANEL_4X4",

    # Liquid Breath Oxygen Shakes
    "OXYGEN_SHAKE_MORNING_BREATH",
    "OXYGEN_SHAKE_EVENING_BREATH",
    "OXYGEN_SHAKE_MINT",
    "OXYGEN_SHAKE_CHOCOLATE",
    "OXYGEN_SHAKE_GARLIC",

    # Protein Snack Packs
    "SNACKPACK_CHOCOLATE",
    "SNACKPACK_VANILLA",
    "SNACKPACK_PISTACHIO",
    "SNACKPACK_STRAWBERRY",
    "SNACKPACK_RASPBERRY",
]

POSITION_LIMITS = {product: 10 for product in ALGO_PRODUCTS}

prices_parts = []
trades_parts = []

for day in DAYS:
    price_path = DATA_DIR / f"prices_round_{ROUND}_day_{day}.csv"
    trade_path = DATA_DIR / f"trades_round_{ROUND}_day_{day}.csv"

    p = pd.read_csv(price_path, sep=";")
    t = pd.read_csv(trade_path, sep=";")

    p["file_day"] = day
    t["file_day"] = day

    prices_parts.append(p)
    trades_parts.append(t)

prices = pd.concat(prices_parts, ignore_index=True)
trades = pd.concat(trades_parts, ignore_index=True)

# Standardise trade product column name.
if "symbol" in trades.columns and "product" not in trades.columns:
    trades = trades.rename(columns={"symbol": "product"})

# Keep only valid Round 5 algorithmic products.
prices = prices[prices["product"].isin(ALGO_PRODUCTS)].copy()
trades = trades[trades["product"].isin(ALGO_PRODUCTS)].copy()

# Useful global time index across days.
# Assumes timestamp resets each day.
min_day = min(DAYS)
prices["global_ts"] = (prices["file_day"] - min_day) * 1_000_000 + prices["timestamp"]
trades["global_ts"] = (trades["file_day"] - min_day) * 1_000_000 + trades["timestamp"]

prices = prices.sort_values(["product", "global_ts"]).reset_index(drop=True)
trades = trades.sort_values(["product", "global_ts"]).reset_index(drop=True)

# Basic sanity checks.
price_products = sorted(prices["product"].unique())
trade_products = sorted(trades["product"].unique())

missing_in_prices = sorted(set(ALGO_PRODUCTS) - set(price_products))
missing_in_trades = sorted(set(ALGO_PRODUCTS) - set(trade_products))

print("prices shape:", prices.shape)
print("trades shape:", trades.shape)
print()
print("Price products:", price_products)
print("Trade products:", trade_products)
print()
print("Missing in prices:", missing_in_prices)
print("Missing in trades:", missing_in_trades)
print()
print("Price days:", sorted(prices["file_day"].unique()))
print("Trade days:", sorted(trades["file_day"].unique()))
print()
print("Position limits:", POSITION_LIMITS)

display(prices.head())
display(trades.head())

prices shape: (1500000, 19)
trades shape: (35385, 9)

Price products: ['GALAXY_SOUNDS_BLACK_HOLES', 'GALAXY_SOUNDS_DARK_MATTER', 'GALAXY_SOUNDS_PLANETARY_RINGS', 'GALAXY_SOUNDS_SOLAR_FLAMES', 'GALAXY_SOUNDS_SOLAR_WINDS', 'MICROCHIP_CIRCLE', 'MICROCHIP_OVAL', 'MICROCHIP_RECTANGLE', 'MICROCHIP_SQUARE', 'MICROCHIP_TRIANGLE', 'OXYGEN_SHAKE_CHOCOLATE', 'OXYGEN_SHAKE_EVENING_BREATH', 'OXYGEN_SHAKE_GARLIC', 'OXYGEN_SHAKE_MINT', 'OXYGEN_SHAKE_MORNING_BREATH', 'PANEL_1X2', 'PANEL_1X4', 'PANEL_2X2', 'PANEL_2X4', 'PANEL_4X4', 'PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XL', 'PEBBLES_XS', 'ROBOT_DISHES', 'ROBOT_IRONING', 'ROBOT_LAUNDRY', 'ROBOT_MOPPING', 'ROBOT_VACUUMING', 'SLEEP_POD_COTTON', 'SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON', 'SLEEP_POD_POLYESTER', 'SLEEP_POD_SUEDE', 'SNACKPACK_CHOCOLATE', 'SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY', 'SNACKPACK_STRAWBERRY', 'SNACKPACK_VANILLA', 'TRANSLATOR_ASTRO_BLACK', 'TRANSLATOR_ECLIPSE_CHARCOAL', 'TRANSLATOR_GRAPHITE_MIST', 'TRANSLATOR_SPACE_GRAY', 'TRANSLATOR_VOID_BLUE', 'UV_VISOR_AMBER', 'UV_VISOR_MAGENTA', 'UV_VISOR_ORANGE', 'UV_VISOR_RED', 'UV_VISOR_YELLOW']
Trade products: ['GALAXY_SOUNDS_BLACK_HOLES', 'GALAXY_SOUNDS_DARK_MATTER', 'GALAXY_SOUNDS_PLANETARY_RINGS', 'GALAXY_SOUNDS_SOLAR_FLAMES', 'GALAXY_SOUNDS_SOLAR_WINDS', 'MICROCHIP_CIRCLE', 'MICROCHIP_OVAL', 'MICROCHIP_RECTANGLE', 'MICROCHIP_SQUARE', 'MICROCHIP_TRIANGLE', 'OXYGEN_SHAKE_CHOCOLATE', 'OXYGEN_SHAKE_EVENING_BREATH', 'OXYGEN_SHAKE_GARLIC', 'OXYGEN_SHAKE_MINT', 'OXYGEN_SHAKE_MORNING_BREATH', 'PANEL_1X2', 'PANEL_1X4', 'PANEL_2X2', 'PANEL_2X4', 'PANEL_4X4', 'PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XL', 'PEBBLES_XS', 'ROBOT_DISHES', 'ROBOT_IRONING', 'ROBOT_LAUNDRY', 'ROBOT_MOPPING', 'ROBOT_VACUUMING', 'SLEEP_POD_COTTON', 'SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON', 'SLEEP_POD_POLYESTER', 'SLEEP_POD_SUEDE', 'SNACKPACK_CHOCOLATE', 'SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY', 'SNACKPACK_STRAWBERRY', 'SNACKPACK_VANILLA', 'TRANSLATOR_ASTRO_BLACK', 'TRANSLATOR_ECLIPSE_CHARCOAL', 'TRANSLATOR_GRAPHITE_MIST', 'TRANSLATOR_SPACE_GRAY', 'TRANSLATOR_VOID_BLUE', 'UV_VISOR_AMBER', 'UV_VISOR_MAGENTA', 'UV_VISOR_ORANGE', 'UV_VISOR_RED', 'UV_VISOR_YELLOW']

Missing in prices: []
Missing in trades: []

Price days: [np.int64(2), np.int64(3), np.int64(4)]
Trade days: [np.int64(2), np.int64(3), np.int64(4)]

Position limits: {'GALAXY_SOUNDS_DARK_MATTER': 10, 'GALAXY_SOUNDS_BLACK_HOLES': 10, 'GALAXY_SOUNDS_PLANETARY_RINGS': 10, 'GALAXY_SOUNDS_SOLAR_WINDS': 10, 'GALAXY_SOUNDS_SOLAR_FLAMES': 10, 'SLEEP_POD_SUEDE': 10, 'SLEEP_POD_LAMB_WOOL': 10, 'SLEEP_POD_POLYESTER': 10, 'SLEEP_POD_NYLON': 10, 'SLEEP_POD_COTTON': 10, 'MICROCHIP_CIRCLE': 10, 'MICROCHIP_OVAL': 10, 'MICROCHIP_SQUARE': 10, 'MICROCHIP_RECTANGLE': 10, 'MICROCHIP_TRIANGLE': 10, 'PEBBLES_XS': 10, 'PEBBLES_S': 10, 'PEBBLES_M': 10, 'PEBBLES_L': 10, 'PEBBLES_XL': 10, 'ROBOT_VACUUMING': 10, 'ROBOT_MOPPING': 10, 'ROBOT_DISHES': 10, 'ROBOT_LAUNDRY': 10, 'ROBOT_IRONING': 10, 'UV_VISOR_YELLOW': 10, 'UV_VISOR_AMBER': 10, 'UV_VISOR_ORANGE': 10, 'UV_VISOR_RED': 10, 'UV_VISOR_MAGENTA': 10, 'TRANSLATOR_SPACE_GRAY': 10, 'TRANSLATOR_ASTRO_BLACK': 10, 'TRANSLATOR_ECLIPSE_CHARCOAL': 10, 'TRANSLATOR_GRAPHITE_MIST': 10, 'TRANSLATOR_VOID_BLUE': 10, 'PANEL_1X2': 10, 'PANEL_2X2': 10, 'PANEL_1X4': 10, 'PANEL_2X4': 10, 'PANEL_4X4': 10, 'OXYGEN_SHAKE_MORNING_BREATH': 10, 'OXYGEN_SHAKE_EVENING_BREATH': 10, 'OXYGEN_SHAKE_MINT': 10, 'OXYGEN_SHAKE_CHOCOLATE': 10, 'OXYGEN_SHAKE_GARLIC': 10, 'SNACKPACK_CHOCOLATE': 10, 'SNACKPACK_VANILLA': 10, 'SNACKPACK_PISTACHIO': 10, 'SNACKPACK_STRAWBERRY': 10, 'SNACKPACK_RASPBERRY': 10}

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss,file_day,global_ts
0,2,0,GALAXY_SOUNDS_BLACK_HOLES,9994,22,9992.0,26.0,NaN,NaN,10006,22,10008.0,26.0,NaN,NaN,10000.0,0.0,2,0
1,2,100,GALAXY_SOUNDS_BLACK_HOLES,10001,18,10000.0,25.0,NaN,NaN,10014,18,10016.0,25.0,NaN,NaN,10007.5,0.0,2,100
2,2,200,GALAXY_SOUNDS_BLACK_HOLES,9996,19,9995.0,31.0,NaN,NaN,10009,19,10011.0,31.0,NaN,NaN,10002.5,0.0,2,200
3,2,300,GALAXY_SOUNDS_BLACK_HOLES,9994,25,9993.0,33.0,NaN,NaN,10007,25,10009.0,33.0,NaN,NaN,10000.5,0.0,2,300
4,2,400,GALAXY_SOUNDS_BLACK_HOLES,9999,14,9997.0,32.0,NaN,NaN,10012,14,10013.0,32.0,NaN,NaN,10005.5,0.0,2,400

,timestamp,buyer,seller,product,currency,price,quantity,file_day,global_ts
0,1700,NaN,NaN,GALAXY_SOUNDS_BLACK_HOLES,XIRECS,9969.0,4,2,1700
1,14500,NaN,NaN,GALAXY_SOUNDS_BLACK_HOLES,XIRECS,9749.0,1,2,14500
2,15100,NaN,NaN,GALAXY_SOUNDS_BLACK_HOLES,XIRECS,9764.0,2,2,15100
3,26500,NaN,NaN,GALAXY_SOUNDS_BLACK_HOLES,XIRECS,9656.0,4,2,26500
4,36400,NaN,NaN,GALAXY_SOUNDS_BLACK_HOLES,XIRECS,9675.0,4,2,36400

In [3]:
# =========================
# UV VISORS DISCOVERY + STRICT BACKTEST NOTEBOOK
# Assumes you already have: prices = market dataframe
# =========================

import numpy as np
import pandas as pd
from pathlib import Path
from itertools import combinations, permutations, product
import time

OUTDIR = Path("analysis_outputs/uv_visors")
OUTDIR.mkdir(parents=True, exist_ok=True)

VISORS = [
    "UV_VISOR_YELLOW",
    "UV_VISOR_AMBER",
    "UV_VISOR_ORANGE",
    "UV_VISOR_RED",
    "UV_VISOR_MAGENTA",
]

COLOR_SHORT = {
    "UV_VISOR_YELLOW": "YELLOW",
    "UV_VISOR_AMBER": "AMBER",
    "UV_VISOR_ORANGE": "ORANGE",
    "UV_VISOR_RED": "RED",
    "UV_VISOR_MAGENTA": "MAGENTA",
}

# Ordered colour spectrum assumption:
# YELLOW -> AMBER -> ORANGE -> RED -> MAGENTA
COLOR_ORDER = VISORS


# =========================
# 1) Robust dataframe parsing
# =========================

def pick_col(df, options, required=True):
    for c in options:
        if c in df.columns:
            return c
    if required:
        raise ValueError(f"Could not find any of columns: {options}")
    return None


def prepare_prices_df(prices):
    df = prices.copy()

    product_col = pick_col(df, ["product", "symbol", "asset", "instrument"])
    day_col = pick_col(df, ["day", "trading_day", "date"])
    ts_col = pick_col(df, ["timestamp", "time", "ts"])

    bid_col = pick_col(
        df,
        ["bid_price_1", "bid1", "best_bid", "bid_price", "bid"],
        required=False,
    )
    ask_col = pick_col(
        df,
        ["ask_price_1", "ask1", "best_ask", "ask_price", "ask"],
        required=False,
    )
    mid_col = pick_col(
        df,
        ["mid_price", "mid", "fair", "price"],
        required=False,
    )

    if mid_col is None:
        if bid_col is None or ask_col is None:
            raise ValueError("Need either mid column, or bid+ask columns.")
        df["_mid"] = (df[bid_col] + df[ask_col]) / 2
        mid_col = "_mid"

    if bid_col is None:
        df["_bid"] = df[mid_col]
        bid_col = "_bid"
    if ask_col is None:
        df["_ask"] = df[mid_col]
        ask_col = "_ask"

    return df, product_col, day_col, ts_col, bid_col, ask_col, mid_col


def make_day_panels(prices, products):
    df, product_col, day_col, ts_col, bid_col, ask_col, mid_col = prepare_prices_df(prices)
    df = df[df[product_col].isin(products)].copy()

    missing = sorted(set(products) - set(df[product_col].unique()))
    if missing:
        raise ValueError(f"Missing visor products in dataframe: {missing}")

    panels = {}
    for day, d in df.groupby(day_col):
        mid = d.pivot(index=ts_col, columns=product_col, values=mid_col).sort_index()
        bid = d.pivot(index=ts_col, columns=product_col, values=bid_col).sort_index()
        ask = d.pivot(index=ts_col, columns=product_col, values=ask_col).sort_index()

        # Align columns/order and fill very small data gaps if any.
        mid = mid.reindex(columns=products).ffill().bfill()
        bid = bid.reindex(columns=products).ffill().bfill()
        ask = ask.reindex(columns=products).ffill().bfill()

        panels[int(day)] = {"mid": mid, "bid": bid, "ask": ask}

    return panels


panels = make_day_panels(prices, VISORS)
DAYS = sorted(panels.keys())

print("Days:", DAYS)
for day in DAYS:
    print(
        f"Day {day}: mid={panels[day]['mid'].shape}, "
        f"bid={panels[day]['bid'].shape}, ask={panels[day]['ask'].shape}"
    )

Days: [2, 3, 4]
Day 2: mid=(10000, 5), bid=(10000, 5), ask=(10000, 5)
Day 3: mid=(10000, 5), bid=(10000, 5), ask=(10000, 5)
Day 4: mid=(10000, 5), bid=(10000, 5), ask=(10000, 5)

In [5]:
# =========================
# 2) Helpers: z-score, q generation, execution PnL
# =========================

def rolling_z(s, window):
    s = pd.Series(s).replace([np.inf, -np.inf], np.nan)
    mu = s.rolling(window, min_periods=window).mean()
    sd = s.rolling(window, min_periods=window).std(ddof=0)
    return ((s - mu) / sd).replace([np.inf, -np.inf], np.nan)


def q_from_weights(weights, gross=60, max_abs=80):
    """
    Converts arbitrary signal/position weights into integer trade quantities.
    Sign convention:
      weights = desired position when signal is LOW for mean-reversion.
    """
    w = np.asarray(weights, dtype=float)
    if np.allclose(w, 0):
        return np.zeros_like(w, dtype=int)

    q = w / np.sum(np.abs(w)) * gross
    q = np.rint(q).astype(int)

    # Avoid losing tiny but intentional legs after rounding.
    for i, wi in enumerate(w):
        if wi != 0 and q[i] == 0:
            q[i] = int(np.sign(wi))

    if np.max(np.abs(q)) > max_abs:
        scale = max_abs / np.max(np.abs(q))
        q = np.rint(q * scale).astype(int)

    return q


def exec_pnl(pos, entry_i, exit_i, bid, ask):
    """
    Conservative execution:
      Long: buy at entry ask, sell at exit bid.
      Short: sell at entry bid, buy at exit ask.
    """
    pos = np.asarray(pos, dtype=float)

    entry_bid = bid.iloc[entry_i].values.astype(float)
    entry_ask = ask.iloc[entry_i].values.astype(float)
    exit_bid = bid.iloc[exit_i].values.astype(float)
    exit_ask = ask.iloc[exit_i].values.astype(float)

    long = pos > 0
    short = pos < 0

    pnl = 0.0
    pnl += np.sum(pos[long] * (exit_bid[long] - entry_ask[long]))
    pnl += np.sum((-pos[short]) * (entry_bid[short] - exit_ask[short]))
    return float(pnl)


def summarise_day_rows(rows):
    if not rows:
        return {
            "trade_count": 0,
            "day_pnl": 0.0,
            "hit_rate": np.nan,
            "avg_trade_pnl": np.nan,
            "median_trade_pnl": np.nan,
        }

    pnls = np.array([r["exec_pnl"] for r in rows], dtype=float)
    return {
        "trade_count": len(pnls),
        "day_pnl": float(pnls.sum()),
        "hit_rate": float(np.mean(pnls > 0)),
        "avg_trade_pnl": float(np.mean(pnls)),
        "median_trade_pnl": float(np.median(pnls)),
    }


def robust_score(total_pnl, min_day_pnl, mean_hit_rate, one_day_dependency):
    if total_pnl == 0 or not np.isfinite(total_pnl):
        return -np.inf
    dep_penalty = max(0.0, one_day_dependency - 0.50) * abs(total_pnl) * 0.5
    return float(total_pnl + 2.0 * min_day_pnl + 5000.0 * mean_hit_rate - dep_penalty)

In [6]:
# =========================
# 3) Candidate generation
# Includes pairs, lead-lag, baskets, colour gradients, and colour mixing
# =========================

def idx(product):
    return VISORS.index(product)


def vector_from_dict(d):
    v = np.zeros(len(VISORS), dtype=float)
    for k, val in d.items():
        v[idx(k)] = val
    return v


def linear_signal(weights):
    weights = np.asarray(weights, dtype=float)
    def f(mid):
        return mid.dot(weights)
    return f


def pair_spread_signal(a, b):
    return lambda mid: mid[a] - mid[b]


def pair_logratio_signal(a, b):
    return lambda mid: np.log(mid[a] / mid[b])


def pair_ratio_signal(a, b):
    return lambda mid: mid[a] / mid[b]


def leader_return_signal(leader, lag):
    return lambda mid: np.log(mid[leader] / mid[leader].shift(lag))


def static_poly_resid_signal(y, x, degree):
    """
    Discovery-only: fits y ~ poly(x) using the full day.
    Useful to detect nonlinear relationships, but don't trust as final
    unless later converted to rolling/online form.
    """
    def f(mid):
        xx = mid[x].astype(float)
        yy = mid[y].astype(float)
        ok = xx.notna() & yy.notna()
        if ok.sum() < degree + 2:
            return pd.Series(np.nan, index=mid.index)
        coefs = np.polyfit(xx[ok], yy[ok], degree)
        pred = np.polyval(coefs, xx)
        return yy - pred
    return f


def add_candidate(cands, name, family, signal_type, signal_func, pos_low_weights, note):
    cands.append({
        "candidate": name,
        "family": family,
        "signal_type": signal_type,
        "signal_func": signal_func,
        "pos_low_weights": np.asarray(pos_low_weights, dtype=float),
        "note": note,
    })


def make_uv_visor_candidates(include_static_poly=True):
    cands = []

    # ---- Single product own mean-reversion / trend
    for p in VISORS:
        w = vector_from_dict({p: 1})
        short = COLOR_SHORT[p]

        add_candidate(
            cands,
            f"{short}_own_meanrev",
            "single",
            "own_price",
            lambda mid, p=p: mid[p],
            w,
            f"{short} own price mean-reversion",
        )

        add_candidate(
            cands,
            f"{short}_own_trend",
            "single",
            "own_price",
            lambda mid, p=p: mid[p],
            -w,
            f"{short} own price trend/breakout",
        )

    # ---- Pairwise spreads / ratios / logratios, both meanrev and trend
    for a, b in combinations(VISORS, 2):
        sa, sb = COLOR_SHORT[a], COLOR_SHORT[b]
        w = vector_from_dict({a: 1, b: -1})

        for signal_type, sig_fn in [
            ("spread", pair_spread_signal(a, b)),
            ("logratio", pair_logratio_signal(a, b)),
            ("ratio", pair_ratio_signal(a, b)),
        ]:
            add_candidate(
                cands,
                f"{sa}_vs_{sb}_{signal_type}_mr",
                "pairwise",
                signal_type,
                sig_fn,
                w,
                f"{sa} - {sb} mean-reversion",
            )
            add_candidate(
                cands,
                f"{sa}_vs_{sb}_{signal_type}_trend",
                "pairwise",
                signal_type,
                sig_fn,
                -w,
                f"{sa} - {sb} trend",
            )

        if include_static_poly:
            for deg in [2, 3]:
                add_candidate(
                    cands,
                    f"{sa}_resid_vs_{sb}_poly{deg}_mr_DISCOVERY",
                    "pairwise_nonlinear_discovery",
                    f"poly{deg}_resid",
                    static_poly_resid_signal(a, b, deg),
                    w,
                    f"{sa} residual versus degree-{deg} function of {sb}; discovery-only",
                )

                add_candidate(
                    cands,
                    f"{sb}_resid_vs_{sa}_poly{deg}_mr_DISCOVERY",
                    "pairwise_nonlinear_discovery",
                    f"poly{deg}_resid",
                    static_poly_resid_signal(b, a, deg),
                    -w,
                    f"{sb} residual versus degree-{deg} function of {sa}; discovery-only",
                )

    # ---- Lead-lag: every leader/follower, follow and inverse
    for leader, follower in permutations(VISORS, 2):
        sl, sf = COLOR_SHORT[leader], COLOR_SHORT[follower]
        follower_w = vector_from_dict({follower: 1})

        for lag in [50, 100, 250, 500, 1000]:
            sig = leader_return_signal(leader, lag)

            # follow: leader down => short follower, leader up => long follower
            add_candidate(
                cands,
                f"lead_{sl}_to_{sf}_follow_lag{lag}",
                "lead_lag",
                "leader_return_follow",
                sig,
                -follower_w,
                f"{sf} follows {sl} return over lag {lag}",
            )

            # inverse: leader down => long follower, leader up => short follower
            add_candidate(
                cands,
                f"lead_{sl}_to_{sf}_inverse_lag{lag}",
                "lead_lag",
                "leader_return_inverse",
                sig,
                follower_w,
                f"{sf} inversely follows {sl} return over lag {lag}",
            )

    # ---- Ordered colour spectrum baskets
    Y, A, O, R, M = VISORS

    basket_defs = {
        "spectrum_gradient_2_1_0_1_2": {Y: -2, A: -1, O: 0, R: 1, M: 2},
        "spectrum_gradient_1_1_0_1_1": {Y: -1, A: -1, O: 0, R: 1, M: 1},
        "warm_vs_cool": {Y: -1, A: -1, O: 1, R: 1, M: 1},
        "hot_vs_nonhot": {Y: -1, A: -1, O: -1, R: 1.5, M: 1.5},
        "red_extreme_vs_rest": {Y: -0.25, A: -0.25, O: -0.25, R: 1, M: -0.25},
        "magenta_extreme_vs_rest": {Y: -0.25, A: -0.25, O: -0.25, R: -0.25, M: 1},
        "orange_red_vs_others": {Y: -1, A: -1, O: 1.5, R: 1.5, M: -1},
        "yellow_amber_vs_red_magenta": {Y: 1, A: 1, O: 0, R: -1, M: -1},
    }

    for name, wd in basket_defs.items():
        w = vector_from_dict(wd)
        add_candidate(
            cands,
            f"basket_{name}_mr",
            "colour_basket",
            "linear_basket",
            linear_signal(w),
            w,
            f"Colour basket mean-reversion: {name}",
        )
        add_candidate(
            cands,
            f"basket_{name}_trend",
            "colour_basket",
            "linear_basket",
            linear_signal(w),
            -w,
            f"Colour basket trend: {name}",
        )

    # ---- Adjacent neighbour spreads along colour spectrum
    adjacent = [(Y, A), (A, O), (O, R), (R, M)]
    for a, b in adjacent:
        sa, sb = COLOR_SHORT[a], COLOR_SHORT[b]
        w = vector_from_dict({a: 1, b: -1})
        add_candidate(
            cands,
            f"adjacent_{sa}_vs_{sb}_spread_mr",
            "colour_adjacent",
            "spread",
            pair_spread_signal(a, b),
            w,
            f"Adjacent colour spread {sa}-{sb} mean-reversion",
        )

    # ---- Explicit colour mixing / blend residuals
    # Signal: target - weighted blend(source1, source2)
    # Low signal => target cheap vs blend => long target, short blend legs.
    mix_specs = []

    # Local spectrum blends
    mix_specs += [
        ("AMBER_blend_YELLOW_ORANGE_50_50", A, Y, O, 0.50),
        ("ORANGE_blend_AMBER_RED_50_50", O, A, R, 0.50),
        ("RED_blend_ORANGE_MAGENTA_50_50", R, O, M, 0.50),
    ]

    # Wider colour-mixing hypotheses
    for alpha in [0.25, 0.50, 0.75]:
        mix_specs += [
            (f"ORANGE_blend_YELLOW_RED_{int(alpha*100)}_{int((1-alpha)*100)}", O, Y, R, alpha),
            (f"RED_blend_YELLOW_MAGENTA_{int(alpha*100)}_{int((1-alpha)*100)}", R, Y, M, alpha),
            (f"AMBER_blend_YELLOW_RED_{int(alpha*100)}_{int((1-alpha)*100)}", A, Y, R, alpha),
            (f"ORANGE_blend_YELLOW_MAGENTA_{int(alpha*100)}_{int((1-alpha)*100)}", O, Y, M, alpha),
        ]

    for name, target, s1, s2, alpha in mix_specs:
        w = vector_from_dict({
            target: 1,
            s1: -alpha,
            s2: -(1 - alpha),
        })
        add_candidate(
            cands,
            f"mix_{name}_mr",
            "colour_mixing",
            "blend_residual",
            linear_signal(w),
            w,
            f"{COLOR_SHORT[target]} residual versus blend of {COLOR_SHORT[s1]} and {COLOR_SHORT[s2]}",
        )

    # ---- Curvature / second-difference relationships along the colour line
    curvature_specs = [
        ("curvature_YELLOW_AMBER_ORANGE", {Y: 1, A: -2, O: 1}),
        ("curvature_AMBER_ORANGE_RED", {A: 1, O: -2, R: 1}),
        ("curvature_ORANGE_RED_MAGENTA", {O: 1, R: -2, M: 1}),
        ("curvature_YELLOW_ORANGE_RED", {Y: 1, O: -2, R: 1}),
        ("curvature_AMBER_RED_MAGENTA", {A: 1, R: -2, M: 1}),
    ]

    for name, wd in curvature_specs:
        w = vector_from_dict(wd)
        add_candidate(
            cands,
            f"{name}_mr",
            "colour_curvature",
            "second_difference",
            linear_signal(w),
            w,
            f"Colour curvature mean-reversion: {name}",
        )

    return cands


candidates = make_uv_visor_candidates(include_static_poly=True)
print("Candidates generated:", len(candidates))
print(pd.Series([c["family"] for c in candidates]).value_counts())

Candidates generated: 350
lead_lag                        200
pairwise                         60
pairwise_nonlinear_discovery     40
colour_basket                    16
colour_mixing                    15
single                           10
colour_curvature                  5
colour_adjacent                   4
Name: count, dtype: int64

In [7]:
# =========================
# 4) Lead-lag diagnostics table
# Not a backtest, just correlation/edge discovery.
# =========================

def run_leadlag_diagnostics(panels, products, lags=(50, 100, 250, 500, 1000), horizons=(50, 100, 250, 500, 1000)):
    rows = []

    for leader, follower in permutations(products, 2):
        for lag in lags:
            for h in horizons:
                corrs = []
                edges = []

                for day, panel in panels.items():
                    mid = panel["mid"]
                    leader_ret = np.log(mid[leader] / mid[leader].shift(lag))
                    follower_future = mid[follower].shift(-h) - mid[follower]

                    z = rolling_z(leader_ret, max(250, lag * 2))
                    mask = z.abs() > 1.5

                    corr = leader_ret.corr(follower_future)
                    edge = np.nan
                    if mask.sum() > 10:
                        # Signed edge: if leader_ret positive, expected follower move;
                        # if negative, expected opposite sign.
                        edge = np.nanmean(np.sign(leader_ret[mask]) * follower_future[mask])

                    corrs.append(corr)
                    edges.append(edge)

                rows.append({
                    "leader": leader,
                    "follower": follower,
                    "lag": lag,
                    "future_horizon": h,
                    "mean_corr": float(np.nanmean(corrs)),
                    "mean_signed_edge": float(np.nanmean(edges)),
                    "abs_score": float(abs(np.nanmean(corrs)) * abs(np.nanmean(edges))),
                    "suggested_mode": "follow" if np.nanmean(corrs) > 0 else "inverse",
                })

    out = pd.DataFrame(rows).sort_values("abs_score", ascending=False)
    out.to_csv(OUTDIR / "uv_visors_leadlag_diagnostics.csv", index=False)
    return out


leadlag_diag = run_leadlag_diagnostics(panels, VISORS)
display(leadlag_diag.head(50))

,leader,follower,lag,future_horizon,mean_corr,mean_signed_edge,abs_score,suggested_mode
199,UV_VISOR_AMBER,UV_VISOR_MAGENTA,1000,1000,0.451211,218.437422,98.561429,follow
49,UV_VISOR_YELLOW,UV_VISOR_ORANGE,1000,1000,-0.439975,-97.643963,42.960894,inverse
318,UV_VISOR_RED,UV_VISOR_YELLOW,500,500,-0.327298,-108.636374,35.556429,inverse
494,UV_VISOR_MAGENTA,UV_VISOR_RED,500,1000,-0.263304,-95.814441,25.228362,inverse
319,UV_VISOR_RED,UV_VISOR_YELLOW,500,1000,-0.186026,-129.728806,24.132987,inverse
344,UV_VISOR_RED,UV_VISOR_AMBER,500,1000,0.250122,87.858101,21.975201,follow
398,UV_VISOR_RED,UV_VISOR_MAGENTA,1000,500,-0.169944,-108.121912,18.374695,inverse
394,UV_VISOR_RED,UV_VISOR_MAGENTA,500,1000,-0.127305,-139.870049,17.806143,inverse
317,UV_VISOR_RED,UV_VISOR_YELLOW,500,250,-0.293791,-60.018023,17.632756,inverse
198,UV_VISOR_AMBER,UV_VISOR_MAGENTA,1000,500,0.266334,63.350984,16.872509,follow
313,UV_VISOR_RED,UV_VISOR_YELLOW,250,500,-0.271444,-58.122977,15.777146,inverse
314,UV_VISOR_RED,UV_VISOR_YELLOW,250,1000,-0.210901,-73.026289,15.401353,inverse
374,UV_VISOR_RED,UV_VISOR_ORANGE,1000,1000,0.133333,114.167186,15.222240,follow
148,UV_VISOR_AMBER,UV_VISOR_ORANGE,1000,500,-0.140001,-105.852871,14.819469,inverse
68,UV_VISOR_YELLOW,UV_VISOR_RED,500,500,0.190693,76.463515,14.581058,follow
424,UV_VISOR_MAGENTA,UV_VISOR_YELLOW,1000,1000,0.149868,81.927576,12.278289,follow
348,UV_VISOR_RED,UV_VISOR_AMBER,1000,500,0.257741,46.749393,12.049234,follow
147,UV_VISOR_AMBER,UV_VISOR_ORANGE,1000,250,-0.151385,-77.220871,11.690087,inverse
343,UV_VISOR_RED,UV_VISOR_AMBER,500,500,0.305270,38.226947,11.669534,follow
474,UV_VISOR_MAGENTA,UV_VISOR_ORANGE,1000,1000,-0.142869,-79.353239,11.337083,inverse
139,UV_VISOR_AMBER,UV_VISOR_ORANGE,250,1000,-0.183037,-57.317661,10.491263,inverse
419,UV_VISOR_MAGENTA,UV_VISOR_YELLOW,500,1000,0.140939,71.233252,10.039538,follow
168,UV_VISOR_AMBER,UV_VISOR_RED,500,500,-0.186904,-50.981596,9.528663,inverse
393,UV_VISOR_RED,UV_VISOR_MAGENTA,500,500,-0.171932,-54.295051,9.335076,inverse
323,UV_VISOR_RED,UV_VISOR_YELLOW,1000,500,-0.167168,-55.208509,9.229092,inverse
48,UV_VISOR_YELLOW,UV_VISOR_ORANGE,1000,500,-0.230326,-36.461047,8.397909,inverse
149,UV_VISOR_AMBER,UV_VISOR_ORANGE,1000,1000,-0.065424,-127.360353,8.332402,inverse
322,UV_VISOR_RED,UV_VISOR_YELLOW,1000,250,-0.212116,-35.959067,7.627476,inverse
219,UV_VISOR_ORANGE,UV_VISOR_YELLOW,500,1000,-0.218695,34.807086,7.612135,inverse
194,UV_VISOR_AMBER,UV_VISOR_MAGENTA,500,1000,0.269054,27.592295,7.423813,follow
144,UV_VISOR_AMBER,UV_VISOR_ORANGE,500,1000,-0.174637,-42.440317,7.411643,inverse
174,UV_VISOR_AMBER,UV_VISOR_RED,1000,1000,-0.094247,-71.671313,6.754793,inverse
164,UV_VISOR_AMBER,UV_VISOR_RED,250,1000,-0.155261,-42.779812,6.642024,inverse
23,UV_VISOR_YELLOW,UV_VISOR_AMBER,1000,500,0.199862,30.735440,6.142854,follow
309,UV_VISOR_RED,UV_VISOR_YELLOW,100,1000,-0.155319,-38.574656,5.991362,inverse
299,UV_VISOR_ORANGE,UV_VISOR_MAGENTA,1000,1000,-0.077603,-76.258564,5.917860,inverse
143,UV_VISOR_AMBER,UV_VISOR_ORANGE,500,500,-0.233188,-25.292479,5.897902,inverse
499,UV_VISOR_MAGENTA,UV_VISOR_RED,1000,1000,-0.159114,-36.385890,5.789521,inverse
272,UV_VISOR_ORANGE,UV_VISOR_RED,1000,250,0.109806,52.158646,5.727321,follow
69,UV_VISOR_YELLOW,UV_VISOR_RED,500,1000,0.075985,73.005533,5.547291,follow
444,UV_VISOR_MAGENTA,UV_VISOR_AMBER,500,1000,0.131905,41.296251,5.447202,follow
24,UV_VISOR_YELLOW,UV_VISOR_AMBER,1000,1000,0.282986,19.063681,5.394756,follow
64,UV_VISOR_YELLOW,UV_VISOR_RED,250,1000,0.107782,46.732648,5.036920,follow
44,UV_VISOR_YELLOW,UV_VISOR_ORANGE,500,1000,-0.220045,22.213684,4.888001,inverse
316,UV_VISOR_RED,UV_VISOR_YELLOW,500,100,-0.197247,-24.700842,4.872158,inverse
397,UV_VISOR_RED,UV_VISOR_MAGENTA,1000,250,-0.139146,-34.459369,4.794879,inverse
273,UV_VISOR_ORANGE,UV_VISOR_RED,1000,500,0.078283,61.214159,4.792055,follow
172,UV_VISOR_AMBER,UV_VISOR_RED,1000,250,-0.155370,-30.203760,4.692773,inverse
169,UV_VISOR_AMBER,UV_VISOR_RED,500,1000,-0.158753,-29.397104,4.666874,inverse
224,UV_VISOR_ORANGE,UV_VISOR_YELLOW,1000,1000,-0.308267,14.768496,4.552638,inverse

In [8]:
# =========================
# 5) Loose event scan
# Ranks broad families quickly before strict backtest.
# =========================

def event_scan_one_config(cand, window, threshold, horizon, gross):
    q_low = q_from_weights(cand["pos_low_weights"], gross=gross)

    day_rows = []
    all_trades = []

    for day, panel in panels.items():
        mid, bid, ask = panel["mid"], panel["bid"], panel["ask"]
        sig = cand["signal_func"](mid)
        z = rolling_z(sig, window)

        trades = []
        i = window

        while i < len(mid) - horizon:
            zi = z.iloc[i]
            if not np.isfinite(zi):
                i += 1
                continue

            if zi <= -threshold:
                pos = q_low
                side = 1
            elif zi >= threshold:
                pos = -q_low
                side = -1
            else:
                i += 1
                continue

            exit_i = i + horizon
            pnl = exec_pnl(pos, i, exit_i, bid, ask)

            trade = {
                "candidate": cand["candidate"],
                "family": cand["family"],
                "signal_type": cand["signal_type"],
                "note": cand["note"],
                "day": day,
                "window": window,
                "threshold": threshold,
                "horizon": horizon,
                "gross": gross,
                "entry_idx": i,
                "exit_idx": exit_i,
                "entry_ts": mid.index[i],
                "exit_ts": mid.index[exit_i],
                "side": side,
                "entry_z_seen": float(zi),
                "exec_pnl": pnl,
                "q_trade": q_low.tolist(),
                "position": pos.tolist(),
            }
            trades.append(trade)
            all_trades.append(trade)

            # Non-overlapping event scan.
            i = exit_i + 1

        s = summarise_day_rows(trades)
        s.update({
            "candidate": cand["candidate"],
            "family": cand["family"],
            "signal_type": cand["signal_type"],
            "note": cand["note"],
            "day": day,
            "window": window,
            "threshold": threshold,
            "horizon": horizon,
            "gross": gross,
            "q_trade": q_low.tolist(),
            "net_position": float(np.sum(q_low)),
            "gross_position": float(np.sum(np.abs(q_low))),
        })
        day_rows.append(s)

    day_df = pd.DataFrame(day_rows)
    total_pnl = day_df["day_pnl"].sum()
    total_trades = day_df["trade_count"].sum()
    active_days = int((day_df["trade_count"] > 0).sum())
    mean_hit = day_df["hit_rate"].mean()
    min_hit = day_df["hit_rate"].min()
    min_day = day_df["day_pnl"].min()
    max_day = day_df["day_pnl"].max()
    one_day_dep = abs(max_day) / abs(total_pnl) if total_pnl != 0 else np.inf

    summary = {
        "candidate": cand["candidate"],
        "family": cand["family"],
        "signal_type": cand["signal_type"],
        "note": cand["note"],
        "window": window,
        "threshold": threshold,
        "horizon": horizon,
        "gross": gross,
        "q_trade": q_low.tolist(),
        "net_position": float(np.sum(q_low)),
        "gross_position": float(np.sum(np.abs(q_low))),
        "days": len(DAYS),
        "active_days": active_days,
        "total_events": int(total_trades),
        "total_pnl": float(total_pnl),
        "mean_day_pnl": float(day_df["day_pnl"].mean()),
        "min_day_pnl": float(min_day),
        "max_day_pnl": float(max_day),
        "mean_hit_rate": float(mean_hit),
        "min_hit_rate": float(min_hit),
        "pnl_per_event": float(total_pnl / total_trades) if total_trades else np.nan,
        "one_day_dependency": float(one_day_dep),
    }
    summary["robust_pass"] = (
        active_days == len(DAYS)
        and total_trades >= 6
        and min_day > 0
        and mean_hit > 0.55
    )
    summary["robust_score"] = robust_score(total_pnl, min_day, mean_hit, one_day_dep)

    return summary, day_df, all_trades


EVENT_WINDOWS = [500, 1000, 2500, 4000, 5000]
EVENT_THRESHOLDS = [1.25, 1.5, 1.75, 2.0]
EVENT_HORIZONS = [250, 500, 1000, 1500, 2500]
EVENT_GROSS = 60

event_summaries = []
event_day_breakdowns = []
event_trades = []

configs = list(product(range(len(candidates)), EVENT_WINDOWS, EVENT_THRESHOLDS, EVENT_HORIZONS))
t0 = time.time()

for k, (ci, w, th, h) in enumerate(configs, start=1):
    cand = candidates[ci]

    if k == 1 or k % 500 == 0 or k == len(configs):
        print(f"[{time.time()-t0:7.2f}s] event {k}/{len(configs)}: {cand['candidate']}, w={w}, th={th}, h={h}")

    summary, day_df, trades = event_scan_one_config(cand, w, th, h, EVENT_GROSS)
    event_summaries.append(summary)
    event_day_breakdowns.append(day_df)
    event_trades.extend(trades)

event_summary = pd.DataFrame(event_summaries).sort_values("robust_score", ascending=False)
event_day_breakdown = pd.concat(event_day_breakdowns, ignore_index=True)
event_trades_df = pd.DataFrame(event_trades)

event_summary.to_csv(OUTDIR / "uv_visors_event_summary.csv", index=False)
event_summary[event_summary["robust_pass"]].to_csv(OUTDIR / "uv_visors_event_robust_only.csv", index=False)
event_day_breakdown.to_csv(OUTDIR / "uv_visors_event_day_breakdown.csv", index=False)
event_trades_df.to_csv(OUTDIR / "uv_visors_event_trades.csv", index=False)

display(event_summary.head(50))
display(event_summary[event_summary["robust_pass"]].head(50))

[   0.00s] event 1/35000: YELLOW_own_meanrev, w=500, th=1.25, h=250
[   5.77s] event 500/35000: ORANGE_own_meanrev, w=5000, th=2.0, h=2500
[  11.77s] event 1000/35000: MAGENTA_own_trend, w=5000, th=2.0, h=2500
[  17.44s] event 1500/35000: YELLOW_vs_AMBER_ratio_mr, w=5000, th=2.0, h=2500
[  24.12s] event 2000/35000: AMBER_resid_vs_YELLOW_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  29.38s] event 2500/35000: YELLOW_vs_ORANGE_ratio_mr, w=5000, th=2.0, h=2500
[  35.93s] event 3000/35000: ORANGE_resid_vs_YELLOW_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  41.93s] event 3500/35000: YELLOW_vs_RED_ratio_mr, w=5000, th=2.0, h=2500
[  48.83s] event 4000/35000: RED_resid_vs_YELLOW_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  55.37s] event 4500/35000: YELLOW_vs_MAGENTA_ratio_mr, w=5000, th=2.0, h=2500
[  62.29s] event 5000/35000: MAGENTA_resid_vs_YELLOW_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  68.55s] event 5500/35000: AMBER_vs_ORANGE_ratio_mr, w=5000, th=2.0, h=2500
[  75.35s] event 6000/35000: ORANGE_resid_vs_AMBER_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  81.70s] event 6500/35000: AMBER_vs_RED_ratio_mr, w=5000, th=2.0, h=2500
[  88.27s] event 7000/35000: RED_resid_vs_AMBER_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[  94.94s] event 7500/35000: AMBER_vs_MAGENTA_ratio_mr, w=5000, th=2.0, h=2500
[ 101.68s] event 8000/35000: MAGENTA_resid_vs_AMBER_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[ 106.98s] event 8500/35000: ORANGE_vs_RED_ratio_mr, w=5000, th=2.0, h=2500
[ 113.51s] event 9000/35000: RED_resid_vs_ORANGE_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[ 118.71s] event 9500/35000: ORANGE_vs_MAGENTA_ratio_mr, w=5000, th=2.0, h=2500
[ 125.21s] event 10000/35000: MAGENTA_resid_vs_ORANGE_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[ 131.75s] event 10500/35000: RED_vs_MAGENTA_ratio_mr, w=5000, th=2.0, h=2500
[ 139.07s] event 11000/35000: MAGENTA_resid_vs_RED_poly3_mr_DISCOVERY, w=5000, th=2.0, h=2500
[ 143.76s] event 11500/35000: lead_YELLOW_to_AMBER_follow_lag250, w=5000, th=2.0, h=2500
[ 151.48s] event 12000/35000: lead_YELLOW_to_AMBER_inverse_lag1000, w=5000, th=2.0, h=2500
[ 156.14s] event 12500/35000: lead_YELLOW_to_ORANGE_follow_lag250, w=5000, th=2.0, h=2500
[ 164.19s] event 13000/35000: lead_YELLOW_to_ORANGE_inverse_lag1000, w=5000, th=2.0, h=2500
[ 168.86s] event 13500/35000: lead_YELLOW_to_RED_follow_lag250, w=5000, th=2.0, h=2500
[ 176.62s] event 14000/35000: lead_YELLOW_to_RED_inverse_lag1000, w=5000, th=2.0, h=2500
[ 181.27s] event 14500/35000: lead_YELLOW_to_MAGENTA_follow_lag250, w=5000, th=2.0, h=2500
[ 188.88s] event 15000/35000: lead_YELLOW_to_MAGENTA_inverse_lag1000, w=5000, th=2.0, h=2500
[ 193.68s] event 15500/35000: lead_AMBER_to_YELLOW_follow_lag250, w=5000, th=2.0, h=2500
[ 201.25s] event 16000/35000: lead_AMBER_to_YELLOW_inverse_lag1000, w=5000, th=2.0, h=2500
[ 205.96s] event 16500/35000: lead_AMBER_to_ORANGE_follow_lag250, w=5000, th=2.0, h=2500
[ 213.97s] event 17000/35000: lead_AMBER_to_ORANGE_inverse_lag1000, w=5000, th=2.0, h=2500
[ 218.81s] event 17500/35000: lead_AMBER_to_RED_follow_lag250, w=5000, th=2.0, h=2500
[ 226.83s] event 18000/35000: lead_AMBER_to_RED_inverse_lag1000, w=5000, th=2.0, h=2500
[ 231.89s] event 18500/35000: lead_AMBER_to_MAGENTA_follow_lag250, w=5000, th=2.0, h=2500
[ 239.88s] event 19000/35000: lead_AMBER_to_MAGENTA_inverse_lag1000, w=5000, th=2.0, h=2500
[ 244.75s] event 19500/35000: lead_ORANGE_to_YELLOW_follow_lag250, w=5000, th=2.0, h=2500
[ 252.38s] event 20000/35000: lead_ORANGE_to_YELLOW_inverse_lag1000, w=5000, th=2.0, h=2500
[ 257.53s] event 20500/35000: lead_ORANGE_to_AMBER_follow_lag250, w=5000, th=2.0, h=2500
[ 264.54s] event 21000/35000: lead_ORANGE_to_AMBER_inverse_lag1000, w=5000, th=2.0, h=2500
[ 269.45s] event 21500/35000: lead_ORANGE_to_RED_follow_lag250, w=5000, th=2.0, h=2500
[ 277.24s] event 22000/35000: lead_ORANGE_to_RED_inverse_lag1000, w=5000, th=2.0, h=2500
[ 282.03s] event 22500/35000: lead_ORANGE_to_MAGENTA_follow_lag250, w=5000, th=2.0, h=2500
[ 288.95s] event 23000/35000: lead_ORANGE_to_MAGENTA_inverse_lag1000, w=5000, th=2.0, h=2500
[ 293.65s] event 23500/35000: lead_RED_to_YELLOW_follow_lag250, w=5000, th=2.0, h=2500
[ 301.25s] event 24000/35000: lead_RED_to_YELLOW_inverse_lag1000, w=5000, th=2.0, h=2500
[ 305.94s] event 24500/35000: lead_RED_to_AMBER_follow_lag250, w=5000, th=2.0, h=2500
[ 313.56s] event 25000/35000: lead_RED_to_AMBER_inverse_lag1000, w=5000, th=2.0, h=2500
[ 318.26s] event 25500/35000: lead_RED_to_ORANGE_follow_lag250, w=5000, th=2.0, h=2500
[ 325.87s] event 26000/35000: lead_RED_to_ORANGE_inverse_lag1000, w=5000, th=2.0, h=2500
[ 331.23s] event 26500/35000: lead_RED_to_MAGENTA_follow_lag250, w=5000, th=2.0, h=2500
[ 338.91s] event 27000/35000: lead_RED_to_MAGENTA_inverse_lag1000, w=5000, th=2.0, h=2500
[ 343.72s] event 27500/35000: lead_MAGENTA_to_YELLOW_follow_lag250, w=5000, th=2.0, h=2500
[ 351.69s] event 28000/35000: lead_MAGENTA_to_YELLOW_inverse_lag1000, w=5000, th=2.0, h=2500
[ 356.47s] event 28500/35000: lead_MAGENTA_to_AMBER_follow_lag250, w=5000, th=2.0, h=2500
[ 364.17s] event 29000/35000: lead_MAGENTA_to_AMBER_inverse_lag1000, w=5000, th=2.0, h=2500
[ 368.95s] event 29500/35000: lead_MAGENTA_to_ORANGE_follow_lag250, w=5000, th=2.0, h=2500
[ 376.67s] event 30000/35000: lead_MAGENTA_to_ORANGE_inverse_lag1000, w=5000, th=2.0, h=2500
[ 381.45s] event 30500/35000: lead_MAGENTA_to_RED_follow_lag250, w=5000, th=2.0, h=2500
[ 389.15s] event 31000/35000: lead_MAGENTA_to_RED_inverse_lag1000, w=5000, th=2.0, h=2500
[ 396.29s] event 31500/35000: basket_warm_vs_cool_mr, w=5000, th=2.0, h=2500
[ 402.41s] event 32000/35000: basket_red_extreme_vs_rest_trend, w=5000, th=2.0, h=2500
[ 408.27s] event 32500/35000: basket_yellow_amber_vs_red_magenta_mr, w=5000, th=2.0, h=2500
[ 414.19s] event 33000/35000: adjacent_RED_vs_MAGENTA_spread_mr, w=5000, th=2.0, h=2500
[ 419.88s] event 33500/35000: mix_RED_blend_YELLOW_MAGENTA_25_75_mr, w=5000, th=2.0, h=2500
[ 425.64s] event 34000/35000: mix_AMBER_blend_YELLOW_RED_50_50_mr, w=5000, th=2.0, h=2500
[ 430.94s] event 34500/35000: mix_ORANGE_blend_YELLOW_MAGENTA_75_25_mr, w=5000, th=2.0, h=2500
[ 436.69s] event 35000/35000: curvature_AMBER_RED_MAGENTA_mr, w=5000, th=2.0, h=2500

,candidate,family,signal_type,note,window,threshold,horizon,gross,q_trade,net_position,...,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,mean_hit_rate,min_hit_rate,pnl_per_event,one_day_dependency,robust_pass,robust_score
16008,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,310800.0,103600.0,64080.0,145500.0,0.833333,0.666667,17266.666667,0.468147,True,443126.666667
17924,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,2500,60,"[0, 0, 0, 60, 0]",60.0,...,260100.0,86700.0,76020.0,104100.0,0.888889,0.666667,28900.000000,0.400231,True,416584.444444
15333,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,1000,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,252780.0,84260.0,75900.0,93780.0,0.733333,0.600000,16852.000000,0.370995,True,408246.666667
19231,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,259140.0,86380.0,70920.0,100080.0,0.725275,0.692308,6478.500000,0.386201,True,404606.373626
16203,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,267540.0,89180.0,65520.0,132660.0,0.777778,0.666667,14863.333333,0.495851,True,402468.888889
17909,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,2500,60,"[0, 0, 0, 60, 0]",60.0,...,254040.0,84680.0,68760.0,107160.0,0.888889,0.666667,28226.666667,0.421823,True,396004.444444
18332,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,1.75,1000,60,"[0, 0, 0, 0, 60]",60.0,...,250020.0,83340.0,71100.0,107220.0,0.619048,0.571429,11905.714286,0.428846,True,395315.238095
13802,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,305040.0,101680.0,42300.0,132360.0,0.750000,0.625000,12710.000000,0.433910,True,393390.000000
23518,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,257520.0,85840.0,63000.0,125220.0,0.800000,0.800000,17168.000000,0.486253,True,387520.000000
23736,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1000,2.00,500,60,"[60, 0, 0, 0, 0]",60.0,...,231180.0,77060.0,67680.0,84000.0,0.716667,0.700000,7224.375000,0.363353,True,370123.333333
16233,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,1000,1.75,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,256380.0,85460.0,53640.0,129900.0,0.866667,0.800000,17092.000000,0.506670,True,367138.333333
27206,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,232800.0,77600.0,64500.0,84960.0,0.637908,0.600000,4953.191489,0.364948,True,364989.542484
13807,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.50,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,286200.0,95400.0,36000.0,131640.0,0.744048,0.625000,12443.478261,0.459958,True,361920.238095
15348,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,1.50,1500,60,"[60, 0, 0, 0, 0]",60.0,...,230520.0,76840.0,62280.0,95520.0,0.750000,0.750000,19210.000000,0.414368,True,358830.000000
23918,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,233340.0,77780.0,57600.0,101460.0,0.783333,0.750000,16667.142857,0.434816,True,352456.666667
14143,lead_YELLOW_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows YELLOW return over l...,2500,1.25,1500,60,"[0, 0, 0, 0, 60]",60.0,...,212220.0,70740.0,64920.0,75120.0,0.833333,0.750000,17685.000000,0.353972,True,346226.666667
18137,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,1000,60,"[0, 0, 0, 0, 60]",60.0,...,235260.0,78420.0,51840.0,95280.0,0.684524,0.625000,10693.636364,0.404999,True,342362.619048
19422,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 250,1000,1.25,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,228720.0,76240.0,54300.0,103980.0,0.738095,0.625000,9944.347826,0.454617,True,341010.476190
23523,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.25,1500,60,"[60, 0, 0, 0, 0]",60.0,...,244260.0,81420.0,45720.0,112260.0,0.800000,0.600000,16284.000000,0.459592,True,339700.000000
18116,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,2.00,500,60,"[0, 0, 0, 0, 60]",60.0,...,239580.0,79860.0,51300.0,134400.0,0.733333,0.466667,5324.000000,0.560982,True,338541.666667
12001,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.25,500,60,"[0, 0, -60, 0, 0]",-60.0,...,259680.0,86560.0,38040.0,132900.0,0.617647,0.500000,4993.846154,0.511784,True,337318.235294
23920,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,250,60,"[60, 0, 0, 0, 0]",60.0,...,239820.0,79940.0,48960.0,127380.0,0.584877,0.458333,3074.615385,0.531148,True,336929.382716
19226,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.50,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,245040.0,81680.0,42900.0,105600.0,0.634921,0.571429,5569.090909,0.430950,True,334014.603175
27724,lead_MAGENTA_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,1000,1.25,2500,60,"[60, 0, 0, 0, 0]",60.0,...,230220.0,76740.0,49200.0,106920.0,0.888889,0.666667,25580.000000,0.464425,True,333064.444444
23921,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,500,60,"[60, 0, 0, 0, 0]",60.0,...,253140.0,84380.0,43320.0,151320.0,0.595238,0.500000,6328.500000,0.597772,True,330381.190476
12007,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,1000,60,"[0, 0, -60, 0, 0]",-60.0,...,216540.0,72180.0,54900.0,93120.0,0.708333,0.625000,9022.500000,0.430036,True,329881.666667
23906,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.50,500,60,"[60, 0, 0, 0, 0]",60.0,...,200760.0,66920.0,60060.0,75480.0,0.650794,0.571429,4668.837209,0.375971,True,324133.968254
23913,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,222300.0,74100.0,48480.0,96420.0,0.783333,0.750000,15878.571429,0.433738,True,323176.666667
17934,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.75,2500,60,"[0, 0, 0, 60, 0]",60.0,...,207540.0,69180.0,55620.0,85920.0,0.777778,0.666667,25942.500000,0.413992,True,322668.888889
17929,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.50,2500,60,"[0, 0, 0, 60, 0]",60.0,...,214140.0,71380.0,50400.0,83880.0,0.777778,0.666667,23793.333333,0.391706,True,318828.888889
15353,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,210180.0,70060.0,51660.0,96540.0,0.750000,0.750000,17515.000000,0.459321,True,317250.000000
12605,lead_YELLOW_to_ORANGE_follow_lag500,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 500,500,1.50,250,60,"[0, 0, -60, 0, 0]",-60.0,...,192960.0,64320.0,60000.0,67680.0,0.570197,0.551724,2243.720930,0.350746,True,315810.985222
23901,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.25,500,60,"[60, 0, 0, 0, 0]",60.0,...,246720.0,82240.0,32040.0,116700.0,0.600000,0.466667,5482.666667,0.473006,True,313800.000000
18736,lead_AMBER_to_MAGENTA_inverse_lag500,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,500,60,"[0, 0, 0, 0, 60]",60.0,...,197100.0,65700.0,55800.0,78540.0,0.679714,0.625000,7039.285714,0.398478,True,312098.569024
21222,lead_ORANGE_to_RED_follow_lag100,lead_lag,leader_return_follow,RED follows ORANGE return over lag 100,1000,1.25,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,237360.0,79120.0,34140.0,105000.0,0.625000,0.500000,9890.000000,0.442366,True,308765.000000
18802,lead_AMBER_to_MAGENTA_follow_lag1000,lead_lag,leader_return_follow,MAGENTA follows AMBER return over lag 1000,500,1.25,1000,60,"[0, 0, 0, 0, -60]",-60.0,...,190920.0,63640.0,56040.0,74400.0,0.750000,0.625000,7955.000000,0.389692,True,306750.000000
15358,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,198180.0,66060.0,52440.0,78420.0,0.722222,0.666667,18016.363636,0.395701,True,306671.111111
21063,lead_ORANGE_to_RED_follow_lag50,lead_lag,leader_return_follow,RED follows ORANGE return over lag 50,4000,1.25,1500,60,"[0, 0, 0, -60, 0]",-60.0,...,183120.0,61040.0,58800.0,64140.0,0.888889,0.666667,20346.666667,0.350262,True,305164.444444
18337,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,1000,60,"[0, 0, 0, 0, 60]",60.0,...,199560.0,66520.0,49560.0,88620.0,0.730159,0.666667,10503.157895,0.444077,True,302330.793651
23323,lead_RED_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 100,1000,1.25,1500,60,"[60, 0, 0, 0, 0]",60.0,...,205620.0,68540.0,45360.0,85740.0,0.800000,0.600000,13708.000000,0.416983,True,300340.000000
19232,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,204660.0,68220.0,45840.0,101700.0,0.619048,0.571429,9745.714286,0.496922,True,299435.238095
18105,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.50,250,60,"[0, 0, 0, 0, 60]",60.0,...,229080.0,76360.0,32640.0,111720.0,0.638889,0.566667,2490.000000,0.487690,True,297554.444444
30017,lead_MAGENTA_to_RED_follow_lag50,lead_lag,leader_return_follow,RED follows MAGENTA return over lag 50,500,2.00,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,199500.0,66500.0,46740.0,83700.0,0.750000,0.750000,8312.500000,0.419549,True,296730.000000
19037,lead_ORANGE_to_YELLOW_follow_lag50,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 50,1000,2.00,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,197820.0,65940.0,47460.0,85020.0,0.761905,0.714286,9420.000000,0.429785,True,296549.523810
12006,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,500,60,"[0, 0, -60, 0, 0]",-60.0,...,193620.0,64540.0,49860.0,90360.0,0.569853,0.500000,3951.428571,0.466687,True,296189.264706
13427,lead_YELLOW_to_RED_follow_lag250,lead_lag,leader_return_follow,RED follows YELLOW return over lag 250,1000,1.50,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,276360.0,92120.0,9300.0,148260.0,0.736111,0.500000,12561.818182,0.536474,True,293600.555556
18111,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.75,500,60,"[0, 0, 0, 0, 60]",60.0,...,205680.0,68560.0,39660.0,85200.0,0.643464,0.533333,4285.000000,0.414236,True,288217.320261
16352,lead_AMBER_to_ORANGE_inverse_lag100,lead_lag,leader_return_inverse,ORANGE inversely follows AMBER return over lag...,2500,1.75,1000,60,"[0, 0, 60, 0, 0]",60.0,...,210480.0,70160.0,37020.0,106740.0,0.777778,0.666667,11693.333333,0.507127,True,287658.888889
15928,lead_AMBER_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,1000,1.50,1500,60,"[60, 0, 0, 0, 0]",60.0,...,211740.0,70580.0,36480.0,88380.0,0.500000,0.250000,17645.000000,0.417399,False,287200.000000
27302,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,1.25,1000,60,"[60, 0, 0, 0, 0]",60.0,...,183120.0,61040.0,49440.0,82680.0,0.689815,0.625000,7043.076923,0.451507,True,285449.074074

,candidate,family,signal_type,note,window,threshold,horizon,gross,q_trade,net_position,...,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,mean_hit_rate,min_hit_rate,pnl_per_event,one_day_dependency,robust_pass,robust_score
16008,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,310800.0,103600.0,64080.0,145500.0,0.833333,0.666667,17266.666667,0.468147,True,443126.666667
17924,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,2500,60,"[0, 0, 0, 60, 0]",60.0,...,260100.0,86700.0,76020.0,104100.0,0.888889,0.666667,28900.000000,0.400231,True,416584.444444
15333,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,1000,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,252780.0,84260.0,75900.0,93780.0,0.733333,0.600000,16852.000000,0.370995,True,408246.666667
19231,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,259140.0,86380.0,70920.0,100080.0,0.725275,0.692308,6478.500000,0.386201,True,404606.373626
16203,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,267540.0,89180.0,65520.0,132660.0,0.777778,0.666667,14863.333333,0.495851,True,402468.888889
17909,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,2500,60,"[0, 0, 0, 60, 0]",60.0,...,254040.0,84680.0,68760.0,107160.0,0.888889,0.666667,28226.666667,0.421823,True,396004.444444
18332,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,1.75,1000,60,"[0, 0, 0, 0, 60]",60.0,...,250020.0,83340.0,71100.0,107220.0,0.619048,0.571429,11905.714286,0.428846,True,395315.238095
13802,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,305040.0,101680.0,42300.0,132360.0,0.750000,0.625000,12710.000000,0.433910,True,393390.000000
23518,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,257520.0,85840.0,63000.0,125220.0,0.800000,0.800000,17168.000000,0.486253,True,387520.000000
23736,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1000,2.00,500,60,"[60, 0, 0, 0, 0]",60.0,...,231180.0,77060.0,67680.0,84000.0,0.716667,0.700000,7224.375000,0.363353,True,370123.333333
16233,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,1000,1.75,1500,60,"[0, 0, -60, 0, 0]",-60.0,...,256380.0,85460.0,53640.0,129900.0,0.866667,0.800000,17092.000000,0.506670,True,367138.333333
27206,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,232800.0,77600.0,64500.0,84960.0,0.637908,0.600000,4953.191489,0.364948,True,364989.542484
13807,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.50,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,286200.0,95400.0,36000.0,131640.0,0.744048,0.625000,12443.478261,0.459958,True,361920.238095
15348,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,1.50,1500,60,"[60, 0, 0, 0, 0]",60.0,...,230520.0,76840.0,62280.0,95520.0,0.750000,0.750000,19210.000000,0.414368,True,358830.000000
23918,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,233340.0,77780.0,57600.0,101460.0,0.783333,0.750000,16667.142857,0.434816,True,352456.666667
14143,lead_YELLOW_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows YELLOW return over l...,2500,1.25,1500,60,"[0, 0, 0, 0, 60]",60.0,...,212220.0,70740.0,64920.0,75120.0,0.833333,0.750000,17685.000000,0.353972,True,346226.666667
18137,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,1000,60,"[0, 0, 0, 0, 60]",60.0,...,235260.0,78420.0,51840.0,95280.0,0.684524,0.625000,10693.636364,0.404999,True,342362.619048
19422,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 250,1000,1.25,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,228720.0,76240.0,54300.0,103980.0,0.738095,0.625000,9944.347826,0.454617,True,341010.476190
23523,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.25,1500,60,"[60, 0, 0, 0, 0]",60.0,...,244260.0,81420.0,45720.0,112260.0,0.800000,0.600000,16284.000000,0.459592,True,339700.000000
18116,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,2.00,500,60,"[0, 0, 0, 0, 60]",60.0,...,239580.0,79860.0,51300.0,134400.0,0.733333,0.466667,5324.000000,0.560982,True,338541.666667
12001,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.25,500,60,"[0, 0, -60, 0, 0]",-60.0,...,259680.0,86560.0,38040.0,132900.0,0.617647,0.500000,4993.846154,0.511784,True,337318.235294
23920,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,250,60,"[60, 0, 0, 0, 0]",60.0,...,239820.0,79940.0,48960.0,127380.0,0.584877,0.458333,3074.615385,0.531148,True,336929.382716
19226,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.50,500,60,"[-60, 0, 0, 0, 0]",-60.0,...,245040.0,81680.0,42900.0,105600.0,0.634921,0.571429,5569.090909,0.430950,True,334014.603175
27724,lead_MAGENTA_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,1000,1.25,2500,60,"[60, 0, 0, 0, 0]",60.0,...,230220.0,76740.0,49200.0,106920.0,0.888889,0.666667,25580.000000,0.464425,True,333064.444444
23921,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,500,60,"[60, 0, 0, 0, 0]",60.0,...,253140.0,84380.0,43320.0,151320.0,0.595238,0.500000,6328.500000,0.597772,True,330381.190476
12007,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,1000,60,"[0, 0, -60, 0, 0]",-60.0,...,216540.0,72180.0,54900.0,93120.0,0.708333,0.625000,9022.500000,0.430036,True,329881.666667
23906,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.50,500,60,"[60, 0, 0, 0, 0]",60.0,...,200760.0,66920.0,60060.0,75480.0,0.650794,0.571429,4668.837209,0.375971,True,324133.968254
23913,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,222300.0,74100.0,48480.0,96420.0,0.783333,0.750000,15878.571429,0.433738,True,323176.666667
17934,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.75,2500,60,"[0, 0, 0, 60, 0]",60.0,...,207540.0,69180.0,55620.0,85920.0,0.777778,0.666667,25942.500000,0.413992,True,322668.888889
17929,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.50,2500,60,"[0, 0, 0, 60, 0]",60.0,...,214140.0,71380.0,50400.0,83880.0,0.777778,0.666667,23793.333333,0.391706,True,318828.888889
15353,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,1.75,1500,60,"[60, 0, 0, 0, 0]",60.0,...,210180.0,70060.0,51660.0,96540.0,0.750000,0.750000,17515.000000,0.459321,True,317250.000000
12605,lead_YELLOW_to_ORANGE_follow_lag500,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 500,500,1.50,250,60,"[0, 0, -60, 0, 0]",-60.0,...,192960.0,64320.0,60000.0,67680.0,0.570197,0.551724,2243.720930,0.350746,True,315810.985222
23901,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.25,500,60,"[60, 0, 0, 0, 0]",60.0,...,246720.0,82240.0,32040.0,116700.0,0.600000,0.466667,5482.666667,0.473006,True,313800.000000
18736,lead_AMBER_to_MAGENTA_inverse_lag500,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,500,60,"[0, 0, 0, 0, 60]",60.0,...,197100.0,65700.0,55800.0,78540.0,0.679714,0.625000,7039.285714,0.398478,True,312098.569024
21222,lead_ORANGE_to_RED_follow_lag100,lead_lag,leader_return_follow,RED follows ORANGE return over lag 100,1000,1.25,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,237360.0,79120.0,34140.0,105000.0,0.625000,0.500000,9890.000000,0.442366,True,308765.000000
18802,lead_AMBER_to_MAGENTA_follow_lag1000,lead_lag,leader_return_follow,MAGENTA follows AMBER return over lag 1000,500,1.25,1000,60,"[0, 0, 0, 0, -60]",-60.0,...,190920.0,63640.0,56040.0,74400.0,0.750000,0.625000,7955.000000,0.389692,True,306750.000000
15358,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,2500,2.00,1500,60,"[60, 0, 0, 0, 0]",60.0,...,198180.0,66060.0,52440.0,78420.0,0.722222,0.666667,18016.363636,0.395701,True,306671.111111
21063,lead_ORANGE_to_RED_follow_lag50,lead_lag,leader_return_follow,RED follows ORANGE return over lag 50,4000,1.25,1500,60,"[0, 0, 0, -60, 0]",-60.0,...,183120.0,61040.0,58800.0,64140.0,0.888889,0.666667,20346.666667,0.350262,True,305164.444444
18337,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,1000,60,"[0, 0, 0, 0, 60]",60.0,...,199560.0,66520.0,49560.0,88620.0,0.730159,0.666667,10503.157895,0.444077,True,302330.793651
23323,lead_RED_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 100,1000,1.25,1500,60,"[60, 0, 0, 0, 0]",60.0,...,205620.0,68540.0,45360.0,85740.0,0.800000,0.600000,13708.000000,0.416983,True,300340.000000
19232,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,204660.0,68220.0,45840.0,101700.0,0.619048,0.571429,9745.714286,0.496922,True,299435.238095
18105,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.50,250,60,"[0, 0, 0, 0, 60]",60.0,...,229080.0,76360.0,32640.0,111720.0,0.638889,0.566667,2490.000000,0.487690,True,297554.444444
30017,lead_MAGENTA_to_RED_follow_lag50,lead_lag,leader_return_follow,RED follows MAGENTA return over lag 50,500,2.00,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,199500.0,66500.0,46740.0,83700.0,0.750000,0.750000,8312.500000,0.419549,True,296730.000000
19037,lead_ORANGE_to_YELLOW_follow_lag50,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 50,1000,2.00,1000,60,"[-60, 0, 0, 0, 0]",-60.0,...,197820.0,65940.0,47460.0,85020.0,0.761905,0.714286,9420.000000,0.429785,True,296549.523810
12006,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,500,60,"[0, 0, -60, 0, 0]",-60.0,...,193620.0,64540.0,49860.0,90360.0,0.569853,0.500000,3951.428571,0.466687,True,296189.264706
13427,lead_YELLOW_to_RED_follow_lag250,lead_lag,leader_return_follow,RED follows YELLOW return over lag 250,1000,1.50,1000,60,"[0, 0, 0, -60, 0]",-60.0,...,276360.0,92120.0,9300.0,148260.0,0.736111,0.500000,12561.818182,0.536474,True,293600.555556
18111,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.75,500,60,"[0, 0, 0, 0, 60]",60.0,...,205680.0,68560.0,39660.0,85200.0,0.643464,0.533333,4285.000000,0.414236,True,288217.320261
16352,lead_AMBER_to_ORANGE_inverse_lag100,lead_lag,leader_return_inverse,ORANGE inversely follows AMBER return over lag...,2500,1.75,1000,60,"[0, 0, 60, 0, 0]",60.0,...,210480.0,70160.0,37020.0,106740.0,0.777778,0.666667,11693.333333,0.507127,True,287658.888889
27302,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,1.25,1000,60,"[60, 0, 0, 0, 0]",60.0,...,183120.0,61040.0,49440.0,82680.0,0.689815,0.625000,7043.076923,0.451507,True,285449.074074
2538,YELLOW_vs_ORANGE_ratio_trend,pairwise,ratio,YELLOW - ORANGE trend,1000,2.00,1500,60,"[-30, 0, 30, 0, 0]",0.0,...,191310.0,63770.0,44880.0,90180.0,0.850000,0.750000,13665.000000,0.471382,True,285320.000000

In [9]:
# =========================
# 6) Strict-position backtest on top event candidates
# This is the important validation stage.
# =========================

def strict_backtest_one_config(cand, window, entry_z, exit_z, max_hold, gross):
    q_low = q_from_weights(cand["pos_low_weights"], gross=gross)

    day_rows = []
    all_trades = []

    for day, panel in panels.items():
        mid, bid, ask = panel["mid"], panel["bid"], panel["ask"]
        sig = cand["signal_func"](mid)
        z = rolling_z(sig, window)

        trades = []
        i = window

        while i < len(mid) - 1:
            zi = z.iloc[i]
            if not np.isfinite(zi):
                i += 1
                continue

            if zi <= -entry_z:
                pos = q_low
                side = 1
            elif zi >= entry_z:
                pos = -q_low
                side = -1
            else:
                i += 1
                continue

            entry_i = i
            j = i + 1

            while j < len(mid) - 1:
                zj = z.iloc[j]
                hold = j - entry_i

                exit_hit = np.isfinite(zj) and abs(zj) <= exit_z
                hold_hit = hold >= max_hold
                end_hit = j >= len(mid) - 2

                if exit_hit or hold_hit or end_hit:
                    break
                j += 1

            exit_i = j
            pnl = exec_pnl(pos, entry_i, exit_i, bid, ask)

            trade = {
                "candidate": cand["candidate"],
                "family": cand["family"],
                "signal_type": cand["signal_type"],
                "note": cand["note"],
                "day": day,
                "window": window,
                "entry_z": entry_z,
                "exit_z": exit_z,
                "max_hold": max_hold,
                "gross": gross,
                "entry_idx": entry_i,
                "exit_idx": exit_i,
                "entry_ts": mid.index[entry_i],
                "exit_ts": mid.index[exit_i],
                "side": side,
                "entry_z_seen": float(z.iloc[entry_i]),
                "exit_z_seen": float(z.iloc[exit_i]) if np.isfinite(z.iloc[exit_i]) else np.nan,
                "hold": int(exit_i - entry_i),
                "exec_pnl": pnl,
                "q_trade": q_low.tolist(),
                "position": pos.tolist(),
            }
            trades.append(trade)
            all_trades.append(trade)

            # One strict open position at a time.
            i = exit_i + 1

        s = summarise_day_rows(trades)
        s.update({
            "candidate": cand["candidate"],
            "family": cand["family"],
            "signal_type": cand["signal_type"],
            "note": cand["note"],
            "day": day,
            "window": window,
            "entry_z": entry_z,
            "exit_z": exit_z,
            "max_hold": max_hold,
            "gross": gross,
            "q_trade": q_low.tolist(),
            "net_position": float(np.sum(q_low)),
            "gross_position": float(np.sum(np.abs(q_low))),
        })
        day_rows.append(s)

    day_df = pd.DataFrame(day_rows)
    total_pnl = day_df["day_pnl"].sum()
    total_trades = day_df["trade_count"].sum()
    active_days = int((day_df["trade_count"] > 0).sum())
    mean_hit = day_df["hit_rate"].mean()
    min_hit = day_df["hit_rate"].min()
    min_day = day_df["day_pnl"].min()
    max_day = day_df["day_pnl"].max()
    one_day_dep = abs(max_day) / abs(total_pnl) if total_pnl != 0 else np.inf

    summary = {
        "candidate": cand["candidate"],
        "family": cand["family"],
        "signal_type": cand["signal_type"],
        "note": cand["note"],
        "window": window,
        "entry_z": entry_z,
        "exit_z": exit_z,
        "max_hold": max_hold,
        "gross": gross,
        "q_trade": q_low.tolist(),
        "net_position": float(np.sum(q_low)),
        "gross_position": float(np.sum(np.abs(q_low))),
        "days": len(DAYS),
        "active_days": active_days,
        "total_trades": int(total_trades),
        "total_pnl": float(total_pnl),
        "mean_day_pnl": float(day_df["day_pnl"].mean()),
        "min_day_pnl": float(min_day),
        "max_day_pnl": float(max_day),
        "mean_hit_rate": float(mean_hit),
        "min_hit_rate": float(min_hit),
        "pnl_per_trade": float(total_pnl / total_trades) if total_trades else np.nan,
        "one_day_dependency": float(one_day_dep),
    }

    summary["robust_pass"] = (
        active_days == len(DAYS)
        and total_trades >= 5
        and min_day > 0
        and mean_hit > 0.55
    )
    summary["robust_score"] = robust_score(total_pnl, min_day, mean_hit, one_day_dep)

    return summary, day_df, all_trades


# Select candidates for strict testing:
# 1) top robust event candidates
# 2) top overall event candidates
# 3) manually force in suspected RED lead-lag and colour-mixing candidates
top_event_names = list(event_summary.head(80)["candidate"].unique())
top_robust_names = list(event_summary[event_summary["robust_pass"]].head(80)["candidate"].unique())

manual_names = [
    name for name in [c["candidate"] for c in candidates]
    if (
        "lead_RED_to_YELLOW" in name
        or "lead_RED_to_ORANGE" in name
        or "lead_RED_to_AMBER" in name
        or "lead_MAGENTA_to_RED" in name
        or "mix_" in name
        or "curvature_" in name
        or "red_extreme" in name.lower()
        or "spectrum_gradient" in name
    )
]

strict_names = list(dict.fromkeys(top_robust_names + top_event_names + manual_names))
strict_name_set = set(strict_names)
strict_candidates = [c for c in candidates if c["candidate"] in strict_name_set]

print("Strict candidates:", len(strict_candidates))


STRICT_WINDOWS = [1000, 2500, 4000, 5000]
STRICT_ENTRY_ZS = [1.25, 1.5, 1.75, 2.0]
STRICT_EXIT_ZS = [0.0, 0.25, 0.5]
STRICT_MAX_HOLDS = [1000, 1500, 2500]
STRICT_GROSSES = [50, 60, 72]

strict_configs = list(product(
    range(len(strict_candidates)),
    STRICT_WINDOWS,
    STRICT_ENTRY_ZS,
    STRICT_EXIT_ZS,
    STRICT_MAX_HOLDS,
    STRICT_GROSSES,
))

strict_summaries = []
strict_day_breakdowns = []
strict_trades = []

t0 = time.time()

for k, (ci, w, entry, exit_, hold, gross) in enumerate(strict_configs, start=1):
    cand = strict_candidates[ci]

    if k == 1 or k % 250 == 0 or k == len(strict_configs):
        print(
            f"[{time.time()-t0:7.2f}s] strict {k}/{len(strict_configs)}: "
            f"{cand['candidate']}, w={w}, entry={entry}, exit={exit_}, hold={hold}, gross={gross}"
        )

    summary, day_df, trades = strict_backtest_one_config(
        cand=cand,
        window=w,
        entry_z=entry,
        exit_z=exit_,
        max_hold=hold,
        gross=gross,
    )

    strict_summaries.append(summary)
    strict_day_breakdowns.append(day_df)
    strict_trades.extend(trades)

strict_summary = pd.DataFrame(strict_summaries).sort_values("robust_score", ascending=False)
strict_day_breakdown = pd.concat(strict_day_breakdowns, ignore_index=True)
strict_trades_df = pd.DataFrame(strict_trades)

strict_summary.to_csv(OUTDIR / "uv_visors_strict_summary.csv", index=False)
strict_summary[strict_summary["robust_pass"]].to_csv(OUTDIR / "uv_visors_strict_robust_only.csv", index=False)
strict_day_breakdown.to_csv(OUTDIR / "uv_visors_strict_day_breakdown.csv", index=False)
strict_trades_df.to_csv(OUTDIR / "uv_visors_strict_trades.csv", index=False)

display(strict_summary.head(50))
display(strict_summary[strict_summary["robust_pass"]].head(50))

Strict candidates: 100
[   0.00s] strict 1/43200: YELLOW_vs_ORANGE_spread_trend, w=1000, entry=1.25, exit=0.0, hold=1000, gross=50
[  13.21s] strict 250/43200: YELLOW_vs_ORANGE_spread_trend, w=4000, entry=1.5, exit=0.0, hold=2500, gross=50
[  23.75s] strict 500/43200: YELLOW_vs_ORANGE_logratio_trend, w=1000, entry=1.75, exit=0.25, hold=1500, gross=60
[  35.31s] strict 750/43200: YELLOW_vs_ORANGE_logratio_trend, w=4000, entry=2.0, exit=0.5, hold=1000, gross=72
[  46.72s] strict 1000/43200: YELLOW_vs_ORANGE_ratio_trend, w=2500, entry=1.5, exit=0.0, hold=1000, gross=50
[  56.87s] strict 1250/43200: YELLOW_vs_ORANGE_ratio_trend, w=5000, entry=1.75, exit=0.0, hold=2500, gross=60

KeyboardInterrupt:

In [11]:
# =========================
# 6-FAST) Optimised strict-position backtest for UV VISORS
# Replacement for slow cell #6
# Uses event_summary + candidates + panels from previous cells
# =========================

import numpy as np
import pandas as pd
from pathlib import Path
import time
from itertools import product

FAST_OUTDIR = Path("analysis_outputs/uv_visors_fast_strict")
FAST_OUTDIR.mkdir(parents=True, exist_ok=True)

# Load from disk if needed
if "event_summary" not in globals():
    event_summary = pd.read_csv("analysis_outputs/uv_visors/uv_visors_event_summary.csv")

if "leadlag_diag" not in globals():
    try:
        leadlag_diag = pd.read_csv("analysis_outputs/uv_visors/uv_visors_leadlag_diagnostics.csv")
    except FileNotFoundError:
        leadlag_diag = None

candidate_by_name = {c["candidate"]: c for c in candidates}

# Do not allow leaky static polynomial discovery candidates into final strict test.
EXCLUDE_DISCOVERY = True

ev = event_summary.copy()
if EXCLUDE_DISCOVERY:
    ev = ev[~ev["candidate"].str.contains("DISCOVERY", na=False)].copy()

ev = ev.sort_values("robust_score", ascending=False).reset_index(drop=True)

# Robust pass may load as bool or string
if ev["robust_pass"].dtype == object:
    ev["robust_pass_bool"] = ev["robust_pass"].astype(str).str.lower().eq("true")
else:
    ev["robust_pass_bool"] = ev["robust_pass"].astype(bool)


# -------------------------
# Candidate selection
# -------------------------

selected_names = []

def add_names(names):
    for n in names:
        if n in candidate_by_name and n not in selected_names:
            selected_names.append(n)

# 1) top robust and top overall event candidates
add_names(ev[ev["robust_pass_bool"]].head(80)["candidate"].tolist())
add_names(ev.head(80)["candidate"].tolist())

# 2) family rescue: keep mixing/curvature/pairwise alive even if lead-lag dominates
for fam, n in [
    ("lead_lag", 60),
    ("pairwise", 25),
    ("colour_mixing", 20),
    ("colour_curvature", 10),
    ("colour_basket", 15),
    ("single", 10),
]:
    add_names(ev[ev["family"].eq(fam)].head(n)["candidate"].tolist())

# 3) lead-lag diagnostics rescue: map top diagnostic rows to exact candidate names
if leadlag_diag is not None:
    for _, r in leadlag_diag.head(40).iterrows():
        leader = COLOR_SHORT[r["leader"]]
        follower = COLOR_SHORT[r["follower"]]
        lag = int(r["lag"])
        mode = str(r["suggested_mode"])
        add_names([f"lead_{leader}_to_{follower}_{mode}_lag{lag}"])

# Limit for fast pass. Increase to 150 if still quick.
MAX_CANDIDATES_FAST = 120
selected_names = selected_names[:MAX_CANDIDATES_FAST]
selected_candidates = [candidate_by_name[n] for n in selected_names]

print("Selected strict candidates:", len(selected_candidates))
print(pd.Series([c["family"] for c in selected_candidates]).value_counts())


# -------------------------
# Fast caches
# -------------------------

panel_np = {}
for day, panel in panels.items():
    mid = panel["mid"]
    panel_np[day] = {
        "mid": mid,
        "bid_arr": panel["bid"].values.astype(float),
        "ask_arr": panel["ask"].values.astype(float),
        "ts_arr": mid.index.to_numpy(),
        "n": len(mid),
    }

def rolling_z_np(values, window):
    s = pd.Series(values).replace([np.inf, -np.inf], np.nan)
    mu = s.rolling(window, min_periods=window).mean()
    sd = s.rolling(window, min_periods=window).std(ddof=0)
    z = ((s - mu) / sd).replace([np.inf, -np.inf], np.nan)
    return z.to_numpy(dtype=float)

signal_cache = {}
z_cache = {}

# We only use windows that appear in the generated config list below,
# but define broad enough here.
STRICT_WINDOWS_FAST = [500, 1000, 1500, 2500, 4000, 5000]

print("Precomputing signals and z-scores...")
t0 = time.time()

for ci, cand in enumerate(selected_candidates, start=1):
    cname = cand["candidate"]

    if ci == 1 or ci % 20 == 0 or ci == len(selected_candidates):
        print(f"[{time.time()-t0:7.2f}s] candidate {ci}/{len(selected_candidates)}: {cname}")

    for day, pnp in panel_np.items():
        mid = pnp["mid"]
        sig = cand["signal_func"](mid)
        sig_arr = pd.Series(sig).to_numpy(dtype=float)
        signal_cache[(cname, day)] = sig_arr

        for w in STRICT_WINDOWS_FAST:
            z_cache[(cname, day, w)] = rolling_z_np(sig_arr, w)

print(f"Cache done in {time.time()-t0:.2f}s")


# -------------------------
# Fast strict execution
# -------------------------

def exec_pnl_np(pos, entry_i, exit_i, bid_arr, ask_arr):
    pos = np.asarray(pos, dtype=float)

    entry_bid = bid_arr[entry_i]
    entry_ask = ask_arr[entry_i]
    exit_bid = bid_arr[exit_i]
    exit_ask = ask_arr[exit_i]

    long = pos > 0
    short = pos < 0

    pnl = 0.0
    pnl += np.sum(pos[long] * (exit_bid[long] - entry_ask[long]))
    pnl += np.sum((-pos[short]) * (entry_bid[short] - exit_ask[short]))
    return float(pnl)


def strict_backtest_fast(cand, window, entry_z, exit_z, max_hold, gross):
    cname = cand["candidate"]
    q_low = q_from_weights(cand["pos_low_weights"], gross=gross)

    day_rows = []
    all_trades = []

    for day, pnp in panel_np.items():
        z = z_cache[(cname, day, window)]
        bid_arr = pnp["bid_arr"]
        ask_arr = pnp["ask_arr"]
        ts_arr = pnp["ts_arr"]
        n = pnp["n"]

        trades = []
        i = window

        while i < n - 2:
            zi = z[i]

            if not np.isfinite(zi):
                i += 1
                continue

            if zi <= -entry_z:
                pos = q_low
                side = 1
            elif zi >= entry_z:
                pos = -q_low
                side = -1
            else:
                i += 1
                continue

            entry_i = i
            max_j = min(n - 2, entry_i + int(max_hold))

            # First zero/exit-zone touch, otherwise max_hold/end.
            z_slice = z[entry_i + 1 : max_j + 1]
            exit_hits = np.where(np.isfinite(z_slice) & (np.abs(z_slice) <= exit_z))[0]

            if len(exit_hits) > 0:
                exit_i = entry_i + 1 + int(exit_hits[0])
            else:
                exit_i = max_j

            pnl = exec_pnl_np(pos, entry_i, exit_i, bid_arr, ask_arr)

            trade = {
                "candidate": cname,
                "family": cand["family"],
                "signal_type": cand["signal_type"],
                "note": cand["note"],
                "day": day,
                "window": window,
                "entry_z": entry_z,
                "exit_z": exit_z,
                "max_hold": max_hold,
                "gross": gross,
                "entry_idx": entry_i,
                "exit_idx": exit_i,
                "entry_ts": ts_arr[entry_i],
                "exit_ts": ts_arr[exit_i],
                "side": side,
                "entry_z_seen": float(z[entry_i]),
                "exit_z_seen": float(z[exit_i]) if np.isfinite(z[exit_i]) else np.nan,
                "hold": int(exit_i - entry_i),
                "exec_pnl": pnl,
                "q_trade": q_low.tolist(),
                "position": pos.tolist(),
            }

            trades.append(trade)
            all_trades.append(trade)

            # Strict: only one open position at a time.
            i = exit_i + 1

        if trades:
            pnls = np.array([t["exec_pnl"] for t in trades], dtype=float)
            trade_count = len(pnls)
            day_pnl = float(pnls.sum())
            hit_rate = float(np.mean(pnls > 0))
            avg_trade_pnl = float(np.mean(pnls))
            median_trade_pnl = float(np.median(pnls))
        else:
            trade_count = 0
            day_pnl = 0.0
            hit_rate = np.nan
            avg_trade_pnl = np.nan
            median_trade_pnl = np.nan

        day_rows.append({
            "candidate": cname,
            "family": cand["family"],
            "signal_type": cand["signal_type"],
            "note": cand["note"],
            "day": day,
            "window": window,
            "entry_z": entry_z,
            "exit_z": exit_z,
            "max_hold": max_hold,
            "gross": gross,
            "q_trade": q_low.tolist(),
            "net_position": float(np.sum(q_low)),
            "gross_position": float(np.sum(np.abs(q_low))),
            "trade_count": trade_count,
            "day_pnl": day_pnl,
            "hit_rate": hit_rate,
            "avg_trade_pnl": avg_trade_pnl,
            "median_trade_pnl": median_trade_pnl,
        })

    day_df = pd.DataFrame(day_rows)

    total_pnl = float(day_df["day_pnl"].sum())
    total_trades = int(day_df["trade_count"].sum())
    active_days = int((day_df["trade_count"] > 0).sum())

    mean_hit = float(day_df["hit_rate"].mean())
    min_hit = float(day_df["hit_rate"].min())
    min_day = float(day_df["day_pnl"].min())
    max_day = float(day_df["day_pnl"].max())
    one_day_dep = abs(max_day) / abs(total_pnl) if total_pnl != 0 else np.inf

    summary = {
        "candidate": cname,
        "family": cand["family"],
        "signal_type": cand["signal_type"],
        "note": cand["note"],
        "window": window,
        "entry_z": entry_z,
        "exit_z": exit_z,
        "max_hold": max_hold,
        "gross": gross,
        "q_trade": q_low.tolist(),
        "net_position": float(np.sum(q_low)),
        "gross_position": float(np.sum(np.abs(q_low))),
        "days": len(DAYS),
        "active_days": active_days,
        "total_trades": total_trades,
        "total_pnl": total_pnl,
        "mean_day_pnl": float(day_df["day_pnl"].mean()),
        "min_day_pnl": min_day,
        "max_day_pnl": max_day,
        "mean_hit_rate": mean_hit,
        "min_hit_rate": min_hit,
        "pnl_per_trade": float(total_pnl / total_trades) if total_trades else np.nan,
        "one_day_dependency": float(one_day_dep),
    }

    summary["robust_pass"] = (
        active_days == len(DAYS)
        and total_trades >= 5
        and min_day > 0
        and mean_hit > 0.55
    )
    summary["robust_score"] = robust_score(total_pnl, min_day, mean_hit, one_day_dep)

    return summary, day_df, all_trades

Selected strict candidates: 87
lead_lag            57
colour_basket        8
colour_mixing        7
single               6
pairwise             5
colour_curvature     4
Name: count, dtype: int64
Precomputing signals and z-scores...
[   0.00s] candidate 1/87: lead_AMBER_to_ORANGE_follow_lag50
[   0.11s] candidate 20/87: lead_AMBER_to_MAGENTA_follow_lag1000
[   0.25s] candidate 40/87: RED_vs_MAGENTA_logratio_trend
[   0.38s] candidate 60/87: basket_magenta_extreme_vs_rest_mr
[   0.52s] candidate 80/87: lead_ORANGE_to_YELLOW_inverse_lag500
[   0.58s] candidate 87/87: lead_ORANGE_to_RED_follow_lag1000
Cache done in 0.59s

In [12]:
# =========================
# 6B-FAST) Build targeted strict configs and run
# =========================

def neighbours(value, allowed):
    allowed = sorted(set(allowed))
    value = int(value)
    if value not in allowed:
        allowed.append(value)
        allowed = sorted(set(allowed))

    i = allowed.index(value)
    out = {value}
    if i > 0:
        out.add(allowed[i - 1])
    if i < len(allowed) - 1:
        out.add(allowed[i + 1])
    return sorted(out)


ALLOWED_WINDOWS = [500, 1000, 1500, 2500, 4000, 5000]
ALLOWED_ENTRIES = [1.25, 1.5, 1.75, 2.0, 2.25]
ALLOWED_EXITS = [0.0, 0.25, 0.5]
ALLOWED_HOLDS = [500, 1000, 1500, 2500, 4000]
ALLOWED_GROSSES = [40, 60, 72, 80]

# Use best event rows per selected candidate to form strict configs.
selected_event_rows = (
    ev[ev["candidate"].isin(selected_names)]
    .sort_values("robust_score", ascending=False)
    .groupby("candidate")
    .head(5)
    .copy()
)

configs = set()

for _, r in selected_event_rows.iterrows():
    cname = r["candidate"]

    base_w = int(r["window"])
    base_entry = float(r["threshold"])
    base_hold = int(r["horizon"])

    ws = neighbours(base_w, ALLOWED_WINDOWS)
    entries = sorted(set([base_entry] + neighbours(round(base_entry * 4) / 4, ALLOWED_ENTRIES)))
    entries = [e for e in entries if e in ALLOWED_ENTRIES]

    holds = neighbours(base_hold, ALLOWED_HOLDS)

    for w, entry_z, exit_z, hold, gross in product(
        ws,
        entries,
        ALLOWED_EXITS,
        holds,
        ALLOWED_GROSSES,
    ):
        configs.add((cname, int(w), float(entry_z), float(exit_z), int(hold), int(gross)))

# Add a small canonical grid for the highest-confidence names.
elite_names = ev.head(25)["candidate"].tolist()
for cname in elite_names:
    if cname not in selected_names:
        continue

    for w, entry_z, exit_z, hold, gross in product(
        [500, 1000, 2500],
        [1.25, 1.5, 1.75, 2.0],
        [0.0, 0.25, 0.5],
        [1000, 1500, 2500],
        [60, 72, 80],
    ):
        configs.add((cname, w, entry_z, exit_z, hold, gross))

configs = sorted(configs)
print("Strict configs:", len(configs))

strict_summaries = []
strict_day_breakdowns = []
strict_trades = []

t0 = time.time()

for k, (cname, w, entry_z, exit_z, hold, gross) in enumerate(configs, start=1):
    cand = candidate_by_name[cname]

    if k == 1 or k % 500 == 0 or k == len(configs):
        print(
            f"[{time.time()-t0:7.2f}s] strict {k}/{len(configs)}: "
            f"{cname}, w={w}, entry={entry_z}, exit={exit_z}, hold={hold}, gross={gross}"
        )

    summary, day_df, trades = strict_backtest_fast(
        cand=cand,
        window=w,
        entry_z=entry_z,
        exit_z=exit_z,
        max_hold=hold,
        gross=gross,
    )

    strict_summaries.append(summary)
    strict_day_breakdowns.append(day_df)
    strict_trades.extend(trades)

strict_summary_fast = pd.DataFrame(strict_summaries).sort_values("robust_score", ascending=False)
strict_day_breakdown_fast = pd.concat(strict_day_breakdowns, ignore_index=True)
strict_trades_fast = pd.DataFrame(strict_trades)

strict_summary_fast.to_csv(FAST_OUTDIR / "uv_visors_strict_summary_fast.csv", index=False)
strict_summary_fast[strict_summary_fast["robust_pass"]].to_csv(FAST_OUTDIR / "uv_visors_strict_robust_only_fast.csv", index=False)
strict_day_breakdown_fast.to_csv(FAST_OUTDIR / "uv_visors_strict_day_breakdown_fast.csv", index=False)
strict_trades_fast.to_csv(FAST_OUTDIR / "uv_visors_strict_trades_fast.csv", index=False)

print("Top strict summary:")
display(strict_summary_fast.head(50))

print("Robust only:")
display(strict_summary_fast[strict_summary_fast["robust_pass"]].head(50))

Strict configs: 54780
[   0.00s] strict 1/54780: AMBER_own_meanrev, w=500, entry=1.25, exit=0.0, hold=500, gross=40
[   2.27s] strict 500/54780: AMBER_own_meanrev, w=2500, entry=1.25, exit=0.5, hold=1000, gross=80
[   4.36s] strict 1000/54780: AMBER_vs_MAGENTA_ratio_mr, w=1500, entry=2.0, exit=0.0, hold=500, gross=80
[   6.62s] strict 1500/54780: MAGENTA_own_meanrev, w=1500, entry=1.75, exit=0.25, hold=2500, gross=80
[   8.50s] strict 2000/54780: MAGENTA_own_meanrev, w=5000, entry=1.25, exit=0.25, hold=1000, gross=80
[  11.19s] strict 2500/54780: ORANGE_own_meanrev, w=1000, entry=1.5, exit=0.25, hold=1000, gross=80
[  12.95s] strict 3000/54780: RED_vs_MAGENTA_logratio_trend, w=500, entry=1.25, exit=0.25, hold=2500, gross=80
[  15.14s] strict 3500/54780: RED_vs_MAGENTA_logratio_trend, w=1500, entry=1.75, exit=0.25, hold=1500, gross=80
[  17.35s] strict 4000/54780: YELLOW_own_meanrev, w=1000, entry=2.0, exit=0.25, hold=1500, gross=80
[  19.60s] strict 4500/54780: YELLOW_vs_ORANGE_logratio_trend, w=1000, entry=2.25, exit=0.5, hold=4000, gross=80
[  21.62s] strict 5000/54780: YELLOW_vs_ORANGE_ratio_trend, w=1000, entry=2.0, exit=0.25, hold=1000, gross=80
[  23.70s] strict 5500/54780: YELLOW_vs_ORANGE_spread_trend, w=1000, entry=1.75, exit=0.0, hold=4000, gross=80
[  25.86s] strict 6000/54780: basket_hot_vs_nonhot_mr, w=1500, entry=1.75, exit=0.0, hold=1500, gross=80
[  27.95s] strict 6500/54780: basket_magenta_extreme_vs_rest_mr, w=1000, entry=2.25, exit=0.0, hold=2500, gross=80
[  29.64s] strict 7000/54780: basket_magenta_extreme_vs_rest_mr, w=4000, entry=1.75, exit=0.25, hold=1500, gross=80
[  31.52s] strict 7500/54780: basket_magenta_extreme_vs_rest_trend, w=1000, entry=2.25, exit=0.0, hold=4000, gross=80
[  33.33s] strict 8000/54780: basket_orange_red_vs_others_trend, w=4000, entry=1.75, exit=0.25, hold=1500, gross=80
[  35.21s] strict 8500/54780: basket_red_extreme_vs_rest_mr, w=2500, entry=1.75, exit=0.25, hold=1000, gross=80
[  37.41s] strict 9000/54780: basket_spectrum_gradient_1_1_0_1_1_mr, w=2500, entry=2.25, exit=0.5, hold=1500, gross=80
[  39.69s] strict 9500/54780: basket_spectrum_gradient_2_1_0_1_2_mr, w=2500, entry=1.75, exit=0.5, hold=1000, gross=80
[  42.00s] strict 10000/54780: basket_yellow_amber_vs_red_magenta_mr, w=1500, entry=2.0, exit=0.5, hold=500, gross=80
[  45.55s] strict 10500/54780: basket_yellow_amber_vs_red_magenta_mr, w=5000, entry=1.75, exit=0.25, hold=1500, gross=80
[  47.59s] strict 11000/54780: curvature_AMBER_ORANGE_RED_mr, w=4000, entry=1.5, exit=0.25, hold=2500, gross=80
[  49.26s] strict 11500/54780: curvature_AMBER_RED_MAGENTA_mr, w=1000, entry=1.5, exit=0.5, hold=1000, gross=80
[  51.05s] strict 12000/54780: curvature_ORANGE_RED_MAGENTA_mr, w=1000, entry=1.25, exit=0.25, hold=2500, gross=80
[  52.79s] strict 12500/54780: curvature_YELLOW_AMBER_ORANGE_mr, w=500, entry=1.25, exit=0.25, hold=1500, gross=80
[  54.98s] strict 13000/54780: lead_AMBER_to_MAGENTA_follow_lag1000, w=500, entry=1.25, exit=0.0, hold=2500, gross=80
[  57.33s] strict 13500/54780: lead_AMBER_to_MAGENTA_follow_lag50, w=500, entry=1.25, exit=0.5, hold=1000, gross=80
[  60.49s] strict 14000/54780: lead_AMBER_to_MAGENTA_follow_lag50, w=4000, entry=1.25, exit=0.5, hold=1500, gross=80
[  62.84s] strict 14500/54780: lead_AMBER_to_MAGENTA_follow_lag500, w=4000, entry=2.25, exit=0.0, hold=1500, gross=80
[  65.58s] strict 15000/54780: lead_AMBER_to_MAGENTA_inverse_lag100, w=1000, entry=1.75, exit=0.5, hold=1500, gross=80
[  68.52s] strict 15500/54780: lead_AMBER_to_MAGENTA_inverse_lag100, w=4000, entry=1.75, exit=0.25, hold=500, gross=60
[  71.62s] strict 16000/54780: lead_AMBER_to_MAGENTA_inverse_lag50, w=1000, entry=1.75, exit=0.5, hold=500, gross=80
[  74.54s] strict 16500/54780: lead_AMBER_to_MAGENTA_inverse_lag500, w=500, entry=1.75, exit=0.25, hold=250, gross=60
[  77.44s] strict 17000/54780: lead_AMBER_to_MAGENTA_inverse_lag500, w=1500, entry=2.25, exit=0.5, hold=500, gross=60
[  81.91s] strict 17500/54780: lead_AMBER_to_ORANGE_follow_lag100, w=1500, entry=1.75, exit=0.25, hold=2500, gross=60
[  85.15s] strict 18000/54780: lead_AMBER_to_ORANGE_follow_lag50, w=1500, entry=1.25, exit=0.5, hold=2500, gross=60
[  87.66s] strict 18500/54780: lead_AMBER_to_ORANGE_follow_lag50, w=5000, entry=2.25, exit=0.25, hold=1000, gross=60
[  90.21s] strict 19000/54780: lead_AMBER_to_ORANGE_inverse_lag100, w=5000, entry=2.0, exit=0.5, hold=1000, gross=60
[  92.79s] strict 19500/54780: lead_AMBER_to_ORANGE_inverse_lag250, w=2500, entry=1.25, exit=0.5, hold=500, gross=60
[  94.93s] strict 20000/54780: lead_AMBER_to_ORANGE_inverse_lag500, w=1000, entry=1.75, exit=0.0, hold=1500, gross=60
[  97.70s] strict 20500/54780: lead_AMBER_to_ORANGE_inverse_lag500, w=2500, entry=2.25, exit=0.25, hold=500, gross=60
[ 100.00s] strict 21000/54780: lead_AMBER_to_RED_inverse_lag1000, w=500, entry=1.5, exit=0.5, hold=4000, gross=40
[ 102.27s] strict 21500/54780: lead_AMBER_to_RED_inverse_lag250, w=500, entry=1.25, exit=0.5, hold=1500, gross=80
[ 104.67s] strict 22000/54780: lead_AMBER_to_RED_inverse_lag250, w=5000, entry=1.5, exit=0.0, hold=1500, gross=80
[ 106.94s] strict 22500/54780: lead_AMBER_to_RED_inverse_lag500, w=2500, entry=1.75, exit=0.25, hold=4000, gross=80
[ 109.14s] strict 23000/54780: lead_AMBER_to_YELLOW_inverse_lag100, w=500, entry=1.5, exit=0.0, hold=1500, gross=80
[ 112.16s] strict 23500/54780: lead_AMBER_to_YELLOW_inverse_lag100, w=2500, entry=1.75, exit=0.25, hold=2500, gross=60
[ 114.69s] strict 24000/54780: lead_AMBER_to_YELLOW_inverse_lag1000, w=1000, entry=1.75, exit=0.5, hold=250, gross=60
[ 116.98s] strict 24500/54780: lead_AMBER_to_YELLOW_inverse_lag500, w=1000, entry=1.5, exit=0.25, hold=1000, gross=60
[ 119.44s] strict 25000/54780: lead_AMBER_to_YELLOW_inverse_lag500, w=4000, entry=1.5, exit=0.5, hold=4000, gross=60
[ 122.36s] strict 25500/54780: lead_MAGENTA_to_ORANGE_follow_lag100, w=4000, entry=1.25, exit=0.0, hold=4000, gross=60
[ 124.56s] strict 26000/54780: lead_MAGENTA_to_ORANGE_inverse_lag1000, w=5000, entry=1.75, exit=0.5, hold=1000, gross=60
[ 128.16s] strict 26500/54780: lead_MAGENTA_to_RED_follow_lag50, w=2500, entry=1.75, exit=0.0, hold=4000, gross=60
[ 132.64s] strict 27000/54780: lead_MAGENTA_to_RED_inverse_lag1000, w=1000, entry=1.75, exit=0.0, hold=1000, gross=60
[ 135.17s] strict 27500/54780: lead_MAGENTA_to_RED_inverse_lag500, w=2500, entry=2.25, exit=0.0, hold=500, gross=60
[ 137.76s] strict 28000/54780: lead_MAGENTA_to_YELLOW_follow_lag100, w=500, entry=1.75, exit=0.0, hold=250, gross=80
[ 140.86s] strict 28500/54780: lead_MAGENTA_to_YELLOW_follow_lag100, w=2500, entry=1.25, exit=0.25, hold=2500, gross=80
[ 143.31s] strict 29000/54780: lead_MAGENTA_to_YELLOW_follow_lag1000, w=500, entry=1.75, exit=0.0, hold=1000, gross=60
[ 145.61s] strict 29500/54780: lead_MAGENTA_to_YELLOW_follow_lag1000, w=2500, entry=1.25, exit=0.0, hold=4000, gross=60
[ 148.24s] strict 30000/54780: lead_MAGENTA_to_YELLOW_follow_lag250, w=1500, entry=2.0, exit=0.5, hold=500, gross=60
[ 150.65s] strict 30500/54780: lead_MAGENTA_to_YELLOW_follow_lag500, w=2500, entry=1.75, exit=0.0, hold=2500, gross=60
[ 153.38s] strict 31000/54780: lead_MAGENTA_to_YELLOW_inverse_lag100, w=500, entry=2.25, exit=0.0, hold=4000, gross=60
[ 156.46s] strict 31500/54780: lead_MAGENTA_to_YELLOW_inverse_lag100, w=2500, entry=1.75, exit=0.5, hold=2500, gross=60
[ 158.83s] strict 32000/54780: lead_MAGENTA_to_YELLOW_inverse_lag500, w=500, entry=2.0, exit=0.0, hold=2500, gross=80
[ 161.26s] strict 32500/54780: lead_MAGENTA_to_YELLOW_inverse_lag500, w=5000, entry=1.25, exit=0.0, hold=4000, gross=40
[ 163.52s] strict 33000/54780: lead_ORANGE_to_MAGENTA_inverse_lag1000, w=1500, entry=1.75, exit=0.0, hold=4000, gross=40
[ 166.27s] strict 33500/54780: lead_ORANGE_to_RED_follow_lag100, w=1000, entry=1.5, exit=0.5, hold=250, gross=40
[ 169.04s] strict 34000/54780: lead_ORANGE_to_RED_follow_lag1000, w=1000, entry=2.0, exit=0.25, hold=1000, gross=40
[ 171.86s] strict 34500/54780: lead_ORANGE_to_RED_follow_lag1000, w=4000, entry=2.0, exit=0.25, hold=1000, gross=40
[ 175.28s] strict 35000/54780: lead_ORANGE_to_RED_follow_lag50, w=5000, entry=1.25, exit=0.25, hold=1500, gross=40
[ 178.31s] strict 35500/54780: lead_ORANGE_to_YELLOW_follow_lag100, w=2500, entry=1.5, exit=0.5, hold=1500, gross=60
[ 180.91s] strict 36000/54780: lead_ORANGE_to_YELLOW_follow_lag250, w=1500, entry=1.5, exit=0.0, hold=500, gross=72
[ 183.76s] strict 36500/54780: lead_ORANGE_to_YELLOW_follow_lag50, w=1000, entry=1.75, exit=0.0, hold=1000, gross=80
[ 186.82s] strict 37000/54780: lead_ORANGE_to_YELLOW_inverse_lag1000, w=500, entry=1.75, exit=0.0, hold=1500, gross=80
[ 189.05s] strict 37500/54780: lead_ORANGE_to_YELLOW_inverse_lag500, w=1000, entry=1.25, exit=0.0, hold=4000, gross=80
[ 191.29s] strict 38000/54780: lead_ORANGE_to_YELLOW_inverse_lag500, w=5000, entry=1.25, exit=0.5, hold=1500, gross=80
[ 193.47s] strict 38500/54780: lead_RED_to_AMBER_follow_lag1000, w=1000, entry=1.75, exit=0.5, hold=1500, gross=80
[ 198.06s] strict 39000/54780: lead_RED_to_AMBER_follow_lag500, w=1500, entry=1.25, exit=0.25, hold=2500, gross=80
[ 200.54s] strict 39500/54780: lead_RED_to_AMBER_follow_lag500, w=4000, entry=1.75, exit=0.5, hold=2500, gross=80
[ 202.94s] strict 40000/54780: lead_RED_to_MAGENTA_inverse_lag1000, w=1000, entry=2.25, exit=0.5, hold=500, gross=80
[ 205.42s] strict 40500/54780: lead_RED_to_MAGENTA_inverse_lag500, w=2500, entry=1.25, exit=0.25, hold=500, gross=80
[ 207.73s] strict 41000/54780: lead_RED_to_ORANGE_follow_lag1000, w=4000, entry=1.5, exit=0.5, hold=1500, gross=80
[ 210.49s] strict 41500/54780: lead_RED_to_YELLOW_inverse_lag100, w=1500, entry=2.25, exit=0.5, hold=1000, gross=80
[ 213.14s] strict 42000/54780: lead_RED_to_YELLOW_inverse_lag1000, w=500, entry=1.75, exit=0.5, hold=1500, gross=60
[ 215.60s] strict 42500/54780: lead_RED_to_YELLOW_inverse_lag250, w=500, entry=1.5, exit=0.5, hold=1500, gross=80
[ 218.33s] strict 43000/54780: lead_RED_to_YELLOW_inverse_lag250, w=2500, entry=1.25, exit=0.25, hold=1000, gross=60
[ 220.66s] strict 43500/54780: lead_RED_to_YELLOW_inverse_lag500, w=500, entry=2.0, exit=0.5, hold=500, gross=60
[ 223.19s] strict 44000/54780: lead_RED_to_YELLOW_inverse_lag500, w=2500, entry=2.0, exit=0.0, hold=1500, gross=72
[ 225.61s] strict 44500/54780: lead_YELLOW_to_AMBER_follow_lag1000, w=1500, entry=1.75, exit=0.25, hold=2500, gross=60
[ 228.37s] strict 45000/54780: lead_YELLOW_to_MAGENTA_inverse_lag100, w=1000, entry=2.0, exit=0.0, hold=1500, gross=60
[ 231.25s] strict 45500/54780: lead_YELLOW_to_MAGENTA_inverse_lag100, w=4000, entry=2.25, exit=0.25, hold=1000, gross=60
[ 234.57s] strict 46000/54780: lead_YELLOW_to_MAGENTA_inverse_lag50, w=2500, entry=1.5, exit=0.0, hold=2500, gross=60
[ 237.41s] strict 46500/54780: lead_YELLOW_to_ORANGE_follow_lag50, w=500, entry=2.0, exit=0.0, hold=4000, gross=80
[ 240.78s] strict 47000/54780: lead_YELLOW_to_ORANGE_follow_lag50, w=2500, entry=1.75, exit=0.0, hold=2500, gross=72
[ 243.30s] strict 47500/54780: lead_YELLOW_to_ORANGE_follow_lag500, w=1000, entry=2.25, exit=0.0, hold=1500, gross=60
[ 245.87s] strict 48000/54780: lead_YELLOW_to_ORANGE_inverse_lag1000, w=4000, entry=1.5, exit=0.25, hold=1500, gross=60
[ 248.12s] strict 48500/54780: lead_YELLOW_to_RED_follow_lag1000, w=1000, entry=1.25, exit=0.0, hold=1000, gross=40
[ 250.54s] strict 49000/54780: lead_YELLOW_to_RED_follow_lag250, w=500, entry=2.0, exit=0.0, hold=2500, gross=80
[ 253.44s] strict 49500/54780: lead_YELLOW_to_RED_follow_lag250, w=1500, entry=2.25, exit=0.5, hold=500, gross=80
[ 256.12s] strict 50000/54780: lead_YELLOW_to_RED_follow_lag500, w=500, entry=1.25, exit=0.0, hold=4000, gross=80
[ 258.63s] strict 50500/54780: lead_YELLOW_to_RED_follow_lag500, w=1500, entry=2.0, exit=0.0, hold=500, gross=80
[ 260.99s] strict 51000/54780: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=1500, entry=1.75, exit=0.0, hold=2500, gross=80
[ 262.96s] strict 51500/54780: mix_AMBER_blend_YELLOW_RED_25_75_mr, w=4000, entry=1.25, exit=0.25, hold=1000, gross=80
[ 264.96s] strict 52000/54780: mix_AMBER_blend_YELLOW_RED_50_50_mr, w=1500, entry=1.75, exit=0.5, hold=500, gross=80
[ 267.35s] strict 52500/54780: mix_ORANGE_blend_AMBER_RED_50_50_mr, w=1500, entry=2.0, exit=0.25, hold=2500, gross=80
[ 269.09s] strict 53000/54780: mix_ORANGE_blend_YELLOW_RED_25_75_mr, w=500, entry=2.0, exit=0.0, hold=1000, gross=80
[ 271.24s] strict 53500/54780: mix_ORANGE_blend_YELLOW_RED_25_75_mr, w=5000, entry=1.25, exit=0.0, hold=1500, gross=80
[ 272.88s] strict 54000/54780: mix_RED_blend_ORANGE_MAGENTA_50_50_mr, w=2500, entry=1.25, exit=0.5, hold=1000, gross=80
[ 280.32s] strict 54500/54780: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=1000, entry=1.5, exit=0.5, hold=1500, gross=80
[ 281.50s] strict 54780/54780: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=1500, entry=2.25, exit=0.5, hold=4000, gross=80
Top strict summary:

,candidate,family,signal_type,note,window,entry_z,exit_z,max_hold,gross,q_trade,...,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
20968,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,80,"[0, 0, 0, 80, 0]",...,378720.0,126240.000000,116000.0,136560.0,0.833333,0.750000,31560.000000,0.360583,True,614886.666667
42547,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,80,"[80, 0, 0, 0, 0]",...,405040.0,135013.333333,96480.0,177920.0,0.833333,0.833333,22502.222222,0.439265,True,602166.666667
21090,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,0.00,2500,80,"[0, 0, 0, 80, 0]",...,363120.0,121040.000000,106640.0,136560.0,0.805556,0.666667,33010.909091,0.376074,True,580427.777778
20967,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,72,"[0, 0, 0, 72, 0]",...,340848.0,113616.000000,104400.0,122904.0,0.833333,0.750000,28404.000000,0.360583,True,553814.666667
17749,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,0.00,1500,80,"[0, 0, -80, 0, 0]",...,387520.0,129173.333333,78320.0,175680.0,0.714286,0.571429,18453.333333,0.453344,True,547731.428571
41977,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,0.00,1500,80,"[80, 0, 0, 0, 0]",...,335040.0,111680.000000,102320.0,126320.0,0.766667,0.666667,19708.235294,0.377030,True,543513.333333
42546,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,72,"[72, 0, 0, 0, 0]",...,364536.0,121512.000000,86832.0,160128.0,0.833333,0.833333,20252.000000,0.439265,True,542366.666667
48313,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,0.00,1000,80,"[0, 0, 0, -80, 0]",...,418480.0,139493.333333,57760.0,182480.0,0.777778,0.666667,15499.259259,0.436054,True,537888.888889
42013,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,0.00,1500,80,"[80, 0, 0, 0, 0]",...,340240.0,113413.333333,92320.0,134320.0,0.711111,0.666667,20014.117647,0.394780,True,528435.555556
21089,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,0.00,2500,72,"[0, 0, 0, 72, 0]",...,326808.0,108936.000000,95976.0,122904.0,0.805556,0.666667,29709.818182,0.376074,True,522787.777778
17021,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,0.00,1500,80,"[0, 0, -80, 0, 0]",...,339600.0,113200.000000,84000.0,158800.0,0.714286,0.571429,16171.428571,0.467609,True,511171.428571
31001,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,2.25,0.00,4000,80,"[80, 0, 0, 0, 0]",...,343600.0,114533.333333,80320.0,165840.0,0.777778,0.666667,38177.777778,0.482654,True,508128.888889
27957,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,0.00,500,80,"[-80, 0, 0, 0, 0]",...,311520.0,103840.000000,95600.0,116480.0,0.641204,0.611111,6230.400000,0.373909,True,505926.018519
42165,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,2500,80,"[80, 0, 0, 0, 0]",...,336960.0,112320.000000,78480.0,171200.0,0.655128,0.600000,7658.181818,0.508072,True,495835.641026
42162,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,1500,80,"[80, 0, 0, 0, 0]",...,336960.0,112320.000000,78480.0,171200.0,0.655128,0.600000,7658.181818,0.508072,True,495835.641026
17293,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,1000,1.75,0.00,1500,80,"[0, 0, -80, 0, 0]",...,341200.0,113733.333333,75760.0,173200.0,0.822222,0.800000,20070.588235,0.507620,True,495531.111111
42159,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,1000,80,"[80, 0, 0, 0, 0]",...,336320.0,112106.666667,77840.0,171200.0,0.655128,0.600000,7643.636364,0.509039,True,493755.641026
35268,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,0.00,500,80,"[-80, 0, 0, 0, 0]",...,322880.0,107626.666667,83520.0,120960.0,0.698413,0.642857,7508.837209,0.374628,True,493412.063492
17748,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,0.00,1500,72,"[0, 0, -72, 0, 0]",...,348768.0,116256.000000,70488.0,158112.0,0.714286,0.571429,16608.000000,0.453344,True,493315.428571
43683,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1000,2.00,0.00,500,80,"[80, 0, 0, 0, 0]",...,308240.0,102746.666667,90240.0,112000.0,0.716667,0.700000,9632.500000,0.363353,True,492303.333333
41976,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,0.00,1500,72,"[72, 0, 0, 0, 0]",...,301536.0,100512.000000,92088.0,113688.0,0.766667,0.666667,17737.411765,0.377030,True,489545.333333
32081,lead_MAGENTA_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,1000,1.25,0.00,2500,80,"[80, 0, 0, 0, 0]",...,330560.0,110186.666667,76880.0,155360.0,0.833333,0.500000,27546.666667,0.469990,True,488486.666667
48312,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,0.00,1000,72,"[0, 0, 0, -72, 0]",...,376632.0,125544.000000,51984.0,164232.0,0.777778,0.666667,13949.333333,0.436054,True,484488.888889
43849,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1500,1.75,0.00,1000,80,"[80, 0, 0, 0, 0]",...,334480.0,111493.333333,72560.0,146560.0,0.902778,0.833333,17604.210526,0.438173,True,484113.888889
23170,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,1000,1.75,0.00,1500,80,"[80, 0, 0, 0, 0]",...,299680.0,99893.333333,89680.0,108800.0,0.655556,0.500000,17628.235294,0.363054,True,482317.777778
14965,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,1.75,0.00,1000,80,"[0, 0, 0, 0, 80]",...,320880.0,106960.000000,76320.0,148960.0,0.607143,0.500000,13951.304348,0.464223,True,476555.714286
42012,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,0.00,1500,72,"[72, 0, 0, 0, 0]",...,306216.0,102072.000000,83088.0,120888.0,0.711111,0.666667,18012.705882,0.394780,True,475947.555556
42203,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,2500,80,"[80, 0, 0, 0, 0]",...,314000.0,104666.666667,78880.0,152720.0,0.679365,0.571429,7658.536585,0.486369,True,475156.825397
42199,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,1500,80,"[80, 0, 0, 0, 0]",...,314000.0,104666.666667,78880.0,152720.0,0.679365,0.571429,7658.536585,0.486369,True,475156.825397
21190,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.75,0.00,2500,80,"[0, 0, 0, 80, 0]",...,295120.0,98373.333333,88000.0,114560.0,0.777778,0.666667,32791.111111,0.388181,True,475008.888889
48373,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.50,0.00,1000,80,"[0, 0, 0, -80, 0]",...,376880.0,125626.666667,46960.0,181680.0,0.694444,0.555556,14495.384615,0.482063,True,474272.222222
16018,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,0.00,1000,80,"[0, 0, 0, 0, 80]",...,331920.0,110640.000000,69120.0,144320.0,0.710317,0.666667,13830.000000,0.434804,True,473711.587302
36048,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 250,2500,1.25,0.00,2500,80,"[-80, 0, 0, 0, 0]",...,297280.0,99093.333333,85040.0,123520.0,0.888889,0.666667,33031.111111,0.415501,True,471804.444444
42081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,250,80,"[80, 0, 0, 0, 0]",...,338000.0,112666.666667,65280.0,169840.0,0.590168,0.458333,4278.481013,0.502485,True,471090.837743
42085,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,500,80,"[80, 0, 0, 0, 0]",...,343920.0,114640.000000,68480.0,197440.0,0.588889,0.500000,8188.571429,0.574087,True,471084.444444
46402,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,0.00,1000,80,"[0, 0, -80, 0, 0]",...,322560.0,107520.000000,72480.0,126640.0,0.703704,0.666667,11946.666667,0.392609,True,471038.518519
42619,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.25,0.00,1500,80,"[80, 0, 0, 0, 0]",...,333040.0,111013.333333,65520.0,145200.0,0.777778,0.666667,18502.222222,0.435984,True,467968.888889
42655,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.50,0.00,1500,80,"[80, 0, 0, 0, 0]",...,295440.0,98480.000000,83840.0,123840.0,0.744444,0.600000,18465.000000,0.419171,True,466842.222222
36571,lead_ORANGE_to_YELLOW_follow_lag50,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 50,1000,2.25,0.00,1000,80,"[-80, 0, 0, 0, 0]",...,301840.0,100613.333333,79840.0,131920.0,0.714286,0.571429,14373.333333,0.437053,True,465091.428571
42195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,1000,80,"[80, 0, 0, 0, 0]",...,307600.0,102533.333333,76000.0,152720.0,0.679365,0.571429,7502.439024,0.496489,True,462996.825397
20966,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,60,"[0, 0, 0, 60, 0]",...,284040.0,94680.000000,87000.0,102420.0,0.833333,0.750000,23670.000000,0.360583,True,462206.666667
17020,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,0.00,1500,72,"[0, 0, -72, 0, 0]",...,305640.0,101880.000000,75600.0,142920.0,0.714286,0.571429,14554.285714,0.467609,True,460411.428571
31000,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,2.25,0.00,4000,72,"[72, 0, 0, 0, 0]",...,309240.0,103080.000000,72288.0,149256.0,0.777778,0.666667,34360.000000,0.482654,True,457704.888889
15783,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,2.00,0.00,500,80,"[0, 0, 0, 0, 80]",...,318080.0,106026.666667,68480.0,161760.0,0.729167,0.500000,6626.666667,0.508551,True,457325.833333
42307,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,500,80,"[80, 0, 0, 0, 0]",...,321600.0,107200.000000,68880.0,171280.0,0.547339,0.470588,6991.304348,0.532587,False,456856.694678
27956,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,0.00,500,72,"[-72, 0, 0, 0, 0]",...,280368.0,93456.000000,86040.0,104832.0,0.641204,0.611111,5607.360000,0.373909,True,455654.018519
42545,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,60,"[60, 0, 0, 0, 0]",...,303780.0,101260.000000,72360.0,133440.0,0.833333,0.833333,16876.666667,0.439265,True,452666.666667
15687,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.50,0.00,250,80,"[0, 0, 0, 0, 80]",...,334080.0,111360.000000,57600.0,144400.0,0.640274,0.580645,3516.631579,0.432232,True,452481.368524
43749,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1500,1.25,0.00,500,80,"[80, 0, 0, 0, 0]",...,310560.0,103520.000000,67200.0,122000.0,0.620879,0.307692,7764.000000,0.392839,True,448064.395604
42164,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,2500,72,"[72, 0, 0, 0, 0]",...,303264.0,101088.000000,70632.0,154080.0,0.655128,0.600000,6892.363636,0.508072,True,446579.641026

Robust only:

,candidate,family,signal_type,note,window,entry_z,exit_z,max_hold,gross,q_trade,...,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
20968,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,80,"[0, 0, 0, 80, 0]",...,378720.0,126240.000000,116000.0,136560.0,0.833333,0.750000,31560.000000,0.360583,True,614886.666667
42547,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,80,"[80, 0, 0, 0, 0]",...,405040.0,135013.333333,96480.0,177920.0,0.833333,0.833333,22502.222222,0.439265,True,602166.666667
21090,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,0.00,2500,80,"[0, 0, 0, 80, 0]",...,363120.0,121040.000000,106640.0,136560.0,0.805556,0.666667,33010.909091,0.376074,True,580427.777778
20967,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,72,"[0, 0, 0, 72, 0]",...,340848.0,113616.000000,104400.0,122904.0,0.833333,0.750000,28404.000000,0.360583,True,553814.666667
17749,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,0.00,1500,80,"[0, 0, -80, 0, 0]",...,387520.0,129173.333333,78320.0,175680.0,0.714286,0.571429,18453.333333,0.453344,True,547731.428571
41977,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,0.00,1500,80,"[80, 0, 0, 0, 0]",...,335040.0,111680.000000,102320.0,126320.0,0.766667,0.666667,19708.235294,0.377030,True,543513.333333
42546,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,72,"[72, 0, 0, 0, 0]",...,364536.0,121512.000000,86832.0,160128.0,0.833333,0.833333,20252.000000,0.439265,True,542366.666667
48313,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,0.00,1000,80,"[0, 0, 0, -80, 0]",...,418480.0,139493.333333,57760.0,182480.0,0.777778,0.666667,15499.259259,0.436054,True,537888.888889
42013,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,0.00,1500,80,"[80, 0, 0, 0, 0]",...,340240.0,113413.333333,92320.0,134320.0,0.711111,0.666667,20014.117647,0.394780,True,528435.555556
21089,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.25,0.00,2500,72,"[0, 0, 0, 72, 0]",...,326808.0,108936.000000,95976.0,122904.0,0.805556,0.666667,29709.818182,0.376074,True,522787.777778
17021,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,0.00,1500,80,"[0, 0, -80, 0, 0]",...,339600.0,113200.000000,84000.0,158800.0,0.714286,0.571429,16171.428571,0.467609,True,511171.428571
31001,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,2.25,0.00,4000,80,"[80, 0, 0, 0, 0]",...,343600.0,114533.333333,80320.0,165840.0,0.777778,0.666667,38177.777778,0.482654,True,508128.888889
27957,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,0.00,500,80,"[-80, 0, 0, 0, 0]",...,311520.0,103840.000000,95600.0,116480.0,0.641204,0.611111,6230.400000,0.373909,True,505926.018519
42165,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,2500,80,"[80, 0, 0, 0, 0]",...,336960.0,112320.000000,78480.0,171200.0,0.655128,0.600000,7658.181818,0.508072,True,495835.641026
42162,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,1500,80,"[80, 0, 0, 0, 0]",...,336960.0,112320.000000,78480.0,171200.0,0.655128,0.600000,7658.181818,0.508072,True,495835.641026
17293,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,1000,1.75,0.00,1500,80,"[0, 0, -80, 0, 0]",...,341200.0,113733.333333,75760.0,173200.0,0.822222,0.800000,20070.588235,0.507620,True,495531.111111
42159,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,1000,80,"[80, 0, 0, 0, 0]",...,336320.0,112106.666667,77840.0,171200.0,0.655128,0.600000,7643.636364,0.509039,True,493755.641026
35268,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 100,1000,1.75,0.00,500,80,"[-80, 0, 0, 0, 0]",...,322880.0,107626.666667,83520.0,120960.0,0.698413,0.642857,7508.837209,0.374628,True,493412.063492
17748,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 50,500,1.50,0.00,1500,72,"[0, 0, -72, 0, 0]",...,348768.0,116256.000000,70488.0,158112.0,0.714286,0.571429,16608.000000,0.453344,True,493315.428571
43683,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1000,2.00,0.00,500,80,"[80, 0, 0, 0, 0]",...,308240.0,102746.666667,90240.0,112000.0,0.716667,0.700000,9632.500000,0.363353,True,492303.333333
41976,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,1.75,0.00,1500,72,"[72, 0, 0, 0, 0]",...,301536.0,100512.000000,92088.0,113688.0,0.766667,0.666667,17737.411765,0.377030,True,489545.333333
32081,lead_MAGENTA_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,1000,1.25,0.00,2500,80,"[80, 0, 0, 0, 0]",...,330560.0,110186.666667,76880.0,155360.0,0.833333,0.500000,27546.666667,0.469990,True,488486.666667
48312,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.25,0.00,1000,72,"[0, 0, 0, -72, 0]",...,376632.0,125544.000000,51984.0,164232.0,0.777778,0.666667,13949.333333,0.436054,True,484488.888889
43849,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1500,1.75,0.00,1000,80,"[80, 0, 0, 0, 0]",...,334480.0,111493.333333,72560.0,146560.0,0.902778,0.833333,17604.210526,0.438173,True,484113.888889
23170,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows AMBER return over lag...,1000,1.75,0.00,1500,80,"[80, 0, 0, 0, 0]",...,299680.0,99893.333333,89680.0,108800.0,0.655556,0.500000,17628.235294,0.363054,True,482317.777778
14965,lead_AMBER_to_MAGENTA_inverse_lag100,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,1.75,0.00,1000,80,"[0, 0, 0, 0, 80]",...,320880.0,106960.000000,76320.0,148960.0,0.607143,0.500000,13951.304348,0.464223,True,476555.714286
42012,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,500,2.00,0.00,1500,72,"[72, 0, 0, 0, 0]",...,306216.0,102072.000000,83088.0,120888.0,0.711111,0.666667,18012.705882,0.394780,True,475947.555556
42203,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,2500,80,"[80, 0, 0, 0, 0]",...,314000.0,104666.666667,78880.0,152720.0,0.679365,0.571429,7658.536585,0.486369,True,475156.825397
42199,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,1500,80,"[80, 0, 0, 0, 0]",...,314000.0,104666.666667,78880.0,152720.0,0.679365,0.571429,7658.536585,0.486369,True,475156.825397
21190,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,1000,1.75,0.00,2500,80,"[0, 0, 0, 80, 0]",...,295120.0,98373.333333,88000.0,114560.0,0.777778,0.666667,32791.111111,0.388181,True,475008.888889
48373,lead_YELLOW_to_RED_follow_lag1000,lead_lag,leader_return_follow,RED follows YELLOW return over lag 1000,500,1.50,0.00,1000,80,"[0, 0, 0, -80, 0]",...,376880.0,125626.666667,46960.0,181680.0,0.694444,0.555556,14495.384615,0.482063,True,474272.222222
16018,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,1000,2.00,0.00,1000,80,"[0, 0, 0, 0, 80]",...,331920.0,110640.000000,69120.0,144320.0,0.710317,0.666667,13830.000000,0.434804,True,473711.587302
36048,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 250,2500,1.25,0.00,2500,80,"[-80, 0, 0, 0, 0]",...,297280.0,99093.333333,85040.0,123520.0,0.888889,0.666667,33031.111111,0.415501,True,471804.444444
42081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,250,80,"[80, 0, 0, 0, 0]",...,338000.0,112666.666667,65280.0,169840.0,0.590168,0.458333,4278.481013,0.502485,True,471090.837743
42085,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,500,80,"[80, 0, 0, 0, 0]",...,343920.0,114640.000000,68480.0,197440.0,0.588889,0.500000,8188.571429,0.574087,True,471084.444444
46402,lead_YELLOW_to_ORANGE_follow_lag50,lead_lag,leader_return_follow,ORANGE follows YELLOW return over lag 50,500,1.50,0.00,1000,80,"[0, 0, -80, 0, 0]",...,322560.0,107520.000000,72480.0,126640.0,0.703704,0.666667,11946.666667,0.392609,True,471038.518519
42619,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.25,0.00,1500,80,"[80, 0, 0, 0, 0]",...,333040.0,111013.333333,65520.0,145200.0,0.777778,0.666667,18502.222222,0.435984,True,467968.888889
42655,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,1000,1.50,0.00,1500,80,"[80, 0, 0, 0, 0]",...,295440.0,98480.000000,83840.0,123840.0,0.744444,0.600000,18465.000000,0.419171,True,466842.222222
36571,lead_ORANGE_to_YELLOW_follow_lag50,lead_lag,leader_return_follow,YELLOW follows ORANGE return over lag 50,1000,2.25,0.00,1000,80,"[-80, 0, 0, 0, 0]",...,301840.0,100613.333333,79840.0,131920.0,0.714286,0.571429,14373.333333,0.437053,True,465091.428571
42195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,1000,80,"[80, 0, 0, 0, 0]",...,307600.0,102533.333333,76000.0,152720.0,0.679365,0.571429,7502.439024,0.496489,True,462996.825397
20966,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.50,0.00,2500,60,"[0, 0, 0, 60, 0]",...,284040.0,94680.000000,87000.0,102420.0,0.833333,0.750000,23670.000000,0.360583,True,462206.666667
17020,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,leader_return_follow,ORANGE follows AMBER return over lag 100,500,1.25,0.00,1500,72,"[0, 0, -72, 0, 0]",...,305640.0,101880.000000,75600.0,142920.0,0.714286,0.571429,14554.285714,0.467609,True,460411.428571
31000,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,leader_return_inverse,YELLOW inversely follows MAGENTA return over l...,500,2.25,0.00,4000,72,"[72, 0, 0, 0, 0]",...,309240.0,103080.000000,72288.0,149256.0,0.777778,0.666667,34360.000000,0.482654,True,457704.888889
15783,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,2.00,0.00,500,80,"[0, 0, 0, 0, 80]",...,318080.0,106026.666667,68480.0,161760.0,0.729167,0.500000,6626.666667,0.508551,True,457325.833333
27956,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,leader_return_follow,YELLOW follows MAGENTA return over lag 100,500,1.50,0.00,500,72,"[-72, 0, 0, 0, 0]",...,280368.0,93456.000000,86040.0,104832.0,0.641204,0.611111,5607.360000,0.373909,True,455654.018519
42545,lead_RED_to_YELLOW_inverse_lag250,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 250,500,2.00,0.00,1500,60,"[60, 0, 0, 0, 0]",...,303780.0,101260.000000,72360.0,133440.0,0.833333,0.833333,16876.666667,0.439265,True,452666.666667
15687,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,leader_return_inverse,MAGENTA inversely follows AMBER return over la...,500,1.50,0.00,250,80,"[0, 0, 0, 0, 80]",...,334080.0,111360.000000,57600.0,144400.0,0.640274,0.580645,3516.631579,0.432232,True,452481.368524
43749,lead_RED_to_YELLOW_inverse_lag500,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 500,1500,1.25,0.00,500,80,"[80, 0, 0, 0, 0]",...,310560.0,103520.000000,67200.0,122000.0,0.620879,0.307692,7764.000000,0.392839,True,448064.395604
42164,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,2500,72,"[72, 0, 0, 0, 0]",...,303264.0,101088.000000,70632.0,154080.0,0.655128,0.600000,6892.363636,0.508072,True,446579.641026
42161,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,leader_return_inverse,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,1500,72,"[72, 0, 0, 0, 0]",...,303264.0,101088.000000,70632.0,154080.0,0.655128,0.600000,6892.363636,0.508072,True,446579.641026

In [13]:
# =========================
# 7-FAST) Best strict config breakdown
# =========================

best = strict_summary_fast.iloc[0]

print("BEST STRICT CONFIG")
display(best.to_frame().T)

best_day_fast = strict_day_breakdown_fast[
    (strict_day_breakdown_fast["candidate"] == best["candidate"])
    & (strict_day_breakdown_fast["window"] == best["window"])
    & (strict_day_breakdown_fast["entry_z"] == best["entry_z"])
    & (strict_day_breakdown_fast["exit_z"] == best["exit_z"])
    & (strict_day_breakdown_fast["max_hold"] == best["max_hold"])
    & (strict_day_breakdown_fast["gross"] == best["gross"])
].copy()

best_trades_fast = strict_trades_fast[
    (strict_trades_fast["candidate"] == best["candidate"])
    & (strict_trades_fast["window"] == best["window"])
    & (strict_trades_fast["entry_z"] == best["entry_z"])
    & (strict_trades_fast["exit_z"] == best["exit_z"])
    & (strict_trades_fast["max_hold"] == best["max_hold"])
    & (strict_trades_fast["gross"] == best["gross"])
].copy()

print("BEST CONFIG DAY BREAKDOWN")
display(best_day_fast)

print("BEST CONFIG TRADES")
display(best_trades_fast)

best_day_fast.to_csv(FAST_OUTDIR / "uv_visors_best_day_breakdown_fast.csv", index=False)
best_trades_fast.to_csv(FAST_OUTDIR / "uv_visors_best_trades_fast.csv", index=False)

family_view_fast = (
    strict_summary_fast
    .groupby("family")
    .agg(
        best_total_pnl=("total_pnl", "max"),
        best_robust_score=("robust_score", "max"),
        robust_count=("robust_pass", "sum"),
        configs=("candidate", "count"),
    )
    .sort_values("best_robust_score", ascending=False)
)

print("FAMILY COMPARISON")
display(family_view_fast)

family_view_fast.to_csv(FAST_OUTDIR / "uv_visors_family_comparison_fast.csv")

BEST STRICT CONFIG

,candidate,family,signal_type,note,window,entry_z,exit_z,max_hold,gross,q_trade,...,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
20968,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,500,1.5,0.0,2500,80,"[0, 0, 0, 80, 0]",...,378720.0,126240.0,116000.0,136560.0,0.833333,0.75,31560.0,0.360583,True,614886.666667

BEST CONFIG DAY BREAKDOWN

,candidate,family,signal_type,note,day,window,entry_z,exit_z,max_hold,gross,q_trade,net_position,gross_position,trade_count,day_pnl,hit_rate,avg_trade_pnl,median_trade_pnl
62904,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.0,2500,80,"[0, 0, 0, 80, 0]",80.0,80.0,4,116000.0,0.75,29000.0,30840.0
62905,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,3,500,1.5,0.0,2500,80,"[0, 0, 0, 80, 0]",80.0,80.0,4,136560.0,0.75,34140.0,34680.0
62906,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,4,500,1.5,0.0,2500,80,"[0, 0, 0, 80, 0]",80.0,80.0,4,126160.0,1.00,31540.0,33240.0

BEST CONFIG TRADES

,candidate,family,signal_type,note,day,window,entry_z,exit_z,max_hold,gross,...,exit_idx,entry_ts,exit_ts,side,entry_z_seen,exit_z_seen,hold,exec_pnl,q_trade,position
992781,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.0,2500,80,...,4221,172100,422100,1,-1.509432,1.094972,2500,37360.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992782,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.0,2500,80,...,6740,424000,674000,-1,1.505966,-2.123194,2500,56800.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"
992783,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.0,2500,80,...,9241,674100,924100,1,-2.071663,-2.397480,2500,-2480.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992784,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.0,2500,80,...,9998,924200,999800,1,-2.659828,1.199641,756,24320.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992785,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,3,500,1.5,0.0,2500,80,...,4137,163700,413700,1,-1.575827,-1.057217,2500,22720.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992786,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,3,500,1.5,0.0,2500,80,...,6732,423200,673200,-1,1.550373,1.271245,2500,46640.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"
992787,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,3,500,1.5,0.0,2500,80,...,9455,695500,945500,1,-1.623993,1.749007,2500,73520.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992788,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,3,500,1.5,0.0,2500,80,...,9998,945600,999800,-1,1.799073,-1.401258,542,-6320.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"
992789,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,4,500,1.5,0.0,2500,80,...,3999,149900,399900,-1,2.057734,0.148917,2500,44480.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"
992790,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,4,500,1.5,0.0,2500,80,...,6626,412600,662600,1,-1.525797,1.648370,2500,49040.0,"[0, 0, 0, 80, 0]","[0, 0, 0, 80, 0]"
992791,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,4,500,1.5,0.0,2500,80,...,9127,662700,912700,-1,1.567073,1.639112,2500,10640.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"
992792,lead_AMBER_to_RED_inverse_lag1000,lead_lag,leader_return_inverse,RED inversely follows AMBER return over lag 1000,4,500,1.5,0.0,2500,80,...,9998,912800,999800,-1,1.810039,-2.684333,870,22000.0,"[0, 0, 0, 80, 0]","[0, 0, 0, -80, 0]"

FAMILY COMPARISON

                  best_total_pnl  best_robust_score  robust_count  configs
family
lead_lag                418480.0      614886.666667          4303    37608
pairwise                285000.0      413708.888889           472     3108
single                  307360.0      364760.000000           324     2640
colour_curvature        231240.0      342373.968254           148     2400
colour_mixing           231240.0      342373.968254           200     4188
colour_basket           180640.0      234397.619048          1718     4836

In [14]:
import numpy as np
import pandas as pd
from pathlib import Path
import itertools
import time

pd.set_option("display.max_rows", 80)
pd.set_option("display.max_columns", 80)
pd.set_option("display.width", 200)

UV_PRODUCTS = [
    "UV_VISOR_YELLOW",
    "UV_VISOR_AMBER",
    "UV_VISOR_ORANGE",
    "UV_VISOR_RED",
    "UV_VISOR_MAGENTA",
]

COLOUR_TO_PRODUCT = {
    "YELLOW": "UV_VISOR_YELLOW",
    "AMBER": "UV_VISOR_AMBER",
    "ORANGE": "UV_VISOR_ORANGE",
    "RED": "UV_VISOR_RED",
    "MAGENTA": "UV_VISOR_MAGENTA",
}

PRODUCT_TO_COLOUR = {v: k for k, v in COLOUR_TO_PRODUCT.items()}

OUT_DIR = Path("analysis_outputs/uv_visors_validation")
OUT_DIR.mkdir(parents=True, exist_ok=True)


def auto_find_price_df():
    """
    Tries to find your existing price dataframe.
    Edit this manually if your dataframe has a different name.
    """
    candidate_names = [
        "prices_df",
        "price_df",
        "prices",
        "df_prices",
        "prices_train",
        "df",
    ]
    for name in candidate_names:
        if name in globals():
            obj = globals()[name]
            if isinstance(obj, pd.DataFrame):
                cols = set(obj.columns)
                if {"product", "timestamp"}.issubset(cols):
                    print(f"Using dataframe: {name}, shape={obj.shape}")
                    return obj.copy()
    raise NameError(
        "Could not auto-find a price dataframe. Set PRICE_DF manually, e.g. PRICE_DF = prices_df.copy()"
    )


def prepare_uv_mid_by_day(price_df: pd.DataFrame, products=UV_PRODUCTS):
    """
    Converts long-format IMC price dataframe into:
    uv_by_day[day] = dataframe indexed by timestamp, columns = UV products, values = mid prices.
    """
    df = price_df.copy()

    if "day" not in df.columns:
        raise ValueError("Expected a 'day' column in the price dataframe.")

    if "mid_price" not in df.columns:
        if {"bid_price_1", "ask_price_1"}.issubset(df.columns):
            df["mid_price"] = (df["bid_price_1"] + df["ask_price_1"]) / 2
        else:
            raise ValueError("Need either 'mid_price' or bid_price_1/ask_price_1 columns.")

    df = df[df["product"].isin(products)].copy()

    uv_by_day = {}
    for day, g in df.groupby("day"):
        pivot = (
            g.pivot_table(
                index="timestamp",
                columns="product",
                values="mid_price",
                aggfunc="last",
            )
            .sort_index()
            .reindex(columns=products)
        )

        # light forward/back fill in case there are tiny gaps
        pivot = pivot.ffill().bfill()

        if pivot[products].isna().any().any():
            print(f"Warning: day {day} still has NaNs after fill.")

        uv_by_day[int(day)] = pivot

    print("Prepared days:", sorted(uv_by_day.keys()))
    for day, mid in uv_by_day.items():
        print(f"Day {day}: shape={mid.shape}, products={list(mid.columns)}")

    return uv_by_day


# Use existing uv_by_day if already created, otherwise build it.
if "uv_by_day" not in globals():
    PRICE_DF = auto_find_price_df()
    uv_by_day = prepare_uv_mid_by_day(PRICE_DF)

Using dataframe: prices, shape=(1500000, 19)
Prepared days: [2, 3, 4]
Day 2: shape=(10000, 5), products=['UV_VISOR_YELLOW', 'UV_VISOR_AMBER', 'UV_VISOR_ORANGE', 'UV_VISOR_RED', 'UV_VISOR_MAGENTA']
Day 3: shape=(10000, 5), products=['UV_VISOR_YELLOW', 'UV_VISOR_AMBER', 'UV_VISOR_ORANGE', 'UV_VISOR_RED', 'UV_VISOR_MAGENTA']
Day 4: shape=(10000, 5), products=['UV_VISOR_YELLOW', 'UV_VISOR_AMBER', 'UV_VISOR_ORANGE', 'UV_VISOR_RED', 'UV_VISOR_MAGENTA']

In [15]:
def rolling_z(raw: pd.Series, window: int) -> pd.Series:
    mu = raw.rolling(window, min_periods=window).mean()
    sd = raw.rolling(window, min_periods=window).std(ddof=0)
    return (raw - mu) / sd.replace(0, np.nan)


def make_q_lead_lag(follower: str, relation: str, gross: int) -> np.ndarray:
    """
    q_base is the position taken when z <= -entry_z.

    relation='follow':
      leader down => follower expected down => short follower.
      q_base follower = -gross.

    relation='inverse':
      leader down => follower expected up => long follower.
      q_base follower = +gross.
    """
    q = np.zeros(len(UV_PRODUCTS), dtype=float)
    idx = UV_PRODUCTS.index(follower)

    if relation == "follow":
        q[idx] = -gross
    elif relation == "inverse":
        q[idx] = gross
    else:
        raise ValueError(f"Unknown relation: {relation}")

    return q


def make_q_mix(target: str, a: str, b: str, wa: float, gross: int) -> np.ndarray:
    """
    Mean-reversion blend q_base for z <= -entry_z:
      target cheap vs blend => long target, short blend.
    """
    q = np.zeros(len(UV_PRODUCTS), dtype=float)

    ia = UV_PRODUCTS.index(a)
    ib = UV_PRODUCTS.index(b)
    it = UV_PRODUCTS.index(target)

    qa = round(gross * wa)
    qb = gross - qa

    q[it] += gross
    q[ia] -= qa
    q[ib] -= qb

    return q


def compute_signal_z(mid_df: pd.DataFrame, spec: dict, window: int) -> np.ndarray:
    """
    Supports:
      kind='lead_lag'
      kind='mix_mr'
      kind='pair_ratio'
      kind='pair_spread'
    """
    kind = spec["kind"]

    if kind == "lead_lag":
        leader = spec["leader"]
        lag = int(spec["lag"])
        raw = mid_df[leader].diff(lag)

    elif kind == "mix_mr":
        target = spec["target"]
        a = spec["a"]
        b = spec["b"]
        wa = float(spec["wa"])
        blend = wa * mid_df[a] + (1 - wa) * mid_df[b]
        raw = mid_df[target] - blend

    elif kind == "pair_ratio":
        a = spec["a"]
        b = spec["b"]
        raw = np.log(mid_df[a] / mid_df[b])

    elif kind == "pair_spread":
        a = spec["a"]
        b = spec["b"]
        raw = mid_df[a] - mid_df[b]

    else:
        raise ValueError(f"Unknown spec kind: {kind}")

    return rolling_z(raw, window).to_numpy(dtype=float)


def q_for_spec(spec: dict, gross: int) -> np.ndarray:
    kind = spec["kind"]

    if kind == "lead_lag":
        return make_q_lead_lag(
            follower=spec["follower"],
            relation=spec["relation"],
            gross=gross,
        )

    if kind == "mix_mr":
        return make_q_mix(
            target=spec["target"],
            a=spec["a"],
            b=spec["b"],
            wa=spec["wa"],
            gross=gross,
        )

    if kind in {"pair_ratio", "pair_spread"}:
        # Mean-reversion pair default:
        # z <= -entry means a cheap vs b => long a, short b.
        q = np.zeros(len(UV_PRODUCTS), dtype=float)
        ia = UV_PRODUCTS.index(spec["a"])
        ib = UV_PRODUCTS.index(spec["b"])
        q[ia] = gross / 2
        q[ib] = -gross / 2
        return q

    raise ValueError(f"Unknown spec kind: {kind}")


def find_exit_idx(z, entry_i, max_j, entry_side, exit_mode, exit_z, entry_z):
    """
    entry_side:
      +1 means entered on negative z, position = q_base
      -1 means entered on positive z, position = -q_base
    """
    z_slice = z[entry_i + 1 : max_j + 1]

    if len(z_slice) == 0:
        return max_j

    finite = np.isfinite(z_slice)

    if exit_mode == "fixed_hold":
        return max_j

    if exit_mode == "zero_cross":
        if entry_side == 1:
            hits = np.where(finite & (z_slice >= 0))[0]
        else:
            hits = np.where(finite & (z_slice <= 0))[0]
        return entry_i + 1 + int(hits[0]) if len(hits) else max_j

    if exit_mode == "abs_band":
        hits = np.where(finite & (np.abs(z_slice) <= exit_z))[0]
        return entry_i + 1 + int(hits[0]) if len(hits) else max_j

    if exit_mode == "signal_flip":
        if entry_side == 1:
            hits = np.where(finite & (z_slice >= entry_z))[0]
        else:
            hits = np.where(finite & (z_slice <= -entry_z))[0]
        return entry_i + 1 + int(hits[0]) if len(hits) else max_j

    raise ValueError(f"Unknown exit_mode: {exit_mode}")


def strict_backtest_one_day(
    mid_df: pd.DataFrame,
    spec: dict,
    window: int,
    entry_z: float,
    exit_z: float,
    max_hold: int,
    gross: int,
    exit_mode: str,
    day: int,
):
    """
    One-position-at-a-time strict backtest.
    Uses mid-to-mid PnL.
    """
    prices = mid_df[UV_PRODUCTS].to_numpy(dtype=float)
    z = compute_signal_z(mid_df, spec, window)
    q_base = q_for_spec(spec, gross)

    n = len(mid_df)
    trades = []

    start_i = max(window + int(spec.get("lag", 0)) + 1, window + 1)
    i = start_i

    while i < n - 1:
        zi = z[i]

        if not np.isfinite(zi):
            i += 1
            continue

        if zi <= -entry_z:
            side = 1
        elif zi >= entry_z:
            side = -1
        else:
            i += 1
            continue

        max_j = min(n - 1, i + max_hold)

        exit_i = find_exit_idx(
            z=z,
            entry_i=i,
            max_j=max_j,
            entry_side=side,
            exit_mode=exit_mode,
            exit_z=exit_z,
            entry_z=entry_z,
        )

        pos = side * q_base
        pnl = float(np.dot(pos, prices[exit_i] - prices[i]))

        trades.append(
            {
                "candidate": spec["name"],
                "family": spec.get("family", spec["kind"]),
                "kind": spec["kind"],
                "note": spec.get("note", ""),
                "day": day,
                "window": window,
                "entry_z": entry_z,
                "exit_z": exit_z,
                "exit_mode": exit_mode,
                "max_hold": max_hold,
                "gross": gross,
                "q_trade": list(q_base),
                "net_position": float(q_base.sum()),
                "gross_position": float(np.abs(q_base).sum()),
                "entry_idx": int(i),
                "exit_idx": int(exit_i),
                "entry_ts": int(mid_df.index[i]),
                "exit_ts": int(mid_df.index[exit_i]),
                "side": int(side),
                "entry_z_seen": float(zi),
                "exit_z_seen": float(z[exit_i]) if np.isfinite(z[exit_i]) else np.nan,
                "hold": int(exit_i - i),
                "exec_pnl": pnl,
                "position": list(pos),
            }
        )

        i = exit_i + 1

    return trades


def summarize_trades(trades_df: pd.DataFrame, spec: dict, cfg: dict):
    if trades_df.empty:
        day_rows = []
        for day in sorted(uv_by_day.keys()):
            day_rows.append(
                {
                    "candidate": spec["name"],
                    "family": spec.get("family", spec["kind"]),
                    "kind": spec["kind"],
                    "note": spec.get("note", ""),
                    "day": day,
                    **cfg,
                    "trade_count": 0,
                    "day_pnl": 0.0,
                    "hit_rate": np.nan,
                    "avg_trade_pnl": np.nan,
                    "median_trade_pnl": np.nan,
                }
            )
        day_df = pd.DataFrame(day_rows)
    else:
        day_df = (
            trades_df.groupby("day")
            .agg(
                trade_count=("exec_pnl", "size"),
                day_pnl=("exec_pnl", "sum"),
                hit_rate=("exec_pnl", lambda x: float((x > 0).mean())),
                avg_trade_pnl=("exec_pnl", "mean"),
                median_trade_pnl=("exec_pnl", "median"),
            )
            .reset_index()
        )

        for day in sorted(uv_by_day.keys()):
            if day not in set(day_df["day"]):
                day_df = pd.concat(
                    [
                        day_df,
                        pd.DataFrame(
                            [
                                {
                                    "day": day,
                                    "trade_count": 0,
                                    "day_pnl": 0.0,
                                    "hit_rate": np.nan,
                                    "avg_trade_pnl": np.nan,
                                    "median_trade_pnl": np.nan,
                                }
                            ]
                        ),
                    ],
                    ignore_index=True,
                )

        day_df = day_df.sort_values("day").reset_index(drop=True)

        for k, v in cfg.items():
            day_df[k] = v

        day_df["candidate"] = spec["name"]
        day_df["family"] = spec.get("family", spec["kind"])
        day_df["kind"] = spec["kind"]
        day_df["note"] = spec.get("note", "")

    total_pnl = float(day_df["day_pnl"].sum())
    mean_day_pnl = float(day_df["day_pnl"].mean())
    min_day_pnl = float(day_df["day_pnl"].min())
    max_day_pnl = float(day_df["day_pnl"].max())
    total_trades = int(day_df["trade_count"].sum())

    hit_rates = day_df["hit_rate"].dropna()
    mean_hit_rate = float(hit_rates.mean()) if len(hit_rates) else np.nan
    min_hit_rate = float(hit_rates.min()) if len(hit_rates) else np.nan

    pnl_per_trade = total_pnl / total_trades if total_trades else np.nan
    one_day_dependency = max_day_pnl / total_pnl if total_pnl > 0 else np.inf

    robust_pass = (
        total_pnl > 0
        and min_day_pnl > 0
        and total_trades >= 3
        and one_day_dependency <= 0.60
    )

    robust_score = (
        total_pnl
        + 2.0 * min_day_pnl
        + 5000.0 * (0 if np.isnan(min_hit_rate) else min_hit_rate)
        + 500.0 * (0 if np.isnan(mean_hit_rate) else mean_hit_rate)
        - 100000.0 * max(0.0, one_day_dependency - 0.50)
    )

    summary = {
        "candidate": spec["name"],
        "family": spec.get("family", spec["kind"]),
        "kind": spec["kind"],
        "note": spec.get("note", ""),
        **cfg,
        "days": int(day_df["day"].nunique()),
        "total_pnl": total_pnl,
        "mean_day_pnl": mean_day_pnl,
        "min_day_pnl": min_day_pnl,
        "max_day_pnl": max_day_pnl,
        "total_trades": total_trades,
        "mean_hit_rate": mean_hit_rate,
        "min_hit_rate": min_hit_rate,
        "pnl_per_trade": pnl_per_trade,
        "one_day_dependency": one_day_dependency,
        "robust_pass": robust_pass,
        "robust_score": robust_score,
    }

    return summary, day_df


def run_config(spec: dict, window, entry_z, exit_z, max_hold, gross, exit_mode):
    cfg = {
        "window": window,
        "entry_z": entry_z,
        "exit_z": exit_z,
        "exit_mode": exit_mode,
        "max_hold": max_hold,
        "gross": gross,
    }

    all_trades = []
    for day, mid_df in sorted(uv_by_day.items()):
        day_trades = strict_backtest_one_day(
            mid_df=mid_df,
            spec=spec,
            window=window,
            entry_z=entry_z,
            exit_z=exit_z,
            max_hold=max_hold,
            gross=gross,
            exit_mode=exit_mode,
            day=day,
        )
        all_trades.extend(day_trades)

    trades_df = pd.DataFrame(all_trades)
    summary, day_df = summarize_trades(trades_df, spec, cfg)

    return summary, day_df, trades_df


def run_grid(specs, windows, entry_zs, exit_zs_by_mode, max_holds, grosses, label="grid"):
    rows = []
    day_rows = []
    trade_rows = []

    configs = []
    for spec in specs:
        for window, entry_z, max_hold, gross, exit_mode in itertools.product(
            windows, entry_zs, max_holds, grosses, exit_zs_by_mode.keys()
        ):
            for exit_z in exit_zs_by_mode[exit_mode]:
                configs.append((spec, window, entry_z, exit_z, max_hold, gross, exit_mode))

    print(f"{label}: total configs = {len(configs)}")
    t0 = time.time()

    for k, (spec, window, entry_z, exit_z, max_hold, gross, exit_mode) in enumerate(configs, 1):
        if k == 1 or k % 250 == 0 or k == len(configs):
            elapsed = time.time() - t0
            print(
                f"[{elapsed:7.2f}s] {label} {k}/{len(configs)}: "
                f"{spec['name']}, w={window}, entry={entry_z}, exit={exit_z}, "
                f"mode={exit_mode}, hold={max_hold}, gross={gross}"
            )

        summary, day_df, trades_df = run_config(
            spec=spec,
            window=window,
            entry_z=entry_z,
            exit_z=exit_z,
            max_hold=max_hold,
            gross=gross,
            exit_mode=exit_mode,
        )

        rows.append(summary)
        day_rows.append(day_df)

        if not trades_df.empty:
            trade_rows.append(trades_df)

    summary_df = pd.DataFrame(rows).sort_values(
        ["robust_pass", "robust_score", "total_pnl"],
        ascending=[False, False, False],
    )

    day_breakdown_df = pd.concat(day_rows, ignore_index=True) if day_rows else pd.DataFrame()
    trades_all_df = pd.concat(trade_rows, ignore_index=True) if trade_rows else pd.DataFrame()

    return summary_df, day_breakdown_df, trades_all_df

In [16]:
LEAD_LAG_SPECS = [
    {
        "name": "lead_AMBER_to_RED_inverse_lag1000",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["AMBER"],
        "follower": COLOUR_TO_PRODUCT["RED"],
        "relation": "inverse",
        "lag": 1000,
        "note": "RED inversely follows AMBER return over lag 1000",
    },
    {
        "name": "lead_RED_to_YELLOW_inverse_lag250",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["RED"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "inverse",
        "lag": 250,
        "note": "YELLOW inversely follows RED return over lag 250",
    },
    {
        "name": "lead_RED_to_YELLOW_inverse_lag1000",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["RED"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "inverse",
        "lag": 1000,
        "note": "YELLOW inversely follows RED return over lag 1000",
    },
    {
        "name": "lead_YELLOW_to_RED_follow_lag1000",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["YELLOW"],
        "follower": COLOUR_TO_PRODUCT["RED"],
        "relation": "follow",
        "lag": 1000,
        "note": "RED follows YELLOW return over lag 1000",
    },
    {
        "name": "lead_AMBER_to_ORANGE_follow_lag50",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["AMBER"],
        "follower": COLOUR_TO_PRODUCT["ORANGE"],
        "relation": "follow",
        "lag": 50,
        "note": "ORANGE follows AMBER return over lag 50",
    },
    {
        "name": "lead_AMBER_to_ORANGE_follow_lag100",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["AMBER"],
        "follower": COLOUR_TO_PRODUCT["ORANGE"],
        "relation": "follow",
        "lag": 100,
        "note": "ORANGE follows AMBER return over lag 100",
    },
    {
        "name": "lead_ORANGE_to_YELLOW_follow_lag100",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["ORANGE"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "follow",
        "lag": 100,
        "note": "YELLOW follows ORANGE return over lag 100",
    },
    {
        "name": "lead_AMBER_to_YELLOW_inverse_lag100",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["AMBER"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "inverse",
        "lag": 100,
        "note": "YELLOW inversely follows AMBER return over lag 100",
    },
    {
        "name": "lead_MAGENTA_to_YELLOW_inverse_lag100",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["MAGENTA"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "inverse",
        "lag": 100,
        "note": "YELLOW inversely follows MAGENTA return over lag 100",
    },
    {
        "name": "lead_MAGENTA_to_YELLOW_follow_lag100",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["MAGENTA"],
        "follower": COLOUR_TO_PRODUCT["YELLOW"],
        "relation": "follow",
        "lag": 100,
        "note": "YELLOW follows MAGENTA return over lag 100",
    },
    {
        "name": "lead_AMBER_to_MAGENTA_inverse_lag50",
        "kind": "lead_lag",
        "family": "lead_lag",
        "leader": COLOUR_TO_PRODUCT["AMBER"],
        "follower": COLOUR_TO_PRODUCT["MAGENTA"],
        "relation": "inverse",
        "lag": 50,
        "note": "MAGENTA inversely follows AMBER return over lag 50",
    },
]


MIXING_SPECS = [
    {
        "name": "mix_RED_blend_YELLOW_MAGENTA_75_25_mr",
        "kind": "mix_mr",
        "family": "colour_mixing",
        "target": COLOUR_TO_PRODUCT["RED"],
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["MAGENTA"],
        "wa": 0.75,
        "note": "RED residual vs 75% YELLOW + 25% MAGENTA",
    },
    {
        "name": "mix_RED_blend_YELLOW_MAGENTA_50_50_mr",
        "kind": "mix_mr",
        "family": "colour_mixing",
        "target": COLOUR_TO_PRODUCT["RED"],
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["MAGENTA"],
        "wa": 0.50,
        "note": "RED residual vs 50% YELLOW + 50% MAGENTA",
    },
    {
        "name": "mix_ORANGE_blend_YELLOW_RED_50_50_mr",
        "kind": "mix_mr",
        "family": "colour_mixing",
        "target": COLOUR_TO_PRODUCT["ORANGE"],
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["RED"],
        "wa": 0.50,
        "note": "ORANGE residual vs 50% YELLOW + 50% RED",
    },
    {
        "name": "mix_AMBER_blend_YELLOW_ORANGE_50_50_mr",
        "kind": "mix_mr",
        "family": "colour_mixing",
        "target": COLOUR_TO_PRODUCT["AMBER"],
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["ORANGE"],
        "wa": 0.50,
        "note": "AMBER residual vs 50% YELLOW + 50% ORANGE",
    },
]


PAIRWISE_SPECS = [
    {
        "name": "YELLOW_vs_ORANGE_ratio_mr",
        "kind": "pair_ratio",
        "family": "pairwise",
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["ORANGE"],
        "note": "YELLOW / ORANGE ratio mean reversion",
    },
    {
        "name": "YELLOW_vs_ORANGE_spread_mr",
        "kind": "pair_spread",
        "family": "pairwise",
        "a": COLOUR_TO_PRODUCT["YELLOW"],
        "b": COLOUR_TO_PRODUCT["ORANGE"],
        "note": "YELLOW - ORANGE spread mean reversion",
    },
]

ALL_VALIDATION_SPECS = LEAD_LAG_SPECS + MIXING_SPECS + PAIRWISE_SPECS

In [17]:
best_spec = LEAD_LAG_SPECS[0]  # lead_AMBER_to_RED_inverse_lag1000

EXIT_VALIDATION_MODES = {
    "fixed_hold": [np.nan],
    "zero_cross": [0.0],
    "abs_band": [0.25, 0.50, 0.75, 1.00],
    "signal_flip": [np.nan],
}

exit_validation_summary, exit_validation_days, exit_validation_trades = run_grid(
    specs=[best_spec],
    windows=[500],
    entry_zs=[1.50],
    exit_zs_by_mode=EXIT_VALIDATION_MODES,
    max_holds=[2500],
    grosses=[80],
    label="exit_validation_best",
)

exit_validation_summary.to_csv(OUT_DIR / "exit_validation_best_summary.csv", index=False)
exit_validation_days.to_csv(OUT_DIR / "exit_validation_best_days.csv", index=False)
exit_validation_trades.to_csv(OUT_DIR / "exit_validation_best_trades.csv", index=False)

display(exit_validation_summary)
display(exit_validation_days.sort_values(["exit_mode", "exit_z", "day"]))
display(exit_validation_trades.sort_values(["exit_mode", "exit_z", "day", "entry_idx"]).head(100))

exit_validation_best: total configs = 7
[   0.00s] exit_validation_best 1/7: lead_AMBER_to_RED_inverse_lag1000, w=500, entry=1.5, exit=nan, mode=fixed_hold, hold=2500, gross=80
[   0.08s] exit_validation_best 7/7: lead_AMBER_to_RED_inverse_lag1000, w=500, entry=1.5, exit=nan, mode=signal_flip, hold=2500, gross=80

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
6,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,NaN,signal_flip,2500,80,3,272960.0,90986.666667,39080.0,163000.0,46,0.589169,0.529412,5933.913043,0.597157,True,344345.934063
0,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,NaN,fixed_hold,2500,80,3,255760.0,85253.333333,-17240.0,142160.0,12,0.666667,0.250000,21313.333333,0.555834,False,217279.973934
1,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,0.00,zero_cross,2500,80,3,138360.0,46120.000000,-16680.0,100240.0,69,0.508485,0.480000,2005.217391,0.724487,False,85205.557833
2,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,0.25,abs_band,2500,80,3,112960.0,37653.333333,-23160.0,83560.0,72,0.498328,0.478261,1568.888889,0.739731,False,45307.380409
5,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,1.00,abs_band,2500,80,3,91520.0,30506.666667,-17720.0,87720.0,128,0.557787,0.477273,715.000000,0.958479,False,12897.355277
4,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,0.75,abs_band,2500,80,3,75920.0,25306.666667,-21520.0,64640.0,104,0.528644,0.457143,730.000000,0.851423,False,287.781070
3,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,500,1.5,0.50,abs_band,2500,80,3,66880.0,22293.333333,-19800.0,57840.0,85,0.494679,0.448276,786.823529,0.864833,False,-6714.534985

,day,trade_count,day_pnl,hit_rate,avg_trade_pnl,median_trade_pnl,window,entry_z,exit_z,exit_mode,max_hold,gross,candidate,family,kind,note
6,2,23,52560.0,0.478261,2285.217391,-1280.0,500,1.5,0.25,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
7,3,23,-23160.0,0.478261,-1006.956522,-800.0,500,1.5,0.25,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
8,4,26,83560.0,0.538462,3213.846154,980.0,500,1.5,0.25,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
9,2,29,28840.0,0.448276,994.482759,-1440.0,500,1.5,0.50,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
10,3,27,-19800.0,0.518519,-733.333333,1760.0,500,1.5,0.50,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
11,4,29,57840.0,0.517241,1994.482759,320.0,500,1.5,0.50,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
12,2,35,32800.0,0.457143,937.142857,-1000.0,500,1.5,0.75,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
13,3,36,-21520.0,0.583333,-597.777778,1640.0,500,1.5,0.75,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
14,4,33,64640.0,0.545455,1958.787879,200.0,500,1.5,0.75,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
15,2,44,21520.0,0.477273,489.090909,-240.0,500,1.5,1.00,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
16,3,47,-17720.0,0.574468,-377.021277,880.0,500,1.5,1.00,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
17,4,37,87720.0,0.621622,2370.810811,1200.0,500,1.5,1.00,abs_band,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
0,2,4,-17240.0,0.250000,-4310.000000,-11720.0,500,1.5,NaN,fixed_hold,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
1,3,4,142160.0,0.750000,35540.000000,35840.0,500,1.5,NaN,fixed_hold,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
2,4,4,130840.0,1.000000,32710.000000,34360.0,500,1.5,NaN,fixed_hold,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
18,2,14,70880.0,0.571429,5062.857143,3060.0,500,1.5,NaN,signal_flip,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
19,3,15,39080.0,0.666667,2605.333333,3840.0,500,1.5,NaN,signal_flip,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
20,4,17,163000.0,0.529412,9588.235294,1440.0,500,1.5,NaN,signal_flip,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
3,2,22,54800.0,0.545455,2490.909091,1200.0,500,1.5,0.00,zero_cross,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
4,3,22,-16680.0,0.500000,-758.181818,380.0,500,1.5,0.00,zero_cross,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000
5,4,25,100240.0,0.480000,4009.600000,-1440.0,500,1.5,0.00,zero_cross,2500,80,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000

,candidate,family,kind,note,day,window,entry_z,exit_z,exit_mode,max_hold,gross,q_trade,net_position,gross_position,entry_idx,exit_idx,entry_ts,exit_ts,side,entry_z_seen,exit_z_seen,hold,exec_pnl,position
81,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.25,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,1840,1874,184000,187400,-1,2.020327,0.218677,34,6560.0,"[-0.0, -0.0, -0.0, -80.0, -0.0]"
82,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.25,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,1892,1906,189200,190600,-1,1.579071,0.186395,14,-1280.0,"[-0.0, -0.0, -0.0, -80.0, -0.0]"
83,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.25,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,1936,2045,193600,204500,1,-1.559829,-0.242369,109,8440.0,"[0.0, 0.0, 0.0, 80.0, 0.0]"
84,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.25,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,2117,2132,211700,213200,-1,1.506158,0.243850,15,-5840.0,"[-0.0, -0.0, -0.0, -80.0, -0.0]"
85,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.25,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,2178,2225,217800,222500,1,-1.728200,-0.210113,47,-6240.0,"[0.0, 0.0, 0.0, 80.0, 0.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.50,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,7377,7487,737700,748700,1,-1.857883,-0.482609,110,16360.0,"[0.0, 0.0, 0.0, 80.0, 0.0]"
177,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.50,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,7629,7651,762900,765100,1,-1.581905,-0.413650,22,2280.0,"[0.0, 0.0, 0.0, 80.0, 0.0]"
178,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.50,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,7715,7954,771500,795400,-1,1.738430,0.487093,239,3000.0,"[-0.0, -0.0, -0.0, -80.0, -0.0]"
179,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.50,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,8310,8692,831000,869200,-1,1.584429,0.425318,382,25120.0,"[-0.0, -0.0, -0.0, -80.0, -0.0]"
180,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,2,500,1.5,0.50,abs_band,2500,80,"[0.0, 0.0, 0.0, 80.0, 0.0]",80.0,80.0,9104,9679,910400,967900,1,-1.623823,-0.447552,575,20320.0,"[0.0, 0.0, 0.0, 80.0, 0.0]"

In [19]:
cols = [
    "candidate", "exit_mode", "exit_z", "max_hold",
    "total_pnl", "min_day_pnl", "max_day_pnl",
    "total_trades", "mean_hit_rate", "one_day_dependency",
    "robust_pass", "robust_score",
]

display(exit_validation_summary[cols].sort_values("robust_score", ascending=False))

                           candidate    exit_mode  exit_z  max_hold  total_pnl  min_day_pnl  max_day_pnl  total_trades  mean_hit_rate  one_day_dependency  robust_pass   robust_score
6  lead_AMBER_to_RED_inverse_lag1000  signal_flip     NaN      2500   272960.0      39080.0     163000.0            46       0.589169            0.597157         True  344345.934063
0  lead_AMBER_to_RED_inverse_lag1000   fixed_hold     NaN      2500   255760.0     -17240.0     142160.0            12       0.666667            0.555834        False  217279.973934
1  lead_AMBER_to_RED_inverse_lag1000   zero_cross    0.00      2500   138360.0     -16680.0     100240.0            69       0.508485            0.724487        False   85205.557833
2  lead_AMBER_to_RED_inverse_lag1000     abs_band    0.25      2500   112960.0     -23160.0      83560.0            72       0.498328            0.739731        False   45307.380409
5  lead_AMBER_to_RED_inverse_lag1000     abs_band    1.00      2500    91520.0     -17720.0      87720.0           128       0.557787            0.958479        False   12897.355277
4  lead_AMBER_to_RED_inverse_lag1000     abs_band    0.75      2500    75920.0     -21520.0      64640.0           104       0.528644            0.851423        False     287.781070
3  lead_AMBER_to_RED_inverse_lag1000     abs_band    0.50      2500    66880.0     -19800.0      57840.0            85       0.494679            0.864833        False   -6714.534985

In [20]:
DISCOVERED_TOP_CONFIGS = [
    # spec_name, window, entry_z, max_hold, gross
    ("lead_AMBER_to_RED_inverse_lag1000", 500, 1.50, 2500, 80),
    ("lead_RED_to_YELLOW_inverse_lag250", 500, 2.00, 1500, 80),
    ("lead_RED_to_YELLOW_inverse_lag1000", 500, 1.75, 1500, 80),
    ("lead_YELLOW_to_RED_follow_lag1000", 500, 1.25, 1000, 80),
    ("lead_AMBER_to_ORANGE_follow_lag50", 500, 1.50, 1500, 80),
    ("lead_AMBER_to_ORANGE_follow_lag100", 500, 1.25, 1500, 80),
    ("lead_ORANGE_to_YELLOW_follow_lag100", 1000, 1.75, 500, 80),
    ("lead_AMBER_to_YELLOW_inverse_lag100", 1000, 1.75, 1500, 80),
    ("lead_MAGENTA_to_YELLOW_inverse_lag100", 500, 2.25, 4000, 80),
    ("lead_MAGENTA_to_YELLOW_follow_lag100", 500, 1.50, 500, 80),
    ("lead_AMBER_to_MAGENTA_inverse_lag50", 1000, 2.00, 1000, 80),
]

spec_by_name = {s["name"]: s for s in ALL_VALIDATION_SPECS}

rows = []
day_rows = []
trade_rows = []

for spec_name, window, entry_z, max_hold, gross in DISCOVERED_TOP_CONFIGS:
    spec = spec_by_name[spec_name]
    for exit_mode, exit_zs in EXIT_VALIDATION_MODES.items():
        for exit_z in exit_zs:
            summary, days, trades = run_config(
                spec=spec,
                window=window,
                entry_z=entry_z,
                exit_z=exit_z,
                max_hold=max_hold,
                gross=gross,
                exit_mode=exit_mode,
            )
            rows.append(summary)
            day_rows.append(days)
            if not trades.empty:
                trade_rows.append(trades)

top_exit_compare_summary = pd.DataFrame(rows).sort_values(
    ["robust_pass", "robust_score", "total_pnl"],
    ascending=[False, False, False],
)

top_exit_compare_days = pd.concat(day_rows, ignore_index=True)
top_exit_compare_trades = pd.concat(trade_rows, ignore_index=True) if trade_rows else pd.DataFrame()

top_exit_compare_summary.to_csv(OUT_DIR / "top_exit_compare_summary.csv", index=False)
top_exit_compare_days.to_csv(OUT_DIR / "top_exit_compare_days.csv", index=False)
top_exit_compare_trades.to_csv(OUT_DIR / "top_exit_compare_trades.csv", index=False)

display(top_exit_compare_summary[cols].head(80))

                                candidate    exit_mode  exit_z  max_hold  total_pnl  min_day_pnl  max_day_pnl  total_trades  mean_hit_rate  one_day_dependency  robust_pass  robust_score
7       lead_RED_to_YELLOW_inverse_lag250   fixed_hold     NaN      1500   426960.0     105120.0     184160.0            18       0.888889            0.431328         True  6.418111e+05
63   lead_MAGENTA_to_YELLOW_follow_lag100   fixed_hold     NaN       500   370200.0     113280.0     138480.0            50       0.722222            0.374068         True  6.004544e+05
21      lead_YELLOW_to_RED_follow_lag1000   fixed_hold     NaN      1000   448840.0      68120.0     191040.0            27       0.851852            0.425631         True  5.893948e+05
76    lead_AMBER_to_MAGENTA_inverse_lag50  signal_flip     NaN      1000   382000.0      99920.0     150640.0            63       0.603319            0.394346         True  5.850962e+05
20     lead_RED_to_YELLOW_inverse_lag1000  signal_flip     NaN      1500   419800.0      78400.0     215320.0            37       0.604978            0.512911         True  5.777543e+05
42    lead_ORANGE_to_YELLOW_follow_lag100   fixed_hold     NaN       500   353760.0      91560.0     134560.0            42       0.669109            0.380371         True  5.400717e+05
35     lead_AMBER_to_ORANGE_follow_lag100   fixed_hold     NaN      1500   349960.0      90080.0     166640.0            21       0.666667            0.476169         True  5.333105e+05
56  lead_MAGENTA_to_YELLOW_inverse_lag100   fixed_hold     NaN      4000   356120.0      84160.0     169400.0             9       0.777778            0.475682         True  5.281622e+05
70    lead_AMBER_to_MAGENTA_inverse_lag50   fixed_hold     NaN      1000   361080.0      76760.0     155240.0            24       0.705688            0.429932         True  5.180778e+05
49    lead_AMBER_to_YELLOW_inverse_lag100   fixed_hold     NaN      1500   316080.0      95640.0     113720.0            16       0.744444            0.359782         True  5.107322e+05
28      lead_AMBER_to_ORANGE_follow_lag50   fixed_hold     NaN      1500   315000.0      85520.0     140000.0            21       0.761905            0.444444         True  4.892781e+05
26      lead_YELLOW_to_RED_follow_lag1000     abs_band    1.00      1000   303360.0      52360.0     146520.0           256       0.563031            0.482991         True  4.106871e+05
69   lead_MAGENTA_to_YELLOW_follow_lag100  signal_flip     NaN       500   282440.0      48640.0     151320.0           111       0.606047            0.535760         True  3.790228e+05
25      lead_YELLOW_to_RED_follow_lag1000     abs_band    0.75      1000   270440.0      40560.0     120120.0           151       0.627850            0.444165         True  3.546399e+05
24      lead_YELLOW_to_RED_follow_lag1000     abs_band    0.50      1000   281000.0      30520.0     127080.0           118       0.567270            0.452242         True  3.446209e+05
6       lead_AMBER_to_RED_inverse_lag1000  signal_flip     NaN      2500   272960.0      39080.0     163000.0            46       0.589169            0.597157         True  3.443459e+05
15     lead_RED_to_YELLOW_inverse_lag1000   zero_cross    0.00      1500   264160.0      30680.0     151800.0            56       0.655728            0.574652         True  3.212774e+05
23      lead_YELLOW_to_RED_follow_lag1000     abs_band    0.25      1000   278920.0       8760.0     136360.0            96       0.563539            0.488886         True  2.992218e+05
14     lead_RED_to_YELLOW_inverse_lag1000   fixed_hold     NaN      1500   256640.0      10160.0     133920.0            18       0.722222            0.521820         True  2.776391e+05
72    lead_AMBER_to_MAGENTA_inverse_lag50     abs_band    0.25      1000   165600.0      42920.0      71320.0           115       0.580961            0.430676         True  2.540278e+05
71    lead_AMBER_to_MAGENTA_inverse_lag50   zero_cross    0.00      1000   170320.0      40280.0      66480.0           112       0.570903            0.390324         True  2.539432e+05
73    lead_AMBER_to_MAGENTA_inverse_lag50     abs_band    0.50      1000    90360.0      26840.0      34280.0           117       0.554864            0.379371         True  1.466859e+05
74    lead_AMBER_to_MAGENTA_inverse_lag50     abs_band    0.75      1000    84240.0      10920.0      37880.0           118       0.547006            0.449668         True  1.085903e+05
10      lead_RED_to_YELLOW_inverse_lag250     abs_band    0.50      1500    26800.0       3960.0      15240.0            79       0.483315            0.568657         True  3.040368e+04
27      lead_YELLOW_to_RED_follow_lag1000  signal_flip     NaN      1000   353600.0      -4760.0     187600.0            49       0.706924            0.530543        False  3.442363e+05
18     lead_RED_to_YELLOW_inverse_lag1000     abs_band    0.75      1500   234320.0      29720.0     140640.0            80       0.599240            0.600205        False  2.862614e+05
13      lead_RED_to_YELLOW_inverse_lag250  signal_flip     NaN      1500   286280.0      -9680.0     163920.0            47       0.529167            0.572586        False  2.619260e+05
22      lead_YELLOW_to_RED_follow_lag1000   zero_cross    0.00      1000   284960.0     -12760.0     150000.0            76       0.600373            0.526390        False  2.594925e+05
0       lead_AMBER_to_RED_inverse_lag1000   fixed_hold     NaN      2500   255760.0     -17240.0     142160.0            12       0.666667            0.555834        False  2.172800e+05
16     lead_RED_to_YELLOW_inverse_lag1000     abs_band    0.25      1500   225320.0       4200.0     156520.0            61       0.640769            0.694656        False  2.167176e+05
17     lead_RED_to_YELLOW_inverse_lag1000     abs_band    0.50      1500   201320.0      -2760.0     153800.0            69       0.637736            0.763958        False  1.724314e+05
65   lead_MAGENTA_to_YELLOW_follow_lag100     abs_band    0.25       500   167800.0      -5320.0     127840.0           189       0.565591            0.761859        False  1.335069e+05
19     lead_RED_to_YELLOW_inverse_lag1000     abs_band    1.00      1500   152680.0      -4080.0     109120.0            93       0.545259            0.714697        False  1.255104e+05
50    lead_AMBER_to_YELLOW_inverse_lag100   zero_cross    0.00      1500   121000.0      -7560.0      78960.0            75       0.536580            0.652562        False  9.321352e+04
1       lead_AMBER_to_RED_inverse_lag1000   zero_cross    0.00      2500   138360.0     -16680.0     100240.0            69       0.508485            0.724487        False  8.520556e+04
66   lead_MAGENTA_to_YELLOW_follow_lag100     abs_band    0.50       500   101200.0      -2800.0      77960.0           211       0.498850            0.770356        False  7.071861e+04
64   lead_MAGENTA_to_YELLOW_follow_lag100   zero_cross    0.00       500   125600.0     -14240.0     112440.0           173       0.523324            0.895223        False  6.012352e+04
75    lead_AMBER_to_MAGENTA_inverse_lag50     abs_band    1.00      1000    59360.0       2160.0      36920.0           123       0.562599            0.621968        False  5.400138e+04
2       lead_AMBER_to_RED_inverse_lag1000     abs_band    0.25      2500   112960.0     -23160.0      83560.0            72       0.498328            0.739731        False  4.530738e+04
67   lead_MAGENTA_to_YELLOW_follow_lag100     abs_band    0.75       500    98000.0      -3080.0      99960.0           239       0.498469            1.020000        False  4.207554e+04
5       lead_AMBER_to_RED_inverse_lag1000     abs_band    1.00      2500    91520.0     -17720.0      87720.0           128       0.557787            0.958479        False  1.289736e+04
4       lead_AMBER_to_RED_inverse_lag1000     abs_band    0.75      2500    75920.0     -21520.0      64640.0           104       0.528644            0.851423        False  2.877811e+02
51    lead_AMBER_to_YELLOW_inverse_lag100     abs_band    0.25      1500    78600.0     -19640.0      71680.0            77       0.485857            0.911959        False  2.635515e+02
3       lead_AMBER_to_RED_inverse_lag1000     abs_band    0.50      2500    66880.0     -19800.0      57840.0            85       0.494679            0.864833        False -6.714535e+03
68   lead_MAGENTA_to_YELLOW_follow_lag100     abs_band    1.00       500    69240.0     -12960.0      76680.0           278       0.474743            1.107452        False -1.502877e+04
48    lead_ORANGE_to_YELLOW_follow_lag100  signal_flip     NaN       500    12480.0      -2280.0      11320.0            67       0.490000            0.907051        False -3.029013e+04
55    lead_AMBER_to_YELLOW_inverse_lag100  signal_flip     NaN      1500    81960.0     -64840.0      83800.0            51       0.574483            1.022450        False -9.773331e+04
34      lead_AMBER_to_ORANGE_follow_lag50  signal_flip     NaN      1500    36200.0     -53520.0      50200.0           152       0.498735            1.386740        False -1.568688e+05
52    lead_AMBER_to_YELLOW_inverse_lag100     abs_band    0.50      1500    56480.0     -55560.0      94120.0            83       0.552109            1.666431        False -1.690715e+05
53    lead_AMBER_to_YELLOW_inverse_lag100     abs_band    0.75      1500    43960.0     -56640.0      79840.0            88       0.518438            1.816197        False -1.987107e+05
54    lead_AMBER_to_YELLOW_inverse_lag100     abs_band    1.00      1500    29560.0     -50560.0      66400.0            96       0.542593            2.246279        False -2.441110e+05
11      lead_RED_to_YELLOW_inverse_lag250     abs_band    0.75      1500     8680.0     -34400.0      24200.0            89       0.467586            2.788018        False -2.866881e+05
9       lead_RED_to_YELLOW_inverse_lag250     abs_band    0.25      1500     3480.0     -30160.0      28480.0            73       0.464842            8.183908        False -8.228245e+05
8       lead_RED_to_YELLOW_inverse_lag250   zero_cross    0.00      1500     2520.0     -19680.0      24800.0            69       0.479964            9.841270        False -9.684543e+05
39     lead_AMBER_to_ORANGE_follow_lag100     abs_band    0.75      1500     7360.0     -80040.0      66680.0           273       0.505298            9.059783        False -1.006468e+06
29      lead_AMBER_to_ORANGE_follow_lag50   zero_cross    0.00      1500    -1000.0     -22480.0      32200.0           232       0.494179                 inf        False          -inf
12      lead_RED_to_YELLOW_inverse_lag250     abs_band    1.00      1500    -4600.0     -19160.0      15680.0            96       0.440030                 inf        False          -inf
40     lead_AMBER_to_ORANGE_follow_lag100     abs_band    1.00      1500    -4600.0     -70960.0      48400.0           386       0.496471                 inf        False          -inf
44    lead_ORANGE_to_YELLOW_follow_lag100     abs_band    0.25       500    -4960.0     -15640.0       6200.0            92       0.435911                 inf        False          -inf
41     lead_AMBER_to_ORANGE_follow_lag100  signal_flip     NaN      1500    -7240.0     -13080.0      10840.0           125       0.494651                 inf        False          -inf
32      lead_AMBER_to_ORANGE_follow_lag50     abs_band    0.75      1500   -10680.0     -36720.0      24760.0           297       0.528732                 inf        False          -inf
31      lead_AMBER_to_ORANGE_follow_lag50     abs_band    0.50      1500   -13760.0     -39840.0      34200.0           273       0.522767                 inf        False          -inf
47    lead_ORANGE_to_YELLOW_follow_lag100     abs_band    1.00       500   -14440.0     -11960.0       7520.0           111       0.458722                 inf        False          -inf
38     lead_AMBER_to_ORANGE_follow_lag100     abs_band    0.50      1500   -14520.0     -82440.0      45960.0           232       0.509404                 inf        False          -inf
30      lead_AMBER_to_ORANGE_follow_lag50     abs_band    0.25      1500   -15240.0     -36920.0      26320.0           251       0.514139                 inf        False          -inf
36     lead_AMBER_to_ORANGE_follow_lag100   zero_cross    0.00      1500   -16560.0     -67440.0      52720.0           185       0.474811                 inf        False          -inf
37     lead_AMBER_to_ORANGE_follow_lag100     abs_band    0.25      1500   -17880.0     -75280.0      57080.0           203       0.496599                 inf        False          -inf
45    lead_ORANGE_to_YELLOW_follow_lag100     abs_band    0.50       500   -36520.0     -22440.0      -5560.0            96       0.521159                 inf        False          -inf
33      lead_AMBER_to_ORANGE_follow_lag50     abs_band    1.00      1500   -40200.0     -24000.0       4600.0           340       0.499857                 inf        False          -inf
43    lead_ORANGE_to_YELLOW_follow_lag100   zero_cross    0.00       500   -47800.0     -30560.0       -120.0            89       0.475173                 inf        False          -inf
46    lead_ORANGE_to_YELLOW_follow_lag100     abs_band    0.75       500   -51080.0     -33400.0      -6240.0           103       0.465224                 inf        False          -inf
57  lead_MAGENTA_to_YELLOW_inverse_lag100   zero_cross    0.00      4000   -56120.0     -27320.0     -14040.0            77       0.410920                 inf        False          -inf
61  lead_MAGENTA_to_YELLOW_inverse_lag100     abs_band    1.00      4000   -59200.0     -23120.0     -14800.0            82       0.476049                 inf        False          -inf
60  lead_MAGENTA_to_YELLOW_inverse_lag100     abs_band    0.75      4000   -63120.0     -28920.0     -12760.0            80       0.526068                 inf        False          -inf
58  lead_MAGENTA_to_YELLOW_inverse_lag100     abs_band    0.25      4000   -90880.0     -38400.0     -15000.0            77       0.424808                 inf        False          -inf
59  lead_MAGENTA_to_YELLOW_inverse_lag100     abs_band    0.50      4000   -95920.0     -42840.0     -16400.0            80       0.512821                 inf        False          -inf
62  lead_MAGENTA_to_YELLOW_inverse_lag100  signal_flip     NaN      4000  -146680.0    -216360.0      48080.0            51       0.344298                 inf        False          -inf

In [21]:
pivot_exit = top_exit_compare_summary.pivot_table(
    index="candidate",
    columns=["exit_mode", "exit_z"],
    values="total_pnl",
    aggfunc="max",
)

display(pivot_exit)

exit_mode                              abs_band                               zero_cross
exit_z                                     0.25      0.50      0.75      1.00       0.00
candidate
lead_AMBER_to_MAGENTA_inverse_lag50    165600.0   90360.0   84240.0   59360.0   170320.0
lead_AMBER_to_ORANGE_follow_lag100     -17880.0  -14520.0    7360.0   -4600.0   -16560.0
lead_AMBER_to_ORANGE_follow_lag50      -15240.0  -13760.0  -10680.0  -40200.0    -1000.0
lead_AMBER_to_RED_inverse_lag1000      112960.0   66880.0   75920.0   91520.0   138360.0
lead_AMBER_to_YELLOW_inverse_lag100     78600.0   56480.0   43960.0   29560.0   121000.0
lead_MAGENTA_to_YELLOW_follow_lag100   167800.0  101200.0   98000.0   69240.0   125600.0
lead_MAGENTA_to_YELLOW_inverse_lag100  -90880.0  -95920.0  -63120.0  -59200.0   -56120.0
lead_ORANGE_to_YELLOW_follow_lag100     -4960.0  -36520.0  -51080.0  -14440.0   -47800.0
lead_RED_to_YELLOW_inverse_lag1000     225320.0  201320.0  234320.0  152680.0   264160.0
lead_RED_to_YELLOW_inverse_lag250        3480.0   26800.0    8680.0   -4600.0     2520.0
lead_YELLOW_to_RED_follow_lag1000      278920.0  281000.0  270440.0  303360.0   284960.0

In [22]:
FOCUSED_EXIT_MODES = {
    "fixed_hold": [np.nan],
    "abs_band": [0.25, 0.50, 0.75],
    "zero_cross": [0.0],
}

focused_summary, focused_days, focused_trades = run_grid(
    specs=LEAD_LAG_SPECS,
    windows=[250, 500, 750, 1000, 1500],
    entry_zs=[1.25, 1.50, 1.75, 2.00, 2.25],
    exit_zs_by_mode=FOCUSED_EXIT_MODES,
    max_holds=[500, 1000, 1500, 2500, 4000],
    grosses=[60, 72, 80],
    label="focused_lead_lag",
)

focused_summary.to_csv(OUT_DIR / "focused_lead_lag_summary.csv", index=False)
focused_days.to_csv(OUT_DIR / "focused_lead_lag_days.csv", index=False)
focused_trades.to_csv(OUT_DIR / "focused_lead_lag_trades.csv", index=False)

display(focused_summary.head(80))

focused_lead_lag: total configs = 20625
[   0.00s] focused_lead_lag 1/20625: lead_AMBER_to_RED_inverse_lag1000, w=250, entry=1.25, exit=nan, mode=fixed_hold, hold=500, gross=60
[   2.11s] focused_lead_lag 250/20625: lead_AMBER_to_RED_inverse_lag1000, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[   4.05s] focused_lead_lag 500/20625: lead_AMBER_to_RED_inverse_lag1000, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[   6.06s] focused_lead_lag 750/20625: lead_AMBER_to_RED_inverse_lag1000, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[   7.97s] focused_lead_lag 1000/20625: lead_AMBER_to_RED_inverse_lag1000, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[   9.83s] focused_lead_lag 1250/20625: lead_AMBER_to_RED_inverse_lag1000, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  11.74s] focused_lead_lag 1500/20625: lead_AMBER_to_RED_inverse_lag1000, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  13.77s] focused_lead_lag 1750/20625: lead_AMBER_to_RED_inverse_lag1000, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  16.07s] focused_lead_lag 2000/20625: lead_RED_to_YELLOW_inverse_lag250, w=250, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  18.39s] focused_lead_lag 2250/20625: lead_RED_to_YELLOW_inverse_lag250, w=250, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  20.65s] focused_lead_lag 2500/20625: lead_RED_to_YELLOW_inverse_lag250, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  22.95s] focused_lead_lag 2750/20625: lead_RED_to_YELLOW_inverse_lag250, w=750, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  25.36s] focused_lead_lag 3000/20625: lead_RED_to_YELLOW_inverse_lag250, w=750, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  27.58s] focused_lead_lag 3250/20625: lead_RED_to_YELLOW_inverse_lag250, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  30.00s] focused_lead_lag 3500/20625: lead_RED_to_YELLOW_inverse_lag250, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  33.36s] focused_lead_lag 3750/20625: lead_RED_to_YELLOW_inverse_lag250, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  35.58s] focused_lead_lag 4000/20625: lead_RED_to_YELLOW_inverse_lag1000, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  37.60s] focused_lead_lag 4250/20625: lead_RED_to_YELLOW_inverse_lag1000, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  39.59s] focused_lead_lag 4500/20625: lead_RED_to_YELLOW_inverse_lag1000, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  41.50s] focused_lead_lag 4750/20625: lead_RED_to_YELLOW_inverse_lag1000, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  43.39s] focused_lead_lag 5000/20625: lead_RED_to_YELLOW_inverse_lag1000, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  45.44s] focused_lead_lag 5250/20625: lead_RED_to_YELLOW_inverse_lag1000, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  47.29s] focused_lead_lag 5500/20625: lead_RED_to_YELLOW_inverse_lag1000, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  49.40s] focused_lead_lag 5750/20625: lead_YELLOW_to_RED_follow_lag1000, w=250, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  51.55s] focused_lead_lag 6000/20625: lead_YELLOW_to_RED_follow_lag1000, w=250, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  53.26s] focused_lead_lag 6250/20625: lead_YELLOW_to_RED_follow_lag1000, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  69.25s] focused_lead_lag 6500/20625: lead_YELLOW_to_RED_follow_lag1000, w=750, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  71.21s] focused_lead_lag 6750/20625: lead_YELLOW_to_RED_follow_lag1000, w=750, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  73.27s] focused_lead_lag 7000/20625: lead_YELLOW_to_RED_follow_lag1000, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  75.25s] focused_lead_lag 7250/20625: lead_YELLOW_to_RED_follow_lag1000, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  77.25s] focused_lead_lag 7500/20625: lead_YELLOW_to_RED_follow_lag1000, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  80.11s] focused_lead_lag 7750/20625: lead_AMBER_to_ORANGE_follow_lag50, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  83.05s] focused_lead_lag 8000/20625: lead_AMBER_to_ORANGE_follow_lag50, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  86.77s] focused_lead_lag 8250/20625: lead_AMBER_to_ORANGE_follow_lag50, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  89.61s] focused_lead_lag 8500/20625: lead_AMBER_to_ORANGE_follow_lag50, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[  92.60s] focused_lead_lag 8750/20625: lead_AMBER_to_ORANGE_follow_lag50, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[  95.40s] focused_lead_lag 9000/20625: lead_AMBER_to_ORANGE_follow_lag50, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  98.00s] focused_lead_lag 9250/20625: lead_AMBER_to_ORANGE_follow_lag50, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 100.60s] focused_lead_lag 9500/20625: lead_AMBER_to_ORANGE_follow_lag100, w=250, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 103.43s] focused_lead_lag 9750/20625: lead_AMBER_to_ORANGE_follow_lag100, w=250, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 106.14s] focused_lead_lag 10000/20625: lead_AMBER_to_ORANGE_follow_lag100, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 108.84s] focused_lead_lag 10250/20625: lead_AMBER_to_ORANGE_follow_lag100, w=750, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 111.51s] focused_lead_lag 10500/20625: lead_AMBER_to_ORANGE_follow_lag100, w=750, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 114.00s] focused_lead_lag 10750/20625: lead_AMBER_to_ORANGE_follow_lag100, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 116.48s] focused_lead_lag 11000/20625: lead_AMBER_to_ORANGE_follow_lag100, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 119.07s] focused_lead_lag 11250/20625: lead_AMBER_to_ORANGE_follow_lag100, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 121.56s] focused_lead_lag 11500/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 124.09s] focused_lead_lag 11750/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 126.73s] focused_lead_lag 12000/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 129.16s] focused_lead_lag 12250/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 131.66s] focused_lead_lag 12500/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 134.29s] focused_lead_lag 12750/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 136.63s] focused_lead_lag 13000/20625: lead_ORANGE_to_YELLOW_follow_lag100, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 139.12s] focused_lead_lag 13250/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=250, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 141.68s] focused_lead_lag 13500/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=250, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 144.11s] focused_lead_lag 13750/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 146.66s] focused_lead_lag 14000/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=750, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 149.32s] focused_lead_lag 14250/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=750, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 151.75s] focused_lead_lag 14500/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 154.22s] focused_lead_lag 14750/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 156.75s] focused_lead_lag 15000/20625: lead_AMBER_to_YELLOW_inverse_lag100, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 159.31s] focused_lead_lag 15250/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 163.16s] focused_lead_lag 15500/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 165.82s] focused_lead_lag 15750/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 168.32s] focused_lead_lag 16000/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 170.83s] focused_lead_lag 16250/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 173.39s] focused_lead_lag 16500/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 175.88s] focused_lead_lag 16750/20625: lead_MAGENTA_to_YELLOW_inverse_lag100, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 178.47s] focused_lead_lag 17000/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=250, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 181.16s] focused_lead_lag 17250/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=250, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 191.84s] focused_lead_lag 17500/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 194.78s] focused_lead_lag 17750/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=750, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 197.54s] focused_lead_lag 18000/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=750, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 200.06s] focused_lead_lag 18250/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 202.59s] focused_lead_lag 18500/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 205.13s] focused_lead_lag 18750/20625: lead_MAGENTA_to_YELLOW_follow_lag100, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 207.95s] focused_lead_lag 19000/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=250, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 210.84s] focused_lead_lag 19250/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 213.71s] focused_lead_lag 19500/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 216.45s] focused_lead_lag 19750/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=750, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 219.24s] focused_lead_lag 20000/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=60
[ 222.02s] focused_lead_lag 20250/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[ 224.73s] focused_lead_lag 20500/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=72
[ 226.11s] focused_lead_lag 20625/20625: lead_AMBER_to_MAGENTA_inverse_lag50, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
2590,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,80,3,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.800000,26084.705882,0.371550,True,692171.111111
2515,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,80,3,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
2585,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,72,3,399096.0,133032.000000,109944.0,148284.0,17,0.822222,0.800000,23476.235294,0.371550,True,623395.111111
4195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,80,3,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
2620,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,80,3,411920.0,137306.666667,92840.0,167120.0,9,0.888889,0.666667,45768.888889,0.405710,True,601377.777778
17335,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,80,3,370200.0,123400.000000,113280.0,138480.0,50,0.722222,0.666667,7404.000000,0.374068,True,600454.444444
18910,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,80,3,386680.0,128893.333333,105000.0,160760.0,54,0.597007,0.500000,7160.740741,0.415744,True,599478.503612
9970,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,80,3,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
6025,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,80,3,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
1180,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,80,3,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
4270,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,80,3,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
5264,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,80,3,391080.0,130360.000000,95880.0,193280.0,42,0.617827,0.571429,9311.428571,0.494221,True,586006.056166
4885,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,80,3,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
4886,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,500,80,3,426360.0,142120.000000,75720.0,220400.0,66,0.702648,0.631579,6460.000000,0.516934,True,579615.813866
2510,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,72,3,384264.0,128088.000000,94608.0,165744.0,18,0.888889,0.833333,21348.000000,0.431328,True,578091.111111
4754,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,80,3,361360.0,120453.333333,104480.0,138680.0,34,0.717236,0.555556,10628.235294,0.383772,True,573456.396011
5066,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,2500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5096,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,4000,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
4769,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4784,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,2500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4799,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,4000,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
5051,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1000,80,3,368720.0,122906.666667,95920.0,172040.0,41,0.754762,0.714286,8993.170732,0.466587,True,564508.809524
4390,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,80,3,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
5261,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,abs_band,500,80,3,374400.0,124800.000000,90160.0,188600.0,45,0.625397,0.500000,8320.000000,0.503739,True,557158.766789
3070,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,80,3,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556
4991,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5006,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,2500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5021,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,4000,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
4901,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1000,80,3,397400.0,132466.666667,74600.0,208760.0,58,0.694752,0.611111,6851.724138,0.525315,True,547471.477250
4190,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,72,3,347724.0,115908.000000,97596.0,125568.0,8,0.888889,0.666667,43465.500000,0.361114,True,546693.777778
4976,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1000,80,3,375720.0,125240.000000,83880.0,191200.0,44,0.651709,0.538462,8539.090909,0.508890,True,545609.202529
4916,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4931,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,2500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4946,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,4000,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
2615,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,72,3,370728.0,123576.000000,83556.0,150408.0,9,0.888889,0.666667,41192.000000,0.405710,True,541617.777778
17330,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,72,3,333180.0,111060.000000,101952.0,124632.0,50,0.722222,0.666667,6663.600000,0.374068,True,540778.444444
12535,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1000,1.75,NaN,fixed_hold,500,80,3,353760.0,117920.000000,91560.0,134560.0,42,0.669109,0.571429,8422.857143,0.380371,True,540071.697192
18905,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,72,3,348012.0,116004.000000,94500.0,144684.0,54,0.597007,0.500000,6444.666667,0.415744,True,539810.503612
4889,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,500,80,3,401360.0,133786.666667,71320.0,229400.0,58,0.612979,0.500000,6920.000000,0.571557,True,539650.818543
19360,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,500,2.00,NaN,fixed_hold,500,80,3,356760.0,118920.000000,87320.0,166760.0,48,0.708333,0.437500,7432.500000,0.467429,True,533941.666667
9790,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.25,NaN,fixed_hold,1500,80,3,349960.0,116653.333333,90080.0,166640.0,21,0.666667,0.571429,16664.761905,0.476169,True,533310.476190
9965,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,72,3,394452.0,131484.000000,66780.0,192672.0,9,0.888889,0.666667,43828.000000,0.488455,True,531789.777778
6020,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,72,3,403956.0,134652.000000,61308.0,171936.0,27,0.851852,0.777778,14961.333333,0.425631,True,530886.814815
1175,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,72,3,333252.0,111084.000000,96624.0,126756.0,11,0.805556,0.666667,30295.636364,0.380361,True,530236.111111
6100,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.50,NaN,fixed_hold,1000,80,3,411360.0,137120.000000,57240.0,192680.0,26,0.773148,0.666667,15821.538462,0.468398,True,529559.907407
4265,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,72,3,343332.0,114444.000000,91836.0,125928.0,8,0.777778,0.333333,42916.500000,0.366782,True,529059.555556
15745,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,lead_lag,YELLOW inversely follows MAGENTA return over l...,500,2.25,NaN,fixed_hold,4000,80,3,356120.0,118706.666667,84160.0,169400.0,9,0.777778,0.666667,39568.888889,0.475682,True,528162.222222
5259,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,72,3,351972.0,117324.000000,86292.0,173952.0,42,0.617827,0.571429,8380.285714,0.494221,True,527722.056166
4679,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,1000,80,3,341640.0,113880.000000,91320.0,132080.0,41,0.703297,0.538462,8332.682927,0.386606,True,527323.956044
4880,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,72,3,367632.0,122544.000000,80640.0,201996.0,42,0.633333,0.500000,8753.142857,0.549452,True,526783.504113
12460,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1000,1.50,NaN,fixed_hold,500,80,3,358360.0,119453.333333,81640.0,145360.0,47,0.661111,0.625000,7624.680851,0.405626,True,525095.555556
5262,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.50,abs_band,500,80,3,349520.0,116506.666667,84920.0,173760.0,51,0.645085,0.555556,6853.333333,0.497139,True,522460.320245
4881,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,500,72,3,383724.0,127908.000000,68148.0,198360.0,66,0.702648,0.631579,5814.000000,0.516934,True,521835.813866
2580,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,60,3,332580.0,110860.000000,91620.0,123570.0,17,0.822222,0.800000,19563.529412,0.371550,True,520231.111111
20125,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,1000,2.00,NaN,fixed_hold,1000,80,3,361080.0,120360.000000,76760.0,155240.0,24,0.705688,0.625000,15045.000000,0.429932,True,518077.843915
4694,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,1500,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
4709,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,2500,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
4724,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,4000,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
4749,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,72,3,325224.0,108408.000000,94032.0,124812.0,34,0.717236,0.555556,9565.411765,0.383772,True,516424.396011
5061,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1500,72,3,333900.0,111300.000000,88380.0,154836.0,41,0.754762,0.714286,8143.902439,0.463720,True,514608.809524
5076,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,2500,72,3,333900.0,111300.000000,88380.0,154836.0,41,0.754762,0.714286,8143.902439,0.463720,True,514608.809524
5091,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,4000,72,3,333900.0,111300.000000,88380.0,154836.0,41,0.754762,0.714286,8143.902439,0.463720,True,514608.809524
14440,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,lead_lag,YELLOW inversely follows AMBER return over lag...,1000,1.75,NaN,fixed_hold,1500,80,3,316080.0,105360.000000,95640.0,113720.0,16,0.744444,0.600000,19755.000000,0.359782,True,510732.222222
4764,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1500,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
4779,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,2500,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
4794,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,4000,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
8170,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,lead_lag,ORANGE follows AMBER return over lag 50,500,2.00,NaN,fixed_hold,4000,80,3,373400.0,124466.666667,66160.0,154840.0,9,0.777778,0.666667,41488.888889,0.414676,True,509442.222222
3040,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,1500,80,3,359720.0,119906.666667,73000.0,152000.0,18,0.777778,0.666667,19984.444444,0.422551,True,509442.222222
19000,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,2.00,NaN,fixed_hold,1000,80,3,331480.0,110493.333333,87160.0,141960.0,28,0.755556,0.600000,11838.571429,0.428261,True,509177.777778
5046,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1000,72,3,331848.0,110616.000000,86328.0,154836.0,41,0.754762,0.714286,8093.853659,0.466587,True,508452.809524
13045,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1500,2.00,NaN,fixed_hold,4000,80,3,305200.0,101733.333333,98760.0,103840.0,6,1.000000,1.000000,50866.666667,0.340236,True,508220.000000
10690,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,1000,1.75,NaN,fixed_hold,1500,80,3,351400.0,117133.333333,76640.0,178920.0,16,0.811111,0.800000,21962.500000,0.509163,True,508169.220894
4385,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,72,3,326016.0,108672.000000,89208.0,129204.0,17,0.766667,0.666667,19177.411765,0.396312,True,508148.666667
4514,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.25,0.00,zero_cross,500,80,3,342440.0,114146.666667,79080.0,150560.0,71,0.596154,0.538462,4823.098592,0.439668,True,503590.384615
4829,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.25,0.00,zero_cross,1000,80,3,318880.0,106293.333333,90680.0,129560.0,31,0.730640,0.555556,10286.451613,0.406297,True,503383.097643
4961,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,500,80,3,362160.0,120720.000000,71840.0,205800.0,50,0.655338,0.588235,7243.200000,0.568257,True,502283.132924
5256,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,abs_band,500,72,3,336960.0,112320.000000,81144.0,169740.0,45,0.625397,0.500000,7488.000000,0.503739,True,501686.766789
3065,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,72,3,319428.0,106476.000000,89928.0,138924.0,9,0.777778,0.333333,35492.000000,0.434915,True,501339.555556
5339,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.50,0.00,zero_cross,500,80,3,332960.0,110986.666667,81440.0,140560.0,37,0.645299,0.500000,8998.918919,0.422153,True,498662.649573

In [23]:
display(
    focused_summary.sort_values(
        ["robust_pass", "robust_score", "min_day_pnl", "total_pnl"],
        ascending=[False, False, False, False],
    ).head(50)
)

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
2590,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,80,3,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.800000,26084.705882,0.371550,True,692171.111111
2515,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,80,3,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
2585,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,72,3,399096.0,133032.000000,109944.0,148284.0,17,0.822222,0.800000,23476.235294,0.371550,True,623395.111111
4195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,80,3,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
2620,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,80,3,411920.0,137306.666667,92840.0,167120.0,9,0.888889,0.666667,45768.888889,0.405710,True,601377.777778
17335,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,80,3,370200.0,123400.000000,113280.0,138480.0,50,0.722222,0.666667,7404.000000,0.374068,True,600454.444444
18910,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,80,3,386680.0,128893.333333,105000.0,160760.0,54,0.597007,0.500000,7160.740741,0.415744,True,599478.503612
9970,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,80,3,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
6025,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,80,3,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
1180,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,80,3,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
4270,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,80,3,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
5264,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,80,3,391080.0,130360.000000,95880.0,193280.0,42,0.617827,0.571429,9311.428571,0.494221,True,586006.056166
4885,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,80,3,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
4886,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,500,80,3,426360.0,142120.000000,75720.0,220400.0,66,0.702648,0.631579,6460.000000,0.516934,True,579615.813866
2510,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,72,3,384264.0,128088.000000,94608.0,165744.0,18,0.888889,0.833333,21348.000000,0.431328,True,578091.111111
4754,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,80,3,361360.0,120453.333333,104480.0,138680.0,34,0.717236,0.555556,10628.235294,0.383772,True,573456.396011
5066,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,2500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5096,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,4000,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
4769,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4784,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,2500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4799,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,4000,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
5051,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1000,80,3,368720.0,122906.666667,95920.0,172040.0,41,0.754762,0.714286,8993.170732,0.466587,True,564508.809524
4390,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,80,3,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
5261,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,abs_band,500,80,3,374400.0,124800.000000,90160.0,188600.0,45,0.625397,0.500000,8320.000000,0.503739,True,557158.766789
3070,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,80,3,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556
4991,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5006,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,2500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5021,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,4000,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
4901,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1000,80,3,397400.0,132466.666667,74600.0,208760.0,58,0.694752,0.611111,6851.724138,0.525315,True,547471.477250
4190,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,72,3,347724.0,115908.000000,97596.0,125568.0,8,0.888889,0.666667,43465.500000,0.361114,True,546693.777778
4976,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1000,80,3,375720.0,125240.000000,83880.0,191200.0,44,0.651709,0.538462,8539.090909,0.508890,True,545609.202529
4916,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4931,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,2500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4946,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,4000,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
2615,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,72,3,370728.0,123576.000000,83556.0,150408.0,9,0.888889,0.666667,41192.000000,0.405710,True,541617.777778
17330,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,72,3,333180.0,111060.000000,101952.0,124632.0,50,0.722222,0.666667,6663.600000,0.374068,True,540778.444444
12535,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1000,1.75,NaN,fixed_hold,500,80,3,353760.0,117920.000000,91560.0,134560.0,42,0.669109,0.571429,8422.857143,0.380371,True,540071.697192
18905,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,72,3,348012.0,116004.000000,94500.0,144684.0,54,0.597007,0.500000,6444.666667,0.415744,True,539810.503612
4889,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,500,80,3,401360.0,133786.666667,71320.0,229400.0,58,0.612979,0.500000,6920.000000,0.571557,True,539650.818543
19360,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,500,2.00,NaN,fixed_hold,500,80,3,356760.0,118920.000000,87320.0,166760.0,48,0.708333,0.437500,7432.500000,0.467429,True,533941.666667
9790,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.25,NaN,fixed_hold,1500,80,3,349960.0,116653.333333,90080.0,166640.0,21,0.666667,0.571429,16664.761905,0.476169,True,533310.476190
9965,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,72,3,394452.0,131484.000000,66780.0,192672.0,9,0.888889,0.666667,43828.000000,0.488455,True,531789.777778
6020,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,72,3,403956.0,134652.000000,61308.0,171936.0,27,0.851852,0.777778,14961.333333,0.425631,True,530886.814815
1175,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,72,3,333252.0,111084.000000,96624.0,126756.0,11,0.805556,0.666667,30295.636364,0.380361,True,530236.111111
6100,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.50,NaN,fixed_hold,1000,80,3,411360.0,137120.000000,57240.0,192680.0,26,0.773148,0.666667,15821.538462,0.468398,True,529559.907407
4265,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,72,3,343332.0,114444.000000,91836.0,125928.0,8,0.777778,0.333333,42916.500000,0.366782,True,529059.555556
15745,lead_MAGENTA_to_YELLOW_inverse_lag100,lead_lag,lead_lag,YELLOW inversely follows MAGENTA return over l...,500,2.25,NaN,fixed_hold,4000,80,3,356120.0,118706.666667,84160.0,169400.0,9,0.777778,0.666667,39568.888889,0.475682,True,528162.222222
5259,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,72,3,351972.0,117324.000000,86292.0,173952.0,42,0.617827,0.571429,8380.285714,0.494221,True,527722.056166
4679,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,1000,80,3,341640.0,113880.000000,91320.0,132080.0,41,0.703297,0.538462,8332.682927,0.386606,True,527323.956044

In [24]:
display(
    focused_summary.sort_values(
        ["total_pnl", "min_day_pnl"],
        ascending=[False, False],
    ).head(50)
)

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
6025,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,80,3,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
2590,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,80,3,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.800000,26084.705882,0.371550,True,692171.111111
9970,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,80,3,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
2515,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,80,3,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
4886,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,500,80,3,426360.0,142120.000000,75720.0,220400.0,66,0.702648,0.631579,6460.000000,0.516934,True,579615.813866
2620,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,80,3,411920.0,137306.666667,92840.0,167120.0,9,0.888889,0.666667,45768.888889,0.405710,True,601377.777778
6100,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.50,NaN,fixed_hold,1000,80,3,411360.0,137120.000000,57240.0,192680.0,26,0.773148,0.666667,15821.538462,0.468398,True,529559.907407
4885,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,80,3,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
6020,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,72,3,403956.0,134652.000000,61308.0,171936.0,27,0.851852,0.777778,14961.333333,0.425631,True,530886.814815
4889,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,500,80,3,401360.0,133786.666667,71320.0,229400.0,58,0.612979,0.500000,6920.000000,0.571557,True,539650.818543
2585,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,72,3,399096.0,133032.000000,109944.0,148284.0,17,0.822222,0.800000,23476.235294,0.371550,True,623395.111111
4901,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1000,80,3,397400.0,132466.666667,74600.0,208760.0,58,0.694752,0.611111,6851.724138,0.525315,True,547471.477250
4916,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,1500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4931,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,2500,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
4946,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,4000,80,3,395920.0,131973.333333,73120.0,208760.0,57,0.687127,0.588235,6945.964912,0.527278,True,542716.916180
9965,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,72,3,394452.0,131484.000000,66780.0,192672.0,9,0.888889,0.666667,43828.000000,0.488455,True,531789.777778
5260,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,NaN,fixed_hold,500,80,3,393280.0,131093.333333,62600.0,242600.0,36,0.604118,0.363636,10924.444444,0.616863,False,508913.910520
5264,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,80,3,391080.0,130360.000000,95880.0,193280.0,42,0.617827,0.571429,9311.428571,0.494221,True,586006.056166
18910,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,80,3,386680.0,128893.333333,105000.0,160760.0,54,0.597007,0.500000,7160.740741,0.415744,True,599478.503612
4195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,80,3,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
8020,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,lead_lag,ORANGE follows AMBER return over lag 50,500,1.50,NaN,fixed_hold,4000,80,3,384920.0,128306.666667,-4840.0,243080.0,9,0.666667,0.333333,42768.888889,0.631508,False,364089.215421
2510,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,72,3,384264.0,128088.000000,94608.0,165744.0,18,0.888889,0.833333,21348.000000,0.431328,True,578091.111111
4881,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.25,abs_band,500,72,3,383724.0,127908.000000,68148.0,198360.0,66,0.702648,0.631579,5814.000000,0.516934,True,521835.813866
4270,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,80,3,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
4991,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5006,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,2500,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
5021,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,4000,80,3,377680.0,125893.333333,85840.0,191200.0,44,0.651709,0.538462,8583.636364,0.506249,True,551753.294780
4135,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,500,80,3,377120.0,125706.666667,48400.0,168360.0,48,0.645833,0.437500,7856.666667,0.446436,True,476430.416667
4976,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,1000,80,3,375720.0,125240.000000,83880.0,191200.0,44,0.651709,0.538462,8539.090909,0.508890,True,545609.202529
5261,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,abs_band,500,80,3,374400.0,124800.000000,90160.0,188600.0,45,0.625397,0.500000,8320.000000,0.503739,True,557158.766789
8170,lead_AMBER_to_ORANGE_follow_lag50,lead_lag,lead_lag,ORANGE follows AMBER return over lag 50,500,2.00,NaN,fixed_hold,4000,80,3,373400.0,124466.666667,66160.0,154840.0,9,0.777778,0.666667,41488.888889,0.414676,True,509442.222222
5066,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,2500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5096,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,4000,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
2615,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,72,3,370728.0,123576.000000,83556.0,150408.0,9,0.888889,0.666667,41192.000000,0.405710,True,541617.777778
1180,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,80,3,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
6095,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.50,NaN,fixed_hold,1000,72,3,370224.0,123408.000000,51516.0,173412.0,26,0.773148,0.666667,14239.384615,0.468398,True,476975.907407
17335,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,80,3,370200.0,123400.000000,113280.0,138480.0,50,0.722222,0.666667,7404.000000,0.374068,True,600454.444444
5051,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1000,80,3,368720.0,122906.666667,95920.0,172040.0,41,0.754762,0.714286,8993.170732,0.466587,True,564508.809524
4880,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,72,3,367632.0,122544.000000,80640.0,201996.0,42,0.633333,0.500000,8753.142857,0.549452,True,526783.504113
4919,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,1500,80,3,364880.0,121626.666667,69880.0,215440.0,48,0.585380,0.466667,7601.666667,0.590441,True,498221.954109
4934,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,2500,80,3,364880.0,121626.666667,69880.0,215440.0,48,0.585380,0.466667,7601.666667,0.590441,True,498221.954109
4949,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,4000,80,3,364880.0,121626.666667,69880.0,215440.0,48,0.585380,0.466667,7601.666667,0.590441,True,498221.954109
4390,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,80,3,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
4961,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.50,0.25,abs_band,500,80,3,362160.0,120720.000000,71840.0,205800.0,50,0.655338,0.588235,7243.200000,0.568257,True,502283.132924
4754,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,80,3,361360.0,120453.333333,104480.0,138680.0,34,0.717236,0.555556,10628.235294,0.383772,True,573456.396011
4884,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,0.00,zero_cross,500,72,3,361224.0,120408.000000,64188.0,206460.0,58,0.612979,0.500000,6228.000000,0.571557,True,485250.818543
20125,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,1000,2.00,NaN,fixed_hold,1000,80,3,361080.0,120360.000000,76760.0,155240.0,24,0.705688,0.625000,15045.000000,0.429932,True,518077.843915
3040,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,1500,80,3,359720.0,119906.666667,73000.0,152000.0,18,0.777778,0.666667,19984.444444,0.422551,True,509442.222222
5279,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,1000,80,3,359640.0,119880.000000,61280.0,184240.0,36,0.611694,0.583333,9990.000000,0.512290,True,484193.506813

In [25]:
display(
    focused_summary.sort_values(
        ["min_day_pnl", "total_pnl"],
        ascending=[False, False],
    ).head(50)
)

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
2590,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,80,3,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.800000,26084.705882,0.371550,True,692171.111111
17335,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,80,3,370200.0,123400.000000,113280.0,138480.0,50,0.722222,0.666667,7404.000000,0.374068,True,600454.444444
2585,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,72,3,399096.0,133032.000000,109944.0,148284.0,17,0.822222,0.800000,23476.235294,0.371550,True,623395.111111
4195,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,80,3,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
1180,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,80,3,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
2515,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,80,3,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
18910,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,80,3,386680.0,128893.333333,105000.0,160760.0,54,0.597007,0.500000,7160.740741,0.415744,True,599478.503612
4754,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,80,3,361360.0,120453.333333,104480.0,138680.0,34,0.717236,0.555556,10628.235294,0.383772,True,573456.396011
4769,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4784,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,2500,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4799,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,4000,80,3,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
4270,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,80,3,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
17330,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,NaN,fixed_hold,500,72,3,333180.0,111060.000000,101952.0,124632.0,50,0.722222,0.666667,6663.600000,0.374068,True,540778.444444
3070,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,80,3,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556
4390,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,80,3,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
13045,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1500,2.00,NaN,fixed_hold,4000,80,3,305200.0,101733.333333,98760.0,103840.0,6,1.000000,1.000000,50866.666667,0.340236,True,508220.000000
5066,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5081,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,2500,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
5096,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,4000,80,3,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
4190,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,72,3,347724.0,115908.000000,97596.0,125568.0,8,0.888889,0.666667,43465.500000,0.361114,True,546693.777778
1175,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,72,3,333252.0,111084.000000,96624.0,126756.0,11,0.805556,0.666667,30295.636364,0.380361,True,530236.111111
5051,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,0.25,abs_band,1000,80,3,368720.0,122906.666667,95920.0,172040.0,41,0.754762,0.714286,8993.170732,0.466587,True,564508.809524
5264,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.00,zero_cross,500,80,3,391080.0,130360.000000,95880.0,193280.0,42,0.617827,0.571429,9311.428571,0.494221,True,586006.056166
14440,lead_AMBER_to_YELLOW_inverse_lag100,lead_lag,lead_lag,YELLOW inversely follows AMBER return over lag...,1000,1.75,NaN,fixed_hold,1500,80,3,316080.0,105360.000000,95640.0,113720.0,16,0.744444,0.600000,19755.000000,0.359782,True,510732.222222
2510,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,72,3,384264.0,128088.000000,94608.0,165744.0,18,0.888889,0.833333,21348.000000,0.431328,True,578091.111111
18905,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,NaN,fixed_hold,500,72,3,348012.0,116004.000000,94500.0,144684.0,54,0.597007,0.500000,6444.666667,0.415744,True,539810.503612
4749,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1000,72,3,325224.0,108408.000000,94032.0,124812.0,34,0.717236,0.555556,9565.411765,0.383772,True,516424.396011
4764,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,1500,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
4779,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,2500,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
4794,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,0.00,zero_cross,4000,72,3,318528.0,106176.000000,94032.0,124812.0,34,0.717236,0.555556,9368.470588,0.391840,True,509728.396011
2620,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,4000,80,3,411920.0,137306.666667,92840.0,167120.0,9,0.888889,0.666667,45768.888889,0.405710,True,601377.777778
4265,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,72,3,343332.0,114444.000000,91836.0,125928.0,8,0.777778,0.333333,42916.500000,0.366782,True,529059.555556
2580,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,60,3,332580.0,110860.000000,91620.0,123570.0,17,0.822222,0.800000,19563.529412,0.371550,True,520231.111111
12535,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1000,1.75,NaN,fixed_hold,500,80,3,353760.0,117920.000000,91560.0,134560.0,42,0.669109,0.571429,8422.857143,0.380371,True,540071.697192
4679,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,1000,80,3,341640.0,113880.000000,91320.0,132080.0,41,0.703297,0.538462,8332.682927,0.386606,True,527323.956044
4694,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,1500,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
4709,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,2500,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
4724,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,1.75,0.00,zero_cross,4000,80,3,332200.0,110733.333333,91320.0,132080.0,40,0.697802,0.538462,8305.000000,0.397592,True,517881.208791
1330,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.75,NaN,fixed_hold,2500,80,3,298680.0,99560.000000,91320.0,115320.0,9,0.777778,0.666667,33186.666667,0.386099,True,485042.222222
4829,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.25,0.00,zero_cross,1000,80,3,318880.0,106293.333333,90680.0,129560.0,31,0.730640,0.555556,10286.451613,0.406297,True,503383.097643
4844,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.25,0.00,zero_cross,1500,80,3,311760.0,103920.000000,90680.0,129560.0,31,0.730640,0.555556,10056.774194,0.415576,True,496263.097643
4859,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.25,0.00,zero_cross,2500,80,3,311760.0,103920.000000,90680.0,129560.0,31,0.730640,0.555556,10056.774194,0.415576,True,496263.097643
4874,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.25,0.00,zero_cross,4000,80,3,311760.0,103920.000000,90680.0,129560.0,31,0.730640,0.555556,10056.774194,0.415576,True,496263.097643
5261,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,0.25,abs_band,500,80,3,374400.0,124800.000000,90160.0,188600.0,45,0.625397,0.500000,8320.000000,0.503739,True,557158.766789
9790,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.25,NaN,fixed_hold,1500,80,3,349960.0,116653.333333,90080.0,166640.0,21,0.666667,0.571429,16664.761905,0.476169,True,533310.476190
3065,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,72,3,319428.0,106476.000000,89928.0,138924.0,9,0.777778,0.333333,35492.000000,0.434915,True,501339.555556
4885,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,80,3,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
4385,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,72,3,326016.0,108672.000000,89208.0,129204.0,17,0.766667,0.666667,19177.411765,0.396312,True,508148.666667
4210,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,NaN,fixed_hold,500,80,3,310320.0,103440.000000,88960.0,125320.0,46,0.672222,0.533333,6746.086957,0.403841,True,491242.777778
13040,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows ORANGE return over lag 100,1500,2.00,NaN,fixed_hold,4000,72,3,274680.0,91560.000000,88884.0,93456.0,6,1.000000,1.000000,45780.000000,0.340236,True,457948.000000

In [26]:
exit_mode_comparison = (
    focused_summary
    .groupby("exit_mode")
    .agg(
        best_total_pnl=("total_pnl", "max"),
        best_min_day_pnl=("min_day_pnl", "max"),
        best_robust_score=("robust_score", "max"),
        robust_count=("robust_pass", "sum"),
        configs=("candidate", "size"),
    )
    .sort_values("best_robust_score", ascending=False)
)

display(exit_mode_comparison)

candidate_exit_mode_comparison = (
    focused_summary
    .groupby(["candidate", "exit_mode"])
    .agg(
        best_total_pnl=("total_pnl", "max"),
        best_min_day_pnl=("min_day_pnl", "max"),
        best_robust_score=("robust_score", "max"),
        robust_count=("robust_pass", "sum"),
        configs=("candidate", "size"),
    )
    .reset_index()
    .sort_values(["candidate", "best_robust_score"], ascending=[True, False])
)

display(candidate_exit_mode_comparison)

            best_total_pnl  best_min_day_pnl  best_robust_score  robust_count  configs
exit_mode
fixed_hold        448840.0          122160.0      692171.111111           666     4125
zero_cross        401360.0          104480.0      586006.056166          1305     4125
abs_band          426360.0           98200.0      579615.813866          3423    12375

                                candidate   exit_mode  best_total_pnl  best_min_day_pnl  best_robust_score  robust_count  configs
1     lead_AMBER_to_MAGENTA_inverse_lag50  fixed_hold        386680.0          105000.0       5.994785e+05            87      375
2     lead_AMBER_to_MAGENTA_inverse_lag50  zero_cross        257280.0           58520.0       3.640026e+05           285      375
0     lead_AMBER_to_MAGENTA_inverse_lag50    abs_band        208760.0           57080.0       3.227470e+05           630     1125
4      lead_AMBER_to_ORANGE_follow_lag100  fixed_hold        438280.0           90080.0       5.904578e+05            27      375
5      lead_AMBER_to_ORANGE_follow_lag100  zero_cross         92000.0           -6870.0       5.683801e+04             0      375
3      lead_AMBER_to_ORANGE_follow_lag100    abs_band         64240.0          -10680.0      -4.578836e+04             0     1125
7       lead_AMBER_to_ORANGE_follow_lag50  fixed_hold        384920.0           85520.0       5.094422e+05            36      375
6       lead_AMBER_to_ORANGE_follow_lag50    abs_band         51960.0            3040.0       4.838678e+04            15     1125
8       lead_AMBER_to_ORANGE_follow_lag50  zero_cross         57960.0            3600.0       1.471072e+04             0      375
10      lead_AMBER_to_RED_inverse_lag1000  fixed_hold        370280.0          107360.0       5.887361e+05            57      375
9       lead_AMBER_to_RED_inverse_lag1000    abs_band        171360.0           41680.0       2.355846e+05           264     1125
11      lead_AMBER_to_RED_inverse_lag1000  zero_cross        193800.0           24280.0       2.116180e+05            42      375
13    lead_AMBER_to_YELLOW_inverse_lag100  fixed_hold        316080.0           95640.0       5.107322e+05            60      375
12    lead_AMBER_to_YELLOW_inverse_lag100    abs_band        232880.0           36160.0       2.948435e+05           360     1125
14    lead_AMBER_to_YELLOW_inverse_lag100  zero_cross        233000.0           48160.0       2.869197e+05           180      375
16   lead_MAGENTA_to_YELLOW_follow_lag100  fixed_hold        370200.0          113280.0       6.004544e+05            12      375
15   lead_MAGENTA_to_YELLOW_follow_lag100    abs_band        188640.0           48120.0       2.808143e+05           405     1125
17   lead_MAGENTA_to_YELLOW_follow_lag100  zero_cross        192160.0           42320.0       2.648519e+05           105      375
19  lead_MAGENTA_to_YELLOW_inverse_lag100  fixed_hold        356120.0           84160.0       5.281622e+05            33      375
20  lead_MAGENTA_to_YELLOW_inverse_lag100  zero_cross         14840.0          -12060.0      -1.451085e+05             0      375
18  lead_MAGENTA_to_YELLOW_inverse_lag100    abs_band        -19350.0          -17910.0               -inf             0     1125
22    lead_ORANGE_to_YELLOW_follow_lag100  fixed_hold        358360.0           98760.0       5.400717e+05            51      375
21    lead_ORANGE_to_YELLOW_follow_lag100    abs_band         29520.0           -8370.0      -9.485834e+04             0     1125
23    lead_ORANGE_to_YELLOW_follow_lag100  zero_cross         17560.0           -9690.0      -2.173968e+05             0      375
25     lead_RED_to_YELLOW_inverse_lag1000  fixed_hold        408480.0          108440.0       6.070178e+05            93      375
26     lead_RED_to_YELLOW_inverse_lag1000  zero_cross        401360.0          104480.0       5.860061e+05           267      375
24     lead_RED_to_YELLOW_inverse_lag1000    abs_band        426360.0           98200.0       5.796158e+05           585     1125
28      lead_RED_to_YELLOW_inverse_lag250  fixed_hold        443440.0          122160.0       6.921711e+05           117      375
29      lead_RED_to_YELLOW_inverse_lag250  zero_cross        199320.0           55800.0       3.138986e+05           165      375
27      lead_RED_to_YELLOW_inverse_lag250    abs_band        180240.0           42680.0       2.660809e+05           324     1125
31      lead_YELLOW_to_RED_follow_lag1000  fixed_hold        448840.0           68120.0       5.893948e+05            93      375
30      lead_YELLOW_to_RED_follow_lag1000    abs_band        317800.0           84080.0       4.829607e+05           840     1125
32      lead_YELLOW_to_RED_follow_lag1000  zero_cross        302120.0           55720.0       4.164028e+05           261      375

In [27]:
fixed_hold_wins = (
    focused_summary
    .sort_values("robust_score", ascending=False)
    .head(100)
    ["exit_mode"]
    .value_counts()
)

display(fixed_hold_wins)

exit_mode
fixed_hold    43
zero_cross    29
abs_band      28
Name: count, dtype: int64

In [28]:
best_row = focused_summary.sort_values(
    ["robust_pass", "robust_score", "total_pnl"],
    ascending=[False, False, False],
).iloc[0]

display(best_row.to_frame().T)

mask = (
    (focused_days["candidate"] == best_row["candidate"])
    & (focused_days["window"] == best_row["window"])
    & (focused_days["entry_z"] == best_row["entry_z"])
    & (focused_days["exit_mode"] == best_row["exit_mode"])
    & (
        (focused_days["exit_z"].isna() & pd.isna(best_row["exit_z"]))
        | (focused_days["exit_z"] == best_row["exit_z"])
    )
    & (focused_days["max_hold"] == best_row["max_hold"])
    & (focused_days["gross"] == best_row["gross"])
)

best_days = focused_days[mask].sort_values("day")
display(best_days)

if not focused_trades.empty:
    trade_mask = (
        (focused_trades["candidate"] == best_row["candidate"])
        & (focused_trades["window"] == best_row["window"])
        & (focused_trades["entry_z"] == best_row["entry_z"])
        & (focused_trades["exit_mode"] == best_row["exit_mode"])
        & (
            (focused_trades["exit_z"].isna() & pd.isna(best_row["exit_z"]))
            | (focused_trades["exit_z"] == best_row["exit_z"])
        )
        & (focused_trades["max_hold"] == best_row["max_hold"])
        & (focused_trades["gross"] == best_row["gross"])
    )

    best_trades = focused_trades[trade_mask].sort_values(["day", "entry_idx"])
    display(best_trades)

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
2590,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,NaN,fixed_hold,1500,80,3,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.8,26084.705882,0.37155,True,692171.111111

,day,trade_count,day_pnl,hit_rate,avg_trade_pnl,median_trade_pnl,window,entry_z,exit_z,exit_mode,max_hold,gross,candidate,family,kind,note
7770,2,6,122160.0,0.833333,20360.000000,20240.0,500,2.25,NaN,fixed_hold,1500,80,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250
7771,3,6,156520.0,0.833333,26086.666667,17480.0,500,2.25,NaN,fixed_hold,1500,80,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250
7772,4,5,164760.0,0.800000,32952.000000,36200.0,500,2.25,NaN,fixed_hold,1500,80,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250

,candidate,family,kind,note,day,window,entry_z,exit_z,exit_mode,max_hold,gross,q_trade,net_position,gross_position,entry_idx,exit_idx,entry_ts,exit_ts,side,entry_z_seen,exit_z_seen,hold,exec_pnl,position
197503,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,1252,2752,125200,275200,1,-2.258428,-0.761087,1500,11680.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197504,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,2808,4308,280800,430800,1,-2.263723,-2.125230,1500,56360.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197505,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,4368,5868,436800,586800,1,-2.357609,0.876294,1500,36360.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197506,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,6193,7693,619300,769300,-1,2.437243,1.037322,1500,-22720.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197507,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,7904,9404,790400,940400,1,-2.398069,3.018385,1500,24480.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197508,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,2,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,9405,9999,940500,999900,-1,3.006702,-0.338921,594,16000.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197509,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,929,2429,92900,242900,-1,2.263040,-2.637358,1500,12320.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197510,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,2430,3930,243000,393000,1,-2.783565,2.113135,1500,-1400.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197511,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,4076,5576,407600,557600,-1,2.346412,0.415596,1500,22000.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197512,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,5640,7140,564000,714000,1,-2.574856,1.749237,1500,69640.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197513,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,7147,8647,714700,864700,-1,2.317380,-2.037268,1500,12960.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197514,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,3,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,8652,9999,865200,999900,1,-2.305566,-1.456873,1347,41000.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"
197515,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,4,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,807,2307,80700,230700,-1,2.260344,-0.735983,1500,83880.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197516,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,4,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,2953,4453,295300,445300,-1,2.393503,0.645843,1500,45600.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197517,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,4,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,5004,6504,500400,650400,-1,2.400040,0.123726,1500,36200.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197518,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,4,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,8047,9547,804700,954700,-1,2.329828,-0.740775,1500,-12080.0,"[-80.0, -0.0, -0.0, -0.0, -0.0]"
197519,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,4,500,2.25,NaN,fixed_hold,1500,80,"[80.0, 0.0, 0.0, 0.0, 0.0]",80.0,80.0,9776,9999,977600,999900,1,-2.265301,1.137932,223,11160.0,"[80.0, 0.0, 0.0, 0.0, 0.0]"

In [29]:
def make_lead_lag_spec(name_prefix, leader_colour, follower_colour, relation, lag):
    leader = COLOUR_TO_PRODUCT[leader_colour]
    follower = COLOUR_TO_PRODUCT[follower_colour]
    return {
        "name": f"{name_prefix}_lag{lag}",
        "kind": "lead_lag",
        "family": "lead_lag_lag_sweep",
        "leader": leader,
        "follower": follower,
        "relation": relation,
        "lag": int(lag),
        "note": f"{follower_colour} {relation} follows {leader_colour} return over lag {lag}",
    }


LAG_SWEEP_SPECS = []

for lag in [25, 50, 100, 150, 250, 500, 750, 1000, 1250, 1500, 2000]:
    LAG_SWEEP_SPECS.append(make_lead_lag_spec("lead_AMBER_to_RED_inverse", "AMBER", "RED", "inverse", lag))
    LAG_SWEEP_SPECS.append(make_lead_lag_spec("lead_RED_to_YELLOW_inverse", "RED", "YELLOW", "inverse", lag))
    LAG_SWEEP_SPECS.append(make_lead_lag_spec("lead_YELLOW_to_RED_follow", "YELLOW", "RED", "follow", lag))
    LAG_SWEEP_SPECS.append(make_lead_lag_spec("lead_AMBER_to_ORANGE_follow", "AMBER", "ORANGE", "follow", lag))
    LAG_SWEEP_SPECS.append(make_lead_lag_spec("lead_ORANGE_to_YELLOW_follow", "ORANGE", "YELLOW", "follow", lag))

lag_sweep_summary, lag_sweep_days, lag_sweep_trades = run_grid(
    specs=LAG_SWEEP_SPECS,
    windows=[250, 500, 1000, 1500],
    entry_zs=[1.25, 1.50, 1.75, 2.00],
    exit_zs_by_mode={"fixed_hold": [np.nan]},
    max_holds=[500, 1000, 1500, 2500, 4000],
    grosses=[80],
    label="lag_sweep",
)

lag_sweep_summary.to_csv(OUT_DIR / "lag_sweep_summary.csv", index=False)
lag_sweep_days.to_csv(OUT_DIR / "lag_sweep_days.csv", index=False)
lag_sweep_trades.to_csv(OUT_DIR / "lag_sweep_trades.csv", index=False)

display(lag_sweep_summary.head(80))

lag_sweep: total configs = 4400
[   0.00s] lag_sweep 1/4400: lead_AMBER_to_RED_inverse_lag25, w=250, entry=1.25, exit=nan, mode=fixed_hold, hold=500, gross=80
[   1.19s] lag_sweep 250/4400: lead_AMBER_to_ORANGE_follow_lag25, w=250, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   2.30s] lag_sweep 500/4400: lead_RED_to_YELLOW_inverse_lag50, w=250, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   3.41s] lag_sweep 750/4400: lead_ORANGE_to_YELLOW_follow_lag50, w=500, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   4.72s] lag_sweep 1000/4400: lead_YELLOW_to_RED_follow_lag100, w=500, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   5.84s] lag_sweep 1250/4400: lead_AMBER_to_RED_inverse_lag150, w=1000, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   7.02s] lag_sweep 1500/4400: lead_AMBER_to_ORANGE_follow_lag150, w=1000, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   8.15s] lag_sweep 1750/4400: lead_RED_to_YELLOW_inverse_lag250, w=1500, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[   9.30s] lag_sweep 2000/4400: lead_ORANGE_to_YELLOW_follow_lag250, w=1500, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  10.48s] lag_sweep 2250/4400: lead_AMBER_to_ORANGE_follow_lag500, w=250, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  11.61s] lag_sweep 2500/4400: lead_RED_to_YELLOW_inverse_lag750, w=250, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  12.68s] lag_sweep 2750/4400: lead_ORANGE_to_YELLOW_follow_lag750, w=500, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  13.87s] lag_sweep 3000/4400: lead_YELLOW_to_RED_follow_lag1000, w=500, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  14.97s] lag_sweep 3250/4400: lead_AMBER_to_RED_inverse_lag1250, w=1000, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  16.03s] lag_sweep 3500/4400: lead_AMBER_to_ORANGE_follow_lag1250, w=1000, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  17.03s] lag_sweep 3750/4400: lead_RED_to_YELLOW_inverse_lag1500, w=1500, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  18.05s] lag_sweep 4000/4400: lead_ORANGE_to_YELLOW_follow_lag1500, w=1500, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  19.13s] lag_sweep 4250/4400: lead_AMBER_to_ORANGE_follow_lag2000, w=250, entry=1.5, exit=nan, mode=fixed_hold, hold=4000, gross=80
[  19.79s] lag_sweep 4400/4400: lead_ORANGE_to_YELLOW_follow_lag2000, w=1500, entry=2.0, exit=nan, mode=fixed_hold, hold=4000, gross=80

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
2124,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.25,NaN,fixed_hold,4000,80,3,415480.0,138493.333333,137760.0,139520.0,8,1.000000,1.000000,51935.000000,0.335804,True,696500.000000
2129,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.50,NaN,fixed_hold,4000,80,3,418440.0,139480.000000,135240.0,143400.0,8,1.000000,1.000000,52305.000000,0.342701,True,694420.000000
1979,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1000,2.00,NaN,fixed_hold,4000,80,3,410360.0,136786.666667,125840.0,153800.0,7,1.000000,1.000000,58622.857143,0.374793,True,667540.000000
4160,lead_YELLOW_to_RED_follow_lag2000,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 2000,250,1.25,NaN,fixed_hold,500,80,3,395520.0,131840.000000,122240.0,140400.0,46,0.675000,0.625000,8598.260870,0.354976,True,643462.500000
1717,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,500,2.00,NaN,fixed_hold,1500,80,3,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
2904,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.25,NaN,fixed_hold,4000,80,3,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
2540,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1500,1.25,NaN,fixed_hold,500,80,3,415080.0,138360.000000,92960.0,225840.0,36,0.715873,0.600000,11530.000000,0.544088,True,599949.147841
2095,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,250,2.00,NaN,fixed_hold,500,80,3,398840.0,132946.666667,96560.0,163000.0,51,0.627723,0.611111,7820.392157,0.408685,True,595329.417211
1074,lead_AMBER_to_ORANGE_follow_lag100,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 100,500,1.75,NaN,fixed_hold,4000,80,3,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
2981,lead_YELLOW_to_RED_follow_lag1000,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 1000,500,1.25,NaN,fixed_hold,1000,80,3,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
2843,lead_AMBER_to_RED_inverse_lag1000,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1000,1000,1.25,NaN,fixed_hold,2500,80,3,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
2909,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.50,NaN,fixed_hold,4000,80,3,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
2920,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,1000,1.25,NaN,fixed_hold,500,80,3,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
1989,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1500,1.50,NaN,fixed_hold,4000,80,3,349080.0,116360.000000,112480.0,120200.0,8,0.777778,0.666667,43635.000000,0.344334,True,577762.222222
1293,lead_RED_to_YELLOW_inverse_lag150,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 150,250,1.75,NaN,fixed_hold,2500,80,3,374560.0,124853.333333,98000.0,160520.0,12,0.666667,0.500000,31213.333333,0.428556,True,573393.333333
801,lead_AMBER_to_RED_inverse_lag100,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 100,250,1.25,NaN,fixed_hold,1000,80,3,415200.0,138400.000000,77680.0,196680.0,30,0.633333,0.400000,13840.000000,0.473699,True,572876.666667
2134,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.75,NaN,fixed_hold,4000,80,3,361400.0,120466.666667,101880.0,144640.0,7,1.000000,1.000000,51628.571429,0.400221,True,570660.000000
2917,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,2.00,NaN,fixed_hold,1500,80,3,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
800,lead_AMBER_to_RED_inverse_lag100,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 100,250,1.25,NaN,fixed_hold,500,80,3,347760.0,115920.000000,104880.0,130040.0,57,0.596491,0.578947,6101.052632,0.373936,True,560712.982456
2519,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,500,2.00,NaN,fixed_hold,4000,80,3,361800.0,120600.000000,97560.0,153920.0,9,0.777778,0.333333,40200.000000,0.425428,True,558975.555556
1724,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,1000,1.25,NaN,fixed_hold,4000,80,3,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556
2514,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,500,1.75,NaN,fixed_hold,4000,80,3,358240.0,119413.333333,94600.0,151720.0,9,0.777778,0.333333,39804.444444,0.423515,True,549495.555556
2374,lead_ORANGE_to_YELLOW_follow_lag500,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 500,1000,1.75,NaN,fixed_hold,4000,80,3,356440.0,118813.333333,93880.0,135800.0,7,0.722222,0.500000,50920.000000,0.380990,True,547061.111111
2750,lead_ORANGE_to_YELLOW_follow_lag750,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 750,500,1.75,NaN,fixed_hold,500,80,3,382080.0,127360.000000,81160.0,195720.0,46,0.652778,0.625000,8306.086957,0.512249,True,546626.514517
2591,lead_YELLOW_to_RED_follow_lag750,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 750,500,1.75,NaN,fixed_hold,1000,80,3,378400.0,126133.333333,82520.0,156160.0,25,0.726852,0.555556,15136.000000,0.412685,True,546581.203704
898,lead_RED_to_YELLOW_inverse_lag100,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 100,250,2.00,NaN,fixed_hold,2500,80,3,372640.0,124213.333333,84600.0,171160.0,12,0.750000,0.500000,31053.333333,0.459317,True,544715.000000
2140,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1500,1.25,NaN,fixed_hold,500,80,3,372400.0,124133.333333,85080.0,148800.0,40,0.620879,0.307692,9310.000000,0.399570,True,544408.901099
893,lead_RED_to_YELLOW_inverse_lag100,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 100,250,1.75,NaN,fixed_hold,2500,80,3,367280.0,122426.666667,86960.0,178560.0,12,0.750000,0.500000,30606.666667,0.486169,True,544075.000000
1565,lead_ORANGE_to_YELLOW_follow_lag150,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 150,1000,1.50,NaN,fixed_hold,500,80,3,420320.0,140106.666667,59600.0,217080.0,44,0.636508,0.466667,9552.727273,0.516464,True,540525.222627
1170,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 100,1000,1.75,NaN,fixed_hold,500,80,3,353760.0,117920.000000,91560.0,134560.0,42,0.669109,0.571429,8422.857143,0.380371,True,540071.697192
2425,lead_AMBER_to_RED_inverse_lag750,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 750,500,1.50,NaN,fixed_hold,500,80,3,354360.0,118120.000000,91040.0,169920.0,47,0.636111,0.533333,7539.574468,0.479512,True,539424.722222
1062,lead_AMBER_to_ORANGE_follow_lag100,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 100,500,1.25,NaN,fixed_hold,1500,80,3,349960.0,116653.333333,90080.0,166640.0,21,0.666667,0.571429,16664.761905,0.476169,True,533310.476190
2135,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,2.00,NaN,fixed_hold,500,80,3,333720.0,111240.000000,97280.0,119160.0,32,0.688889,0.666667,10428.750000,0.357066,True,531957.777778
2986,lead_YELLOW_to_RED_follow_lag1000,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 1000,500,1.50,NaN,fixed_hold,1000,80,3,411360.0,137120.000000,57240.0,192680.0,26,0.773148,0.666667,15821.538462,0.468398,True,529559.907407
1165,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 100,1000,1.50,NaN,fixed_hold,500,80,3,358360.0,119453.333333,81640.0,145360.0,47,0.661111,0.625000,7624.680851,0.405626,True,525095.555556
2769,lead_ORANGE_to_YELLOW_follow_lag750,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 750,1000,1.50,NaN,fixed_hold,4000,80,3,320200.0,106733.333333,94440.0,115880.0,7,0.888889,0.666667,45742.857143,0.361899,True,512857.777778
1462,lead_AMBER_to_ORANGE_follow_lag150,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 150,500,1.25,NaN,fixed_hold,1500,80,3,324880.0,108293.333333,92480.0,128240.0,21,0.714286,0.428571,15470.476190,0.394730,True,512340.000000
679,lead_AMBER_to_ORANGE_follow_lag50,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 50,500,2.00,NaN,fixed_hold,4000,80,3,373400.0,124466.666667,66160.0,154840.0,9,0.777778,0.666667,41488.888889,0.414676,True,509442.222222
1722,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,1000,1.25,NaN,fixed_hold,1500,80,3,359720.0,119906.666667,73000.0,152000.0,18,0.777778,0.666667,19984.444444,0.422551,True,509442.222222
1199,lead_ORANGE_to_YELLOW_follow_lag100,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 100,1500,2.00,NaN,fixed_hold,4000,80,3,305200.0,101733.333333,98760.0,103840.0,6,1.000000,1.000000,50866.666667,0.340236,True,508220.000000
1092,lead_AMBER_to_ORANGE_follow_lag100,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 100,1000,1.75,NaN,fixed_hold,1500,80,3,351400.0,117133.333333,76640.0,178920.0,16,0.811111,0.800000,21962.500000,0.509163,True,508169.220894
1961,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1000,1.25,NaN,fixed_hold,1000,80,3,326760.0,108920.000000,89240.0,147800.0,26,0.611111,0.500000,12567.692308,0.452320,True,508045.555556
3212,lead_AMBER_to_RED_inverse_lag1250,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1250,250,1.75,NaN,fixed_hold,1500,80,3,330880.0,110293.333333,86280.0,142680.0,18,0.833333,0.666667,18382.222222,0.431214,True,507190.000000
2764,lead_ORANGE_to_YELLOW_follow_lag750,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 750,1000,1.25,NaN,fixed_hold,4000,80,3,315720.0,105240.000000,93000.0,115840.0,7,0.888889,0.666667,45102.857143,0.366907,True,505497.777778
547,lead_RED_to_YELLOW_inverse_lag50,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 50,1500,1.50,NaN,fixed_hold,1500,80,3,348680.0,116226.666667,74760.0,154240.0,18,0.777778,0.666667,19371.111111,0.442354,True,501922.222222
202,lead_YELLOW_to_RED_follow_lag25,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 25,1000,1.25,NaN,fixed_hold,1500,80,3,310920.0,103640.000000,89360.0,123800.0,18,0.777778,0.666667,17273.333333,0.398173,True,493362.222222
2905,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.50,NaN,fixed_hold,500,80,3,310320.0,103440.000000,88960.0,125320.0,46,0.672222,0.533333,6746.086957,0.403841,True,491242.777778
922,lead_RED_to_YELLOW_inverse_lag100,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 100,1000,1.25,NaN,fixed_hold,1500,80,3,326800.0,108933.333333,79400.0,137520.0,18,0.777778,0.666667,18155.555556,0.420808,True,489322.222222
667,lead_AMBER_to_ORANGE_follow_lag50,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 50,500,1.50,NaN,fixed_hold,1500,80,3,315000.0,105000.000000,85520.0,140000.0,21,0.761905,0.571429,15000.000000,0.444444,True,489278.095238
2151,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1500,1.75,NaN,fixed_hold,1000,80,3,337640.0,112546.666667,72840.0,152320.0,18,0.891667,0.800000,18757.777778,0.451131,True,487765.833333
2545,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1500,1.50,NaN,fixed_hold,500,80,3,332040.0,110680.000000,77440.0,175680.0,33,0.619577,0.444444,10061.818182,0.529093,True,486542.722544
2853,lead_AMBER_to_RED_inverse_lag1000,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1000,1000,1.75,NaN,fixed_hold,2500,80,3,298680.0,99560.000000,91320.0,115320.0,9,0.777778,0.666667,33186.666667,0.386099,True,485042.222222
63,lead_AMBER_to_RED_inverse_lag25,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 25,1500,1.25,NaN,fixed_hold,2500,80,3,320640.0,106880.000000,79560.0,129360.0,12,0.833333,0.750000,26720.000000,0.403443,True,483926.666667
1727,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,1000,1.50,NaN,fixed_hold,1500,80,3,308480.0,102826.666667,85920.0,134560.0,16,0.744444,0.600000,19280.000000,0.436203,True,483692.222222
3739,lead_RED_to_YELLOW_inverse_lag1500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1500,1000,2.00,NaN,fixed_hold,4000,80,3,311960.0,103986.666667,83960.0,122160.0,6,0.833333,0.500000,51993.333333,0.391589,True,482796.666667
3734,lead_RED_to_YELLOW_inverse_lag1500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1500,1000,1.75,NaN,fixed_hold,4000,80,3,313000.0,104333.333333,80680.0,130520.0,6,0.833333,0.500000,52166.666667,0.416997,True,477276.666667
2900,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.25,NaN,fixed_hold,500,80,3,377120.0,125706.666667,48400.0,168360.0,48,0.645833,0.437500,7856.666667,0.446436,True,476430.416667
2491,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,250,1.75,NaN,fixed_hold,1000,80,3,318480.0,106160.000000,77040.0,137640.0,27,0.629630,0.444444,11795.555556,0.432178,True,475097.037037
1286,lead_RED_to_YELLOW_inverse_lag150,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 150,250,1.50,NaN,fixed_hold,1000,80,3,337560.0,112520.000000,66920.0,173160.0,29,0.759259,0.700000,11640.000000,0.512975,True,473982.082527
2759,lead_ORANGE_to_YELLOW_follow_lag750,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 750,500,2.00,NaN,fixed_hold,4000,80,3,309800.0,103266.666667,79080.0,116640.0,8,0.777778,0.666667,38725.000000,0.376501,True,471682.222222
2521,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1000,1.25,NaN,fixed_hold,1000,80,3,349240.0,116413.333333,60000.0,183880.0,24,0.666667,0.500000,14551.666667,0.526515,True,469421.861566
2526,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1000,1.50,NaN,fixed_hold,1000,80,3,345320.0,115106.666667,60120.0,152440.0,24,0.708333,0.500000,14388.333333,0.441446,True,468414.166667
2821,lead_AMBER_to_RED_inverse_lag1000,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1000,500,1.25,NaN,fixed_hold,1000,80,3,336640.0,112213.333333,63960.0,144760.0,26,0.699074,0.555556,12947.692308,0.430014,True,467687.314815
1601,lead_AMBER_to_RED_inverse_lag250,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 250,250,1.25,NaN,fixed_hold,1000,80,3,388760.0,129586.666667,36680.0,198360.0,30,0.766667,0.500000,12958.666667,0.510238,True,463979.565456
1716,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,500,2.00,NaN,fixed_hold,1000,80,3,307400.0,102466.666667,76680.0,132520.0,27,0.629630,0.555556,11385.185185,0.431100,True,463852.592593
2517,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,500,2.00,NaN,fixed_hold,1500,80,3,334280.0,111426.666667,60000.0,150920.0,18,0.722222,0.666667,18571.111111,0.451478,True,457974.444444
157,lead_RED_to_YELLOW_inverse_lag25,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 25,1500,2.00,NaN,fixed_hold,1500,80,3,342880.0,114293.333333,54440.0,155200.0,18,0.777778,0.666667,19048.888889,0.452636,True,455482.222222
272,lead_AMBER_to_ORANGE_follow_lag25,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 25,500,1.75,NaN,fixed_hold,1500,80,3,356080.0,118693.333333,51440.0,203840.0,20,0.698413,0.666667,17804.000000,0.572456,True,455396.976888
2504,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,500,1.25,NaN,fixed_hold,4000,80,3,319120.0,106373.333333,64200.0,147040.0,9,0.888889,0.666667,35457.777778,0.460767,True,451297.777778
2848,lead_AMBER_to_RED_inverse_lag1000,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1000,1000,1.50,NaN,fixed_hold,2500,80,3,296680.0,98893.333333,74200.0,112640.0,10,0.805556,0.666667,29668.000000,0.379668,True,448816.111111
1982,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1500,1.25,NaN,fixed_hold,1500,80,3,302000.0,100666.666667,70760.0,133640.0,15,0.933333,0.800000,20133.333333,0.442517,True,447986.666667
2600,lead_YELLOW_to_RED_follow_lag750,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 750,1000,1.25,NaN,fixed_hold,500,80,3,315680.0,105226.666667,64000.0,145320.0,45,0.662897,0.533333,7015.111111,0.460340,True,446678.115079
2620,lead_YELLOW_to_RED_follow_lag750,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 750,1500,1.25,NaN,fixed_hold,500,80,3,282080.0,94026.666667,80640.0,111920.0,41,0.584921,0.571429,6880.000000,0.396767,True,446509.603175
3253,lead_AMBER_to_RED_inverse_lag1250,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1250,1000,1.75,NaN,fixed_hold,2500,80,3,280640.0,93546.666667,79720.0,118160.0,9,0.888889,0.666667,31182.222222,0.421038,True,443857.777778
542,lead_RED_to_YELLOW_inverse_lag50,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 50,1500,1.25,NaN,fixed_hold,1500,80,3,293600.0,97866.666667,73480.0,114440.0,18,0.611111,0.500000,16311.111111,0.389782,True,443365.555556
1336,lead_RED_to_YELLOW_inverse_lag150,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 150,1000,2.00,NaN,fixed_hold,1000,80,3,397800.0,132600.000000,18480.0,190000.0,22,0.779762,0.625000,18081.818182,0.477627,True,438274.880952
2525,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1000,1.50,NaN,fixed_hold,500,80,3,340000.0,113333.333333,47280.0,151320.0,40,0.622711,0.461538,8500.000000,0.445059,True,437179.047619
2156,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1500,2.00,NaN,fixed_hold,1000,80,3,301360.0,100453.333333,65520.0,147520.0,17,0.838095,0.714286,17727.058824,0.489514,True,436390.476190

In [30]:
lag_sweep_summary["relationship"] = lag_sweep_summary["candidate"].str.replace(r"_lag\d+$", "", regex=True)
lag_sweep_summary["lag"] = lag_sweep_summary["candidate"].str.extract(r"_lag(\d+)$").astype(int)

best_lag_by_relationship = (
    lag_sweep_summary
    .sort_values(["robust_pass", "robust_score", "total_pnl"], ascending=[False, False, False])
    .groupby("relationship")
    .head(10)
)

display(best_lag_by_relationship[
    [
        "relationship", "lag", "window", "entry_z", "max_hold", "gross",
        "total_pnl", "min_day_pnl", "total_trades", "mean_hit_rate",
        "one_day_dependency", "robust_pass", "robust_score"
    ]
])

                      relationship   lag  window  entry_z  max_hold  gross  total_pnl  min_day_pnl  total_trades  mean_hit_rate  one_day_dependency  robust_pass   robust_score
2124    lead_RED_to_YELLOW_inverse   500    1000     1.25      4000     80   415480.0     137760.0             8       1.000000            0.335804         True  696500.000000
2129    lead_RED_to_YELLOW_inverse   500    1000     1.50      4000     80   418440.0     135240.0             8       1.000000            0.342701         True  694420.000000
1979  lead_ORANGE_to_YELLOW_follow   250    1000     2.00      4000     80   410360.0     125840.0             7       1.000000            0.374793         True  667540.000000
4160     lead_YELLOW_to_RED_follow  2000     250     1.25       500     80   395520.0     122240.0            46       0.675000            0.354976         True  643462.500000
1717    lead_RED_to_YELLOW_inverse   250     500     2.00      1500     80   426960.0     105120.0            18       0.888889            0.431328         True  641811.111111
2904    lead_RED_to_YELLOW_inverse  1000     500     1.25      4000     80   386360.0     108440.0             8       0.888889            0.361114         True  607017.777778
2540    lead_RED_to_YELLOW_inverse   750    1500     1.25       500     80   415080.0      92960.0            36       0.715873            0.544088         True  599949.147841
2095    lead_RED_to_YELLOW_inverse   500     250     2.00       500     80   398840.0      96560.0            51       0.627723            0.408685         True  595329.417211
1074   lead_AMBER_to_ORANGE_follow   100     500     1.75      4000     80   438280.0      74200.0             9       0.888889            0.488455         True  590457.777778
2981     lead_YELLOW_to_RED_follow  1000     500     1.25      1000     80   448840.0      68120.0            27       0.851852            0.425631         True  589394.814815
2843     lead_AMBER_to_RED_inverse  1000    1000     1.25      2500     80   370280.0     107360.0            11       0.805556            0.380361         True  588736.111111
2909    lead_RED_to_YELLOW_inverse  1000     500     1.50      4000     80   381480.0     102040.0             8       0.777778            0.366782         True  587615.555556
2920    lead_RED_to_YELLOW_inverse  1000    1000     1.25       500     80   408480.0      89600.0            42       0.633333            0.549452         True  585551.504113
1989  lead_ORANGE_to_YELLOW_follow   250    1500     1.50      4000     80   349080.0     112480.0             8       0.777778            0.344334         True  577762.222222
1293    lead_RED_to_YELLOW_inverse   150     250     1.75      2500     80   374560.0      98000.0            12       0.666667            0.428556         True  573393.333333
801      lead_AMBER_to_RED_inverse   100     250     1.25      1000     80   415200.0      77680.0            30       0.633333            0.473699         True  572876.666667
2134    lead_RED_to_YELLOW_inverse   500    1000     1.75      4000     80   361400.0     101880.0             7       1.000000            0.400221         True  570660.000000
800      lead_AMBER_to_RED_inverse   100     250     1.25       500     80   347760.0     104880.0            57       0.596491            0.373936         True  560712.982456
2374  lead_ORANGE_to_YELLOW_follow   500    1000     1.75      4000     80   356440.0      93880.0             7       0.722222            0.380990         True  547061.111111
2750  lead_ORANGE_to_YELLOW_follow   750     500     1.75       500     80   382080.0      81160.0            46       0.652778            0.512249         True  546626.514517
2591     lead_YELLOW_to_RED_follow   750     500     1.75      1000     80   378400.0      82520.0            25       0.726852            0.412685         True  546581.203704
1565  lead_ORANGE_to_YELLOW_follow   150    1000     1.50       500     80   420320.0      59600.0            44       0.636508            0.516464         True  540525.222627
1170  lead_ORANGE_to_YELLOW_follow   100    1000     1.75       500     80   353760.0      91560.0            42       0.669109            0.380371         True  540071.697192
2425     lead_AMBER_to_RED_inverse   750     500     1.50       500     80   354360.0      91040.0            47       0.636111            0.479512         True  539424.722222
1062   lead_AMBER_to_ORANGE_follow   100     500     1.25      1500     80   349960.0      90080.0            21       0.666667            0.476169         True  533310.476190
2986     lead_YELLOW_to_RED_follow  1000     500     1.50      1000     80   411360.0      57240.0            26       0.773148            0.468398         True  529559.907407
1165  lead_ORANGE_to_YELLOW_follow   100    1000     1.50       500     80   358360.0      81640.0            47       0.661111            0.405626         True  525095.555556
2769  lead_ORANGE_to_YELLOW_follow   750    1000     1.50      4000     80   320200.0      94440.0             7       0.888889            0.361899         True  512857.777778
1462   lead_AMBER_to_ORANGE_follow   150     500     1.25      1500     80   324880.0      92480.0            21       0.714286            0.394730         True  512340.000000
679    lead_AMBER_to_ORANGE_follow    50     500     2.00      4000     80   373400.0      66160.0             9       0.777778            0.414676         True  509442.222222
1199  lead_ORANGE_to_YELLOW_follow   100    1500     2.00      4000     80   305200.0      98760.0             6       1.000000            0.340236         True  508220.000000
1092   lead_AMBER_to_ORANGE_follow   100    1000     1.75      1500     80   351400.0      76640.0            16       0.811111            0.509163         True  508169.220894
1961  lead_ORANGE_to_YELLOW_follow   250    1000     1.25      1000     80   326760.0      89240.0            26       0.611111            0.452320         True  508045.555556
3212     lead_AMBER_to_RED_inverse  1250     250     1.75      1500     80   330880.0      86280.0            18       0.833333            0.431214         True  507190.000000
202      lead_YELLOW_to_RED_follow    25    1000     1.25      1500     80   310920.0      89360.0            18       0.777778            0.398173         True  493362.222222
667    lead_AMBER_to_ORANGE_follow    50     500     1.50      1500     80   315000.0      85520.0            21       0.761905            0.444444         True  489278.095238
2853     lead_AMBER_to_RED_inverse  1000    1000     1.75      2500     80   298680.0      91320.0             9       0.777778            0.386099         True  485042.222222
63       lead_AMBER_to_RED_inverse    25    1500     1.25      2500     80   320640.0      79560.0            12       0.833333            0.403443         True  483926.666667
2821     lead_AMBER_to_RED_inverse  1000     500     1.25      1000     80   336640.0      63960.0            26       0.699074            0.430014         True  467687.314815
1601     lead_AMBER_to_RED_inverse   250     250     1.25      1000     80   388760.0      36680.0            30       0.766667            0.510238         True  463979.565456
272    lead_AMBER_to_ORANGE_follow    25     500     1.75      1500     80   356080.0      51440.0            20       0.698413            0.572456         True  455396.976888
2848     lead_AMBER_to_RED_inverse  1000    1000     1.50      2500     80   296680.0      74200.0            10       0.805556            0.379668         True  448816.111111
2600     lead_YELLOW_to_RED_follow   750    1000     1.25       500     80   315680.0      64000.0            45       0.662897            0.460340         True  446678.115079
2620     lead_YELLOW_to_RED_follow   750    1500     1.25       500     80   282080.0      80640.0            41       0.584921            0.396767         True  446509.603175
261    lead_AMBER_to_ORANGE_follow    25     500     1.25      1000     80   326920.0      53120.0            30       0.700000            0.547290         True  431781.014315
4161     lead_YELLOW_to_RED_follow  2000     250     1.25      1000     80   307200.0      60920.0            24       0.708333            0.568359         True  425058.229167
1806     lead_YELLOW_to_RED_follow   250    1000     1.50      1000     80   382360.0      21280.0            24       0.664021            0.529972         True  424754.835145
1457   lead_AMBER_to_ORANGE_follow   150     250     2.00      1500     80   298320.0      57960.0            21       0.809524            0.420890         True  418216.190476
647    lead_AMBER_to_ORANGE_follow    50     250     1.50      1500     80   261160.0      74880.0            21       0.714286            0.370041         True  414134.285714
1766     lead_YELLOW_to_RED_follow   250     250     1.50      1000     80   304840.0      43840.0            30       0.633333            0.524078         True  392928.846171

In [31]:
MIX_EXIT_MODES = {
    "fixed_hold": [np.nan],
    "abs_band": [0.25, 0.50, 0.75],
    "zero_cross": [0.0],
}

mix_summary, mix_days, mix_trades = run_grid(
    specs=MIXING_SPECS + PAIRWISE_SPECS,
    windows=[500, 1000, 1500, 2500, 4000],
    entry_zs=[1.25, 1.50, 1.75, 2.00, 2.25],
    exit_zs_by_mode=MIX_EXIT_MODES,
    max_holds=[500, 1000, 1500, 2500, 4000],
    grosses=[40, 60, 80],
    label="mix_pair_sanity",
)

mix_summary.to_csv(OUT_DIR / "mix_pair_sanity_summary.csv", index=False)
mix_days.to_csv(OUT_DIR / "mix_pair_sanity_days.csv", index=False)
mix_trades.to_csv(OUT_DIR / "mix_pair_sanity_trades.csv", index=False)

display(mix_summary.head(80))

mix_pair_sanity: total configs = 11250
[   0.00s] mix_pair_sanity 1/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=500, entry=1.25, exit=nan, mode=fixed_hold, hold=500, gross=40
[   2.30s] mix_pair_sanity 250/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[   4.37s] mix_pair_sanity 500/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[   6.55s] mix_pair_sanity 750/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[   8.38s] mix_pair_sanity 1000/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  10.39s] mix_pair_sanity 1250/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=2500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  12.47s] mix_pair_sanity 1500/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=2500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  14.23s] mix_pair_sanity 1750/11250: mix_RED_blend_YELLOW_MAGENTA_75_25_mr, w=4000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  16.12s] mix_pair_sanity 2000/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  18.23s] mix_pair_sanity 2250/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  19.97s] mix_pair_sanity 2500/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  21.94s] mix_pair_sanity 2750/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  24.09s] mix_pair_sanity 3000/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  25.93s] mix_pair_sanity 3250/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=2500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  27.91s] mix_pair_sanity 3500/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=4000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  29.74s] mix_pair_sanity 3750/11250: mix_RED_blend_YELLOW_MAGENTA_50_50_mr, w=4000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  31.82s] mix_pair_sanity 4000/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  33.91s] mix_pair_sanity 4250/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  36.07s] mix_pair_sanity 4500/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  37.94s] mix_pair_sanity 4750/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  39.78s] mix_pair_sanity 5000/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=2500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  41.51s] mix_pair_sanity 5250/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=2500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  51.71s] mix_pair_sanity 5500/11250: mix_ORANGE_blend_YELLOW_RED_50_50_mr, w=4000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  53.55s] mix_pair_sanity 5750/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  55.71s] mix_pair_sanity 6000/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  57.65s] mix_pair_sanity 6250/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  59.63s] mix_pair_sanity 6500/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  61.59s] mix_pair_sanity 6750/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  63.44s] mix_pair_sanity 7000/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=2500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  65.31s] mix_pair_sanity 7250/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=4000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  67.15s] mix_pair_sanity 7500/11250: mix_AMBER_blend_YELLOW_ORANGE_50_50_mr, w=4000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  69.06s] mix_pair_sanity 7750/11250: YELLOW_vs_ORANGE_ratio_mr, w=500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  71.03s] mix_pair_sanity 8000/11250: YELLOW_vs_ORANGE_ratio_mr, w=1000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  73.09s] mix_pair_sanity 8250/11250: YELLOW_vs_ORANGE_ratio_mr, w=1000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  74.87s] mix_pair_sanity 8500/11250: YELLOW_vs_ORANGE_ratio_mr, w=1500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  76.58s] mix_pair_sanity 8750/11250: YELLOW_vs_ORANGE_ratio_mr, w=2500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  78.29s] mix_pair_sanity 9000/11250: YELLOW_vs_ORANGE_ratio_mr, w=2500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  79.61s] mix_pair_sanity 9250/11250: YELLOW_vs_ORANGE_ratio_mr, w=4000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  81.37s] mix_pair_sanity 9500/11250: YELLOW_vs_ORANGE_spread_mr, w=500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  83.37s] mix_pair_sanity 9750/11250: YELLOW_vs_ORANGE_spread_mr, w=500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  85.23s] mix_pair_sanity 10000/11250: YELLOW_vs_ORANGE_spread_mr, w=1000, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  87.12s] mix_pair_sanity 10250/11250: YELLOW_vs_ORANGE_spread_mr, w=1500, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  89.09s] mix_pair_sanity 10500/11250: YELLOW_vs_ORANGE_spread_mr, w=1500, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80
[  90.52s] mix_pair_sanity 10750/11250: YELLOW_vs_ORANGE_spread_mr, w=2500, entry=2.0, exit=0.0, mode=zero_cross, hold=1000, gross=60
[  92.03s] mix_pair_sanity 11000/11250: YELLOW_vs_ORANGE_spread_mr, w=4000, entry=1.5, exit=0.0, mode=zero_cross, hold=2500, gross=40
[  93.52s] mix_pair_sanity 11250/11250: YELLOW_vs_ORANGE_spread_mr, w=4000, entry=2.25, exit=0.0, mode=zero_cross, hold=4000, gross=80

,candidate,family,kind,note,window,entry_z,exit_z,exit_mode,max_hold,gross,days,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
5695,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,4000,80,3,460520.0,153506.666667,112280.0,196020.0,9,1.000000,1.000000,51168.888889,0.425649,True,690580.000000
3145,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,4000,80,3,444020.0,148006.666667,88060.0,200500.0,6,0.833333,0.500000,74003.333333,0.451556,True,623056.666667
3070,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.25,NaN,fixed_hold,4000,80,3,430120.0,143373.333333,81160.0,193500.0,6,0.833333,0.500000,71686.666667,0.449874,True,595356.666667
5690,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,4000,60,3,345390.0,115130.000000,84210.0,147015.0,9,1.000000,1.000000,38376.666667,0.425649,True,519310.000000
190,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.75,NaN,fixed_hold,1500,80,3,366490.0,122163.333333,68990.0,154510.0,20,0.698413,0.571429,18324.500000,0.421594,True,507676.349206
3140,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,4000,60,3,333015.0,111005.000000,66045.0,150375.0,6,0.833333,0.500000,55502.500000,0.451556,True,468021.666667
3065,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.25,NaN,fixed_hold,4000,60,3,322590.0,107530.000000,60870.0,145125.0,6,0.833333,0.500000,53765.000000,0.449874,True,447246.666667
115,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.50,NaN,fixed_hold,1500,80,3,364790.0,121596.666667,31000.0,195470.0,21,0.761905,0.714286,17370.952381,0.535843,True,427158.126998
925,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.75,NaN,fixed_hold,1000,80,3,277500.0,92500.000000,62330.0,111700.0,19,0.634921,0.571429,14605.263158,0.402523,True,405334.603175
185,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.75,NaN,fixed_hold,1500,60,3,274867.5,91622.500000,51742.5,115882.5,20,0.698413,0.571429,13743.375000,0.421594,True,381558.849206
6625,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,1500,2.00,NaN,fixed_hold,1000,80,3,240320.0,80106.666667,59900.0,104100.0,20,0.698413,0.666667,12016.000000,0.433172,True,363802.539683
5685,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,4000,40,3,230260.0,76753.333333,56140.0,98010.0,9,1.000000,1.000000,25584.444444,0.425649,True,348040.000000
2995,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1500,2.25,NaN,fixed_hold,4000,80,3,341920.0,113973.333333,740.0,196900.0,6,0.833333,0.500000,56986.666667,0.575866,True,338730.096709
110,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.50,NaN,fixed_hold,1500,60,3,273592.5,91197.500000,23250.0,146602.5,21,0.761905,0.714286,13028.214286,0.535843,True,320460.626998
5665,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,1500,80,3,220680.0,73560.000000,45640.0,90080.0,21,0.619048,0.428571,10508.571429,0.408193,True,314412.380952
3135,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,4000,40,3,222010.0,74003.333333,44030.0,100250.0,6,0.833333,0.500000,37001.666667,0.451556,True,312986.666667
835,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.50,NaN,fixed_hold,500,80,3,223880.0,74626.666667,42860.0,110050.0,40,0.597070,0.461538,5597.000000,0.491558,True,312206.227106
920,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.75,NaN,fixed_hold,1000,60,3,208125.0,69375.000000,46747.5,83775.0,19,0.634921,0.571429,10953.947368,0.402523,True,304794.603175
3060,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.25,NaN,fixed_hold,4000,40,3,215060.0,71686.666667,40580.0,96750.0,6,0.833333,0.500000,35843.333333,0.449874,True,299136.666667
6620,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,1500,2.00,NaN,fixed_hold,1000,60,3,180240.0,60080.000000,44925.0,78075.0,20,0.698413,0.666667,9012.000000,0.433172,True,273772.539683
415,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.25,NaN,fixed_hold,1500,80,3,245300.0,81766.666667,10410.0,142120.0,18,0.666667,0.666667,13627.777778,0.579372,True,261849.446936
180,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.75,NaN,fixed_hold,1500,40,3,183245.0,61081.666667,34495.0,77255.0,20,0.698413,0.571429,9162.250000,0.421594,True,255441.349206
2990,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1500,2.25,NaN,fixed_hold,4000,60,3,256440.0,85480.000000,555.0,147675.0,6,0.833333,0.500000,42740.000000,0.575866,True,252880.096709
5660,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,1500,60,3,165510.0,55170.000000,34230.0,67560.0,21,0.619048,0.428571,7881.428571,0.408193,True,236422.380952
830,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.50,NaN,fixed_hold,500,60,3,167910.0,55970.000000,32145.0,82537.5,40,0.597070,0.461538,4197.750000,0.491558,True,234806.227106
3119,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,1500,80,3,153060.0,51020.000000,31480.0,70540.0,21,0.757937,0.666667,7288.571429,0.460865,True,219732.301587
3149,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,4000,80,3,156700.0,52233.333333,32280.0,90940.0,18,0.715873,0.600000,8705.555556,0.580345,True,216583.475755
105,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,500,1.50,NaN,fixed_hold,1500,40,3,182395.0,60798.333333,15500.0,97735.0,21,0.761905,0.714286,8685.476190,0.535843,True,213763.126998
3134,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,2500,80,3,154820.0,51606.666667,31600.0,90940.0,19,0.738095,0.666667,8148.421053,0.587392,True,212983.199968
10495,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,2.25,NaN,fixed_hold,4000,80,3,149820.0,49940.000000,26040.0,75020.0,7,0.555556,0.500000,21402.857143,0.500734,True,204604.356339
915,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.75,NaN,fixed_hold,1000,40,3,138750.0,46250.000000,31165.0,55850.0,19,0.634921,0.571429,7302.631579,0.402523,True,204254.603175
8620,YELLOW_vs_ORANGE_ratio_mr,pairwise,pair_ratio,YELLOW / ORANGE ratio mean reversion,1500,2.25,NaN,fixed_hold,4000,80,3,150900.0,50300.000000,25120.0,77020.0,7,0.555556,0.500000,21557.142857,0.510404,True,202877.353656
760,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.25,NaN,fixed_hold,500,80,3,129650.0,43216.666667,34660.0,47650.0,43,0.606349,0.533333,3015.116279,0.367528,True,201939.841270
535,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.75,NaN,fixed_hold,500,80,3,135700.0,45233.333333,29120.0,65920.0,42,0.622833,0.533333,3230.952381,0.485777,True,196918.083028
410,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.25,NaN,fixed_hold,1500,60,3,183975.0,61325.000000,7807.5,106590.0,18,0.666667,0.666667,10220.833333,0.579372,True,195319.446936
6615,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,1500,2.00,NaN,fixed_hold,1000,40,3,120160.0,40053.333333,29950.0,52050.0,20,0.698413,0.666667,6008.000000,0.433172,True,183742.539683
2260,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1000,1.25,NaN,fixed_hold,500,80,3,145440.0,48480.000000,21360.0,84080.0,49,0.547712,0.466667,2968.163265,0.578108,True,182956.408464
2985,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1500,2.25,NaN,fixed_hold,4000,40,3,170960.0,56986.666667,370.0,98450.0,6,0.833333,0.500000,28493.333333,0.575866,True,167030.096709
3114,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,1500,60,3,114795.0,38265.000000,23610.0,52905.0,21,0.757937,0.666667,5466.428571,0.460865,True,165727.301587
3144,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,4000,60,3,117525.0,39175.000000,24210.0,68205.0,18,0.715873,0.600000,6529.166667,0.580345,True,161268.475755
3129,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,2500,60,3,116115.0,38705.000000,23700.0,68205.0,19,0.738095,0.666667,6111.315789,0.587392,True,158478.199968
5655,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,NaN,fixed_hold,1500,40,3,110340.0,36780.000000,22820.0,45040.0,21,0.619048,0.428571,5254.285714,0.408193,True,158432.380952
825,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.50,NaN,fixed_hold,500,40,3,111940.0,37313.333333,21430.0,55025.0,40,0.597070,0.461538,2798.500000,0.491558,True,157406.227106
10490,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,2.25,NaN,fixed_hold,4000,60,3,112365.0,37455.000000,19530.0,56265.0,7,0.555556,0.500000,16052.142857,0.500734,True,154129.356339
8615,YELLOW_vs_ORANGE_ratio_mr,pairwise,pair_ratio,YELLOW / ORANGE ratio mean reversion,1500,2.25,NaN,fixed_hold,4000,60,3,113175.0,37725.000000,18840.0,57765.0,7,0.555556,0.500000,16167.857143,0.510404,True,152592.353656
755,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.25,NaN,fixed_hold,500,60,3,97237.5,32412.500000,25995.0,35737.5,43,0.606349,0.533333,2261.337209,0.367528,True,152197.341270
530,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.75,NaN,fixed_hold,500,60,3,101775.0,33925.000000,21840.0,49440.0,42,0.622833,0.533333,2423.214286,0.485777,True,148433.083028
5188,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.75,abs_band,500,80,3,99840.0,33280.000000,22840.0,53400.0,20,0.603175,0.428571,4992.000000,0.534856,True,144478.867521
3115,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,1500,80,3,122220.0,40740.000000,10920.0,66280.0,14,0.633333,0.500000,8730.000000,0.542301,True,142646.589756
5187,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,500,80,3,110640.0,36880.000000,18500.0,65860.0,20,0.603175,0.428571,5532.000000,0.595264,True,140558.052543
2255,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1000,1.25,NaN,fixed_hold,500,60,3,109080.0,36360.000000,16020.0,63060.0,49,0.547712,0.466667,2226.122449,0.578108,True,135916.408464
10345,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,1.75,NaN,fixed_hold,4000,80,3,107940.0,35980.000000,17520.0,64720.0,8,0.500000,0.333333,13492.500000,0.599592,True,134937.430054
5202,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,1000,80,3,112720.0,37573.333333,10660.0,64560.0,16,0.700000,0.500000,7045.000000,0.572747,True,129615.337119
405,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.25,NaN,fixed_hold,1500,40,3,122650.0,40883.333333,5205.0,71060.0,18,0.666667,0.666667,6813.888889,0.579372,True,128789.446936
5186,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.25,abs_band,500,80,3,80960.0,26986.666667,16980.0,34000.0,20,0.547619,0.428571,4048.000000,0.419960,True,117336.666667
3109,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,1500,40,3,76530.0,25510.000000,15740.0,35270.0,21,0.757937,0.666667,3644.285714,0.460865,True,111722.301587
5183,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.75,abs_band,500,60,3,74880.0,24960.000000,17130.0,40050.0,20,0.603175,0.428571,3744.000000,0.534856,True,108098.867521
3110,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,1500,60,3,91665.0,30555.000000,8190.0,49710.0,14,0.633333,0.500000,6547.500000,0.542301,True,106631.589756
3139,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,4000,40,3,78350.0,26116.666667,16140.0,45470.0,18,0.715873,0.600000,4352.777778,0.580345,True,105953.475755
3124,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,0.00,zero_cross,2500,40,3,77410.0,25803.333333,15800.0,45470.0,19,0.738095,0.666667,4074.210526,0.587392,True,103973.199968
10485,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,2.25,NaN,fixed_hold,4000,40,3,74910.0,24970.000000,13020.0,37510.0,7,0.555556,0.500000,10701.428571,0.500734,True,103654.356339
5182,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,500,60,3,82980.0,27660.000000,13875.0,49395.0,20,0.603175,0.428571,4149.000000,0.595264,True,103648.052543
750,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1500,1.25,NaN,fixed_hold,500,40,3,64825.0,21608.333333,17330.0,23825.0,43,0.606349,0.533333,1507.558140,0.367528,True,102454.841270
8610,YELLOW_vs_ORANGE_ratio_mr,pairwise,pair_ratio,YELLOW / ORANGE ratio mean reversion,1500,2.25,NaN,fixed_hold,4000,40,3,75450.0,25150.000000,12560.0,38510.0,7,0.555556,0.500000,10778.571429,0.510404,True,102307.353656
525,mix_RED_blend_YELLOW_MAGENTA_75_25_mr,colour_mixing,mix_mr,RED residual vs 75% YELLOW + 25% MAGENTA,1000,1.75,NaN,fixed_hold,500,40,3,67850.0,22616.666667,14560.0,32960.0,42,0.622833,0.533333,1615.476190,0.485777,True,99948.083028
10340,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,1.75,NaN,fixed_hold,4000,60,3,80955.0,26985.000000,13140.0,48540.0,8,0.500000,0.333333,10119.375000,0.599592,True,99192.430054
5197,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,1000,60,3,84540.0,28180.000000,7995.0,48420.0,16,0.700000,0.500000,5283.750000,0.572747,True,96105.337119
2250,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,1000,1.25,NaN,fixed_hold,500,40,3,72720.0,24240.000000,10680.0,42040.0,49,0.547712,0.466667,1484.081633,0.578108,True,88876.408464
5181,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.25,abs_band,500,60,3,60720.0,20240.000000,12735.0,25500.0,20,0.547619,0.428571,3036.000000,0.419960,True,88606.666667
3194,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.75,0.00,zero_cross,1500,80,3,48500.0,16166.666667,12660.0,18460.0,12,0.738889,0.666667,4041.666667,0.380619,True,77522.777778
5185,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,NaN,fixed_hold,500,80,3,55700.0,18566.666667,8740.0,29980.0,20,0.452381,0.428571,2785.000000,0.538241,True,71724.990168
5178,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.75,abs_band,500,40,3,49920.0,16640.000000,11420.0,26700.0,20,0.603175,0.428571,2496.000000,0.534856,True,71718.867521
3105,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,NaN,fixed_hold,1500,40,3,61110.0,20370.000000,5460.0,33140.0,14,0.633333,0.500000,4365.000000,0.542301,True,70616.589756
6190,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,1000,1.75,NaN,fixed_hold,1500,80,3,48520.0,16173.333333,8160.0,20440.0,17,0.533333,0.500000,2854.117647,0.421270,True,67606.666667
5177,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,500,40,3,55320.0,18440.000000,9250.0,32930.0,20,0.603175,0.428571,2766.000000,0.595264,True,66738.052543
10335,YELLOW_vs_ORANGE_spread_mr,pairwise,pair_spread,YELLOW - ORANGE spread mean reversion,1500,1.75,NaN,fixed_hold,4000,40,3,53970.0,17990.000000,8760.0,32360.0,8,0.500000,0.333333,6746.250000,0.599592,True,63447.430054
5192,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.50,abs_band,1000,40,3,56360.0,18786.666667,5330.0,32280.0,16,0.700000,0.500000,3522.500000,0.572747,True,62595.337119
5176,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,0.25,abs_band,500,40,3,40480.0,13493.333333,8490.0,17000.0,20,0.547619,0.428571,2024.000000,0.419960,True,59876.666667
3189,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.75,0.00,zero_cross,1500,60,3,36375.0,12125.000000,9495.0,13845.0,12,0.738889,0.666667,3031.250000,0.380619,True,59067.777778
5180,mix_ORANGE_blend_YELLOW_RED_50_50_mr,colour_mixing,mix_mr,ORANGE residual vs 50% YELLOW + 50% RED,2500,2.25,NaN,fixed_hold,500,60,3,41775.0,13925.000000,6555.0,22485.0,20,0.452381,0.428571,2088.750000,0.538241,True,53429.990168

In [32]:
family_comparison = pd.concat(
    [
        focused_summary.assign(test_set="lead_lag_focused"),
        mix_summary.assign(test_set="mix_pair_sanity"),
    ],
    ignore_index=True,
)

family_table = (
    family_comparison
    .groupby(["test_set", "family"])
    .agg(
        best_total_pnl=("total_pnl", "max"),
        best_min_day_pnl=("min_day_pnl", "max"),
        best_robust_score=("robust_score", "max"),
        robust_count=("robust_pass", "sum"),
        configs=("candidate", "size"),
    )
    .sort_values("best_robust_score", ascending=False)
)

display(family_table)

                                best_total_pnl  best_min_day_pnl  best_robust_score  robust_count  configs
test_set         family
lead_lag_focused lead_lag             448840.0          122160.0      692171.111111          5394    20625
mix_pair_sanity  colour_mixing        460520.0          112280.0      690580.000000            78     7500
                 pairwise             150900.0           26040.0      204604.356339             9     3750

In [33]:
def candidate_card(summary_df, n=20):
    show_cols = [
        "candidate", "family", "kind", "note",
        "window", "entry_z", "exit_mode", "exit_z", "max_hold", "gross",
        "total_pnl", "mean_day_pnl", "min_day_pnl", "max_day_pnl",
        "total_trades", "mean_hit_rate", "min_hit_rate",
        "pnl_per_trade",
        "one_day_dependency", "robust_pass", "robust_score",
    ]
    return summary_df.sort_values(
        ["robust_pass", "robust_score", "min_day_pnl", "total_pnl"],
        ascending=[False, False, False, False],
    )[show_cols].head(n)


final_candidates = pd.concat(
    [
        focused_summary.assign(test_set="focused_lead_lag"),
        lag_sweep_summary.assign(test_set="lag_sweep"),
        mix_summary.assign(test_set="mix_pair_sanity"),
    ],
    ignore_index=True,
)

final_candidates = final_candidates.sort_values(
    ["robust_pass", "robust_score", "min_day_pnl", "total_pnl"],
    ascending=[False, False, False, False],
)

final_candidates.to_csv(OUT_DIR / "final_uv_visor_candidates_all.csv", index=False)

display(candidate_card(final_candidates, n=50))

,candidate,family,kind,note,window,entry_z,exit_mode,exit_z,max_hold,gross,total_pnl,mean_day_pnl,min_day_pnl,max_day_pnl,total_trades,mean_hit_rate,min_hit_rate,pnl_per_trade,one_day_dependency,robust_pass,robust_score
20625,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.25,fixed_hold,NaN,4000,80,415480.0,138493.333333,137760.0,139520.0,8,1.000000,1.000000,51935.000000,0.335804,True,696500.000000
20626,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.50,fixed_hold,NaN,4000,80,418440.0,139480.000000,135240.0,143400.0,8,1.000000,1.000000,52305.000000,0.342701,True,694420.000000
0,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,fixed_hold,NaN,1500,80,443440.0,147813.333333,122160.0,164760.0,17,0.822222,0.800000,26084.705882,0.371550,True,692171.111111
25025,mix_AMBER_blend_YELLOW_ORANGE_50_50_mr,colour_mixing,mix_mr,AMBER residual vs 50% YELLOW + 50% ORANGE,500,1.25,fixed_hold,NaN,4000,80,460520.0,153506.666667,112280.0,196020.0,9,1.000000,1.000000,51168.888889,0.425649,True,690580.000000
20627,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1000,2.00,fixed_hold,NaN,4000,80,410360.0,136786.666667,125840.0,153800.0,7,1.000000,1.000000,58622.857143,0.374793,True,667540.000000
20628,lead_YELLOW_to_RED_follow_lag2000,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 2000,250,1.25,fixed_hold,NaN,500,80,395520.0,131840.000000,122240.0,140400.0,46,0.675000,0.625000,8598.260870,0.354976,True,643462.500000
1,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,fixed_hold,NaN,1500,80,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
20629,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,500,2.00,fixed_hold,NaN,1500,80,426960.0,142320.000000,105120.0,184160.0,18,0.888889,0.833333,23720.000000,0.431328,True,641811.111111
2,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,fixed_hold,NaN,1500,72,399096.0,133032.000000,109944.0,148284.0,17,0.822222,0.800000,23476.235294,0.371550,True,623395.111111
25026,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.50,fixed_hold,NaN,4000,80,444020.0,148006.666667,88060.0,200500.0,6,0.833333,0.500000,74003.333333,0.451556,True,623056.666667
3,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.25,fixed_hold,NaN,4000,80,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
20630,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.25,fixed_hold,NaN,4000,80,386360.0,128786.666667,108440.0,139520.0,8,0.888889,0.666667,48295.000000,0.361114,True,607017.777778
4,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.25,fixed_hold,NaN,4000,80,411920.0,137306.666667,92840.0,167120.0,9,0.888889,0.666667,45768.888889,0.405710,True,601377.777778
5,lead_MAGENTA_to_YELLOW_follow_lag100,lead_lag,lead_lag,YELLOW follows MAGENTA return over lag 100,500,1.50,fixed_hold,NaN,500,80,370200.0,123400.000000,113280.0,138480.0,50,0.722222,0.666667,7404.000000,0.374068,True,600454.444444
20631,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,1500,1.25,fixed_hold,NaN,500,80,415080.0,138360.000000,92960.0,225840.0,36,0.715873,0.600000,11530.000000,0.544088,True,599949.147841
6,lead_AMBER_to_MAGENTA_inverse_lag50,lead_lag,lead_lag,MAGENTA inversely follows AMBER return over la...,250,1.75,fixed_hold,NaN,500,80,386680.0,128893.333333,105000.0,160760.0,54,0.597007,0.500000,7160.740741,0.415744,True,599478.503612
25027,mix_RED_blend_YELLOW_MAGENTA_50_50_mr,colour_mixing,mix_mr,RED residual vs 50% YELLOW + 50% MAGENTA,2500,1.25,fixed_hold,NaN,4000,80,430120.0,143373.333333,81160.0,193500.0,6,0.833333,0.500000,71686.666667,0.449874,True,595356.666667
20632,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,250,2.00,fixed_hold,NaN,500,80,398840.0,132946.666667,96560.0,163000.0,51,0.627723,0.611111,7820.392157,0.408685,True,595329.417211
7,lead_AMBER_to_ORANGE_follow_lag100,lead_lag,lead_lag,ORANGE follows AMBER return over lag 100,500,1.75,fixed_hold,NaN,4000,80,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
20633,lead_AMBER_to_ORANGE_follow_lag100,lead_lag_lag_sweep,lead_lag,ORANGE follow follows AMBER return over lag 100,500,1.75,fixed_hold,NaN,4000,80,438280.0,146093.333333,74200.0,214080.0,9,0.888889,0.666667,48697.777778,0.488455,True,590457.777778
8,lead_YELLOW_to_RED_follow_lag1000,lead_lag,lead_lag,RED follows YELLOW return over lag 1000,500,1.25,fixed_hold,NaN,1000,80,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
20634,lead_YELLOW_to_RED_follow_lag1000,lead_lag_lag_sweep,lead_lag,RED follow follows YELLOW return over lag 1000,500,1.25,fixed_hold,NaN,1000,80,448840.0,149613.333333,68120.0,191040.0,27,0.851852,0.777778,16623.703704,0.425631,True,589394.814815
9,lead_AMBER_to_RED_inverse_lag1000,lead_lag,lead_lag,RED inversely follows AMBER return over lag 1000,1000,1.25,fixed_hold,NaN,2500,80,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
20635,lead_AMBER_to_RED_inverse_lag1000,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 1000,1000,1.25,fixed_hold,NaN,2500,80,370280.0,123426.666667,107360.0,140840.0,11,0.805556,0.666667,33661.818182,0.380361,True,588736.111111
10,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,1.50,fixed_hold,NaN,4000,80,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
20636,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,1.50,fixed_hold,NaN,4000,80,381480.0,127160.000000,102040.0,139920.0,8,0.777778,0.333333,47685.000000,0.366782,True,587615.555556
11,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,zero_cross,0.00,500,80,391080.0,130360.000000,95880.0,193280.0,42,0.617827,0.571429,9311.428571,0.494221,True,586006.056166
12,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,fixed_hold,NaN,500,80,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
20637,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,1000,1.25,fixed_hold,NaN,500,80,408480.0,136160.000000,89600.0,224440.0,42,0.633333,0.500000,9725.714286,0.549452,True,585551.504113
13,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.25,abs_band,0.25,500,80,426360.0,142120.000000,75720.0,220400.0,66,0.702648,0.631579,6460.000000,0.516934,True,579615.813866
14,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,500,2.00,fixed_hold,NaN,1500,72,384264.0,128088.000000,94608.0,165744.0,18,0.888889,0.833333,21348.000000,0.431328,True,578091.111111
20638,lead_ORANGE_to_YELLOW_follow_lag250,lead_lag_lag_sweep,lead_lag,YELLOW follow follows ORANGE return over lag 250,1500,1.50,fixed_hold,NaN,4000,80,349080.0,116360.000000,112480.0,120200.0,8,0.777778,0.666667,43635.000000,0.344334,True,577762.222222
15,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,zero_cross,0.00,1000,80,361360.0,120453.333333,104480.0,138680.0,34,0.717236,0.555556,10628.235294,0.383772,True,573456.396011
20639,lead_RED_to_YELLOW_inverse_lag150,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 150,250,1.75,fixed_hold,NaN,2500,80,374560.0,124853.333333,98000.0,160520.0,12,0.666667,0.500000,31213.333333,0.428556,True,573393.333333
20640,lead_AMBER_to_RED_inverse_lag100,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 100,250,1.25,fixed_hold,NaN,1000,80,415200.0,138400.000000,77680.0,196680.0,30,0.633333,0.400000,13840.000000,0.473699,True,572876.666667
16,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,abs_band,0.25,1500,80,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
17,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,abs_band,0.25,2500,80,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
18,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,abs_band,0.25,4000,80,371000.0,123666.666667,98200.0,172040.0,41,0.754762,0.714286,9048.780488,0.463720,True,571348.809524
20641,lead_RED_to_YELLOW_inverse_lag500,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 500,1000,1.75,fixed_hold,NaN,4000,80,361400.0,120466.666667,101880.0,144640.0,7,1.000000,1.000000,51628.571429,0.400221,True,570660.000000
19,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,zero_cross,0.00,1500,80,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
20,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,zero_cross,0.00,2500,80,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
21,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,750,2.00,zero_cross,0.00,4000,80,353920.0,117973.333333,104480.0,138680.0,34,0.717236,0.555556,10409.411765,0.391840,True,566016.396011
22,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1000,1.75,abs_band,0.25,1000,80,368720.0,122906.666667,95920.0,172040.0,41,0.754762,0.714286,8993.170732,0.466587,True,564508.809524
23,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,500,2.00,fixed_hold,NaN,1500,80,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
20642,lead_RED_to_YELLOW_inverse_lag1000,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 1000,500,2.00,fixed_hold,NaN,1500,80,362240.0,120746.666667,99120.0,143560.0,17,0.766667,0.666667,21308.235294,0.396312,True,564196.666667
20643,lead_AMBER_to_RED_inverse_lag100,lead_lag_lag_sweep,lead_lag,RED inverse follows AMBER return over lag 100,250,1.25,fixed_hold,NaN,500,80,347760.0,115920.000000,104880.0,130040.0,57,0.596491,0.578947,6101.052632,0.373936,True,560712.982456
20644,lead_RED_to_YELLOW_inverse_lag750,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 750,500,2.00,fixed_hold,NaN,4000,80,361800.0,120600.000000,97560.0,153920.0,9,0.777778,0.333333,40200.000000,0.425428,True,558975.555556
24,lead_RED_to_YELLOW_inverse_lag1000,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 1000,1500,1.25,abs_band,0.25,500,80,374400.0,124800.000000,90160.0,188600.0,45,0.625397,0.500000,8320.000000,0.503739,True,557158.766789
25,lead_RED_to_YELLOW_inverse_lag250,lead_lag,lead_lag,YELLOW inversely follows RED return over lag 250,1000,1.25,fixed_hold,NaN,4000,80,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556
20645,lead_RED_to_YELLOW_inverse_lag250,lead_lag_lag_sweep,lead_lag,YELLOW inverse follows RED return over lag 250,1000,1.25,fixed_hold,NaN,4000,80,354920.0,118306.666667,99920.0,154360.0,9,0.777778,0.333333,39435.555556,0.434915,True,556815.555556